- components/ConfigProvider/__demo__/local-setting.md
- components/Modal/useModal/index.tsx
|   Modal    |  修复 `useModal` 的 `holderRef` 可能不存在的 bug    |  Fix the bug that the `holderRef` of `useModal` may not exist    |    Closed: #1416    |
> fix: the bug that the holderRef of useModal may not exist

- components/Table/README.en-US.md
- components/Table/README.zh-CN.md
- components/Table/interface.tsx
The current Table's checkCrossPage API states it can only be used in "uncontrolled mode", but actually, it can be used in "controlled mode" with preserveSelectedRowKeys: true.
This PR improves and clarifies the description of Table's checkCrossPage API, to help Arco Design's users to use checkCrossPage API while in controlled mode.
https://github.com/arco-design/arco-design/issues/1412
This PR modified the documentation.
> doc: improve Table checkCrossPage description

- components/TimePicker/README.zh-CN.md
- components/TimePicker/interface.tsx
> typo: TimePicker onSelect

- components/Image/image.tsx
- components/Image/style/image.less
- [] Enhancement
| Image |  Image 组件的开启 `preview` 后，鼠标悬停样式变为 `zoom-out` |  After opening `preview` of the Image component, the hover style changes to `zoom-out` |    Closed: #1407     |
> enhance: The previewable image mouseover style changes to zoom-out

- components/Table/utils.tsx
| Table   |  修复 Table 在关闭 `checkStrictly` 后，传入不存在的 `selectedKey` 导致页面报错的 bug  |  Fix the bug that when Table is turned off `checkStrictly`, passing in non-existing `selectedKeys` will  report an error  |  Closed: #1405  |
> fix: Table getRowKey throw error when the record is not found

- components/Popconfirm/index.tsx
|   Popconfirm        |     修复 `Popconfirm` 组件开启 `focusLock` 时，Footer 内部 DOM 层级表现和默认不一致，导致按钮外边距样式失效的问题          |     Fixed the issue that when the `Popconfirm` component enables `focusLock`, the performance of the DOM level inside the Footer is inconsistent with the default, causing the button margin style to fail.       |                |
> fix: popconfirm focuslock

- components/Modal/modal.tsx
- components/_util/dom.ts
|    Modal       |     修复 Modal 组件嵌套在 iframe 里时自动 focus 导致父页面失焦的 bug 。          |   Fix the bug that the auto focus of the Modal component is nested in an iframe, causing the parent page to lose focus.            |     close #1435         |
> fix: Avoid auto focus of modal component when modal is inside iframe

- components/Table/style/index.less
|  Table  | 修复 `Table` 组件展开行嵌套子表格时，子表格开启固定列会出现单元格透明的问题。   |Fixed the issue that when the `Table` component expands a row and nested a sub table, the cell transparent problem occurs when the subtable opens fixed column.  | Close: https://github.com/arco-design/arco-design/issues/1427 |
> style: Sub table in table expand content, cell color error

- components/Modal/confirm.tsx
- components/_util/react-dom.ts
- stories/Modal.story.tsx
|   Modal        |      修复 `Modal` 组件在 React 18  下卸载时控制台出现 warning 的 bug      |   Fix the bug of console warning when `Modal` component is uninstalled under React 18            |     Close #1424  Close #1406        |
> fix: modal unmount error in react18

- components/Layout/sider.tsx
|   Layout        |  修复 `Layout.Sider` 组件 `defaultCollapsed` 属性未生效的 bug。  |  Fixed the bug that `defaultCollapsed` of `Layout.Sider` component did not take effect.  |  Close #1448 |
> fix: Layout.Sider defaultCollapsed not work

- components/ConfigProvider/README.zh-CN.md
- components/Drawer/README.en-US.md
- components/Drawer/README.zh-CN.md
- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/form-label.tsx
- components/Form/interface.tsx
- components/Table/README.zh-CN.md
|    Form       |     `Form` 组件的 `colon` 属性支持传入 `ReactNode`。          |      The `colon` property of the `Form` component supports passing a `ReactNode`.         |       Close #1451          |
> feat(Form): colon property supports ReactNode

- components/Tabs/style/index.less
|   Tabs        |  修复暗黑模式下 `Tabs` 组件的新增图标色值有误的 bug。             |  Fixed a bug where the new icon color value of the `Tabs` component in dark mode was incorrect.             |      Close #1452           |
> style(Tabs): fix the color of the add icon

- components/Cascader/cascader.tsx
- components/TreeSelect/tree-select.tsx
|  TreeSelect   |  修复 `TreeSelect` 受控清空 `inputValue` 后无法再次输入相同值的 bug  |  Fixed the bug that the same value could not be entered again after `TreeSelect` was controlled to empty `inputValue`   |   Closed: #1378   |
> fix: treeselect inputvalue  can't change when it is controlled

- components/DatePicker/__demo__/timezone.md
- components/DatePicker/__demo__/utcOffset.md
Fix DatePicker demo error in safari
> docs: fix DatePicker demo error in safari

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Cascader/__demo__/addon.md
- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/cascader.tsx
- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/Select/__demo__/addbefore.md
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Select/select.tsx
- components/Select/style/mixin.less
- components/Select/style/token.less
- components/TreeSelect/README.en-US.md
- components/TreeSelect/README.zh-CN.md
- components/TreeSelect/__demo__/addon.md
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/tree-select.tsx
- components/_class/select-view.tsx
|  Select         |   `Select` 组件支持通过 `addBefore` 属性设置前置标签            |    The `Select` component supports setting the front tag through the `addBefore` property           |        close #1428         |
|  TreeSelect         |   `TreeSelect` 组件支持通过 `addBefore` 属性设置前置标签            |    The `TreeSelect` component supports setting the front tag through the `addBefore` property           |        close #1428         |
|  Cascader         |   `Cascader` 组件支持通过 `addBefore` 属性设置前置标签            |    The `Cascader` component supports setting the front tag through the `addBefore` property           |        close #1428         |
> feat: Select, Cascader, TreeSelect support addBefore

- components/Cascader/__test__/case.test.tsx
- components/Cascader/panel/list.tsx
- components/Cascader/util.tsx
|   Cascader        |    优化 `Cascader` 组件选项的 `title` 属性显示 `[object object]` 的问题。          |    Optimized the problem that the `title` property of the `Cascader` component option displays `[object object]`.|       close #1450        |
|   Cascader        |    修复 `Cascader` 组件在设置 `changeOnSelect` & `mode=multiple` 时，子节点选中后父节点无法被选中的 bug           |    Fixed the bug that the parent node cannot be selected after the child node is selected when the `Cascader` component is set to `changeOnSelect` & `mode=multiple`           |       close #1423        |
> fix: cascader can not select parent node when changeOnSelect=true

- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Upload/README.en-US.md
- components/Upload/README.zh-CN.md
- components/Upload/__demo__/preview.md
- components/Upload/__test__/__snapshots__/demo.test.ts.snap
- components/Upload/interface.tsx
- components/Upload/list/index.tsx
- components/Upload/list/pictureItem.tsx
- components/Upload/style/index.ts
- components/Upload/trigger-node.tsx
- components/Upload/upload.tsx
- components/Upload/uploader.tsx
|   Upload        |   `Upload` 组件支持通过 `imagePreview` 属性启用内置的图片预览功能。            |        The `Upload` component supports enabling built-in image preview functionality via the `imagePreview` property.       |    Close #1410             |
|     Upload      |          `Upload` 组件支持 `onDragLeave` 和 `onDragOver` 事件回调        |         `Upload` component supports `onDragLeave` and `onDragOver` event callbacks      |   Close #1442              |
> feat: upload supports imagePreview & onDragOver & onDragLeave

- components/Image/style/image.less
|Image|  `Image` 组件悬浮时显示`zoom-in`鼠标类型|Show `zoom-in` mouse type when `Image` component is hovered|                |
> Style: change image with preview cursor type

- components/Tabs/__test__/index.test.tsx
- components/Tabs/tab-content.tsx
to fix: https://github.com/arco-design/arco-design/issues/1473
close: https://github.com/arco-design/arco-design/issues/1473
|    Tabs     | 修复 `Tabs` 组件在 `RTL` 视图下水平滚动方向错误的 bug。 | Fix the bug that is wrong in the horizontal scrolling direction under the `RTL` view.   |       Closed: #1473        |
> fix(Tabs): tab can't change when in right direction

- components/Table/style/index.less
|  Table   |修复 `Table` 组件当 `scroll.x` 过小时总结列高度塌陷的样式问题。 | Fixed `Table` component's style issue of collapsed column height when `scroll.x` is too small.    |   Close: https://github.com/arco-design/arco-design/issues/1488    |
> fix: Table foot height collapse when scroll.x is too small

- components/Tabs/style/index.less
|    Tabs       |        修复 `Tabs` 组件 `extra` 元素较大宽度时被遮盖样式问题。       |       Fix `Tabs` component's `extra` element's style issue that is covered when the width is large.        |                |
> style: tabs extra flex-shrink

- components/Slider/hooks/useInterval.ts
- components/Slider/hooks/useLegalValue.ts
修复`Slider`组件每次渲染都会执行useUpdate的问题。 [L87](https://github.com/arco-design/arco-design/blob/main/components/Slider/index.tsx#L87)行在Slider组件更新时都会执行，因为 [useLegalValue](https://github.com/arco-design/arco-design/blob/main/components/Slider/index.tsx#L63)每次返回的getLegalRangeValue函数都是新的
使用useCallback重写useInterval以及useLegalValue
原有测试用例
|      Slider     |  减少 `Slider` 触发区间计算的次数   |    Reduce the number of times `Slider` triggers interval calculations       |                |
> fix: silder hooks usecallback

- components/Image/style/image.less
Add overflow: hidden to arco-image, to prevent footer bottom border radius overflow, when set large border radius.
增加overflow: hidden给arco-image，防止当圆角被设置为大圆角时，footer底部圆角溢出。
|Image| 修复 `Image` 组件`border-radius`较大时，`footer` 区域底部圆角溢出的样式问题。|Fixed a style issue where the bottom corners of the `footer` area overflow when the `border-radius` of the `Image` component is large.|                |
> Style: add Image footer bottom border radius

- site/package.json
- site/src/App.js
- site/src/hooks/useTheme.ts
- site/src/index-en.js
- site/src/index.js
- site/src/pages/home/hooks/useTheme.ts
- site/src/pages/home/utils/cdn-resource.ts
- site/yarn.lock
Modification of the home page（10.07-10.28)
- Material Cover Replacement,
- Navigation and Footer Upgrade
> Homepage Material Cover Replacement, Navigation and Footer Upgrade

- components/DatePicker/panels/date/index.tsx
Close: https://github.com/arco-design/arco-design/issues/1518
> fix: DatePicker timepickerProps omit disableConfirm

- components/Button/style/index.less
- stories/Button.story.tsx
| Button |  修复文字按钮在 `Button.Group` 下边框样式出错的 bug   |    Fix the bug that the border style of text buttons is wrong under `Button.Group`      |     Closed: #1514     |
> style: border problem of text button in Button.Group

- components/Collapse/README.en-US.md
- components/Collapse/README.zh-CN.md
- components/Collapse/__demo__/activeRegion.md
- components/Collapse/__test__/__snapshots__/demo.test.ts.snap
- components/Collapse/__test__/index.test.tsx
- components/Collapse/collapse.tsx
- components/Collapse/interface.ts
- components/Collapse/item.tsx
- components/Collapse/style/index.less
|   Collapse   | `Collapse` 组件新增 `triggerRegion` 属性以自定义折叠触发区域。 |  The `Collapse` component adds a `triggerRegion` property to customize the collapse trigger region.  |  Close #1411  |
> feat: Collase add property triggerRegion

- components/Select/style/mixin.less
Select 新增的 DOM 结构导致组件的 baseline 发生改变。
|  Select  |  修复 `Select` 组件在 `Input.Group` 内使用时竖直方向无法对齐的问题。  |  Fixed `Select` vertical alignment problem when used in `Input.Group`.  |      Close #1529     |
> style: select-view style forward compatibility and solve baseline issue

- components/Form/style/index.less
- components/Form/style/token.less
> style: add form token

- components/Menu/overflow-wrap.tsx
- components/Menu/style/index.less
|  Menu  |  优化 `Menu` 组件水平模式自动折叠时可能出现的抖动问题。             |   Optimize the jitter problem that may occur when the horizontal mode of the `Menu` component is automatically collapsed.  |                |
> enhancement: auto wrap performance of horizontal Menu

- .github/workflows/deploy-site-preview.yml
> chore: add site preview .yml

- netlify.toml
> chore: update pr preview url

- .github/workflows/deploy-site-preview.yml
- .gitignore
- components/Dropdown/__demo__/position.md
- package.json
- tests/screenshots.js
- yarn.lock
> test: add screenshots test

- components/Drawer/README.en-US.md
- components/Drawer/README.zh-CN.md
- components/Drawer/interface.ts
- components/Modal/README.en-US.md
- components/Modal/README.zh-CN.md
- components/Modal/interface.ts
- components/Popconfirm/README.en-US.md
- components/Popconfirm/README.zh-CN.md
- components/Popconfirm/interface.ts
|  Common   |  调整 `Modal` `Drawer` `Popconfirm` 参数 `okText` 和 `cancelText` 属性的 TS 定义为 `ReactNode`。  | Adjust the TS definition of `Modal` `Drawer` `Popconfirm` parameters `okText` and `cancelText` properties to `ReactNode`.| Close: https://github.com/arco-design/arco-design/issues/1547 |
> enhance: Modal,Drawer,Popconfirm okText and cancelText support ReactNode

- components/Layout/sider.tsx
|  Layout   |   修复 `Layout.Sider` 在默认开启 `collapsed` 时，初次渲染会闪动的 bug   |  Fixed the bug that `Layout.Sider` would flicker for the first rendering when `collapsed` is enabled by default    |  Closed: #1550  |
> fix: the `Layout.Sider` would flicker for the first rendering when `collapsed` is enabled by default

- components/_class/VirtualList/index.tsx
|   Common   |   优化虚拟列表在滚动至底部时可能出现的抖动问题。   |  Optimize the jitter problem that may occur when the virtual list is scrolled to the bottom.    |                |
> enhance: VirtualList performance while scrolling near the list bottom

- components/Table/tbody/td.tsx
| Table  |  减少 `Table` 组件 `column.render` 不合预期的渲染次数。  |  Reduced unexpected rendering times of `Table` component `column.render`.   |  Close: https://github.com/arco-design/arco-design/issues/1485  |
> enhance: Table column.render optimization

- components/InputNumber/index.tsx
- components/InputNumber/useSelectionRange.ts
|  InputNumber  |  优化带有 `formatter` 的 `InputNumber` 组件在用户输入时光标位置自动回退至文本尾部的问题。  |  Optimize the problem that the `InputNumber` with `formatter` automatically move back to the end of the text when the user is typing.   |   Close #1549  |
> enhance: InputNumber keep cursor position while user typing

- components/Steps/style/circle.less
- components/Steps/style/dot.less
- components/Steps/style/index.less
- stories/Steps.story.tsx
|     Steps      |   修复 `Steps` 组件在嵌套使用时样式错误的 bug   |Fixed a bug where the `Steps` component had the wrong style when it was nested |                |
> style(Steps): steps are used as children of steps

- .github/workflows/deploy-site-preview.yml
> chore: update ci env

- components/Upload/util.tsx
|  Upload         |      修复 `Upload` 组件对大写后缀名文件错误过滤的 bug。          | Fixed a bug that the `Upload` component incorrectly filters files with uppercase suffixes.              | #1560               |
> fix(upload): upload accept can receive upper file extensions

- .github/workflows/deploy-site-preview.yml
- components/TreeSelect/__demo__/labelInvalue.md
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- tests/screenshots.js
> docs: udpate treeselect demo

- components/DatePicker/__test__/range.test.tsx
- components/DatePicker/picker-range.tsx
| DatePicker   |  修复 `DatePicker.Range` 组件在面板打开时，切换 `mode` 时面板日期不正确的 bug。   |  Fix `DatePicker.Range` component when the panel is open, the panel date is incorrect bug when switching `mode`. |  Close: https://github.com/arco-design/arco-design/issues/1570  |
> fix: when panel open, change mode page show dates correctly

- components/Steps/style/circle.less
| Steps   | 修复 `Steps` 在标签位置为 `vertical` 时不展示连接线的 bug |  Fix the bug that `Steps` does not display connecting lines when the label position is `vertical`  | closed: #1575 |
> style(Steps): label vertical placement

- components/Radio/README.en-US.md
|       Radio    |    修复api文档英文描述错误           |       fix english api describe error        |      close: #1597            |
> doc(Radio): fix english api describe error

- site/docs/designlab/use-theme-package.en-US.md
- site/docs/designlab/use-theme-package.zh-CN.md
- tests/screenshots.js
> docs: update theme doc

- components/Table/__test__/case.test.tsx
- components/Table/utils.tsx
|  Table  |  修复 `Table` 组件 data 为 `number[]` 或 `string[]` 时，报错的问题。   |  Fix the bug of reporting an error when the data of the `Table` component is `number[]` or `string[]`.   |   Close: https://github.com/arco-design/arco-design/issues/1608  |
> fix: Table data is array of number or string, cause error

- components/Upload/trigger-node.tsx
|   Upload        |     `Upload` 支持通过 `drag=false` 设置关闭拖拽上传          |     `Upload` supports turning off drag upload by setting `drag=false`          |                |
> feat: Upload disbaled drag by drag=false

- components/InputNumber/Decimal.ts
- components/InputNumber/README.en-US.md
- components/InputNumber/README.zh-CN.md
- components/InputNumber/__demo__/strictMode.md
- components/InputNumber/__test__/__snapshots__/demo.test.ts.snap
- components/InputNumber/__test__/index.test.tsx
- components/InputNumber/index.tsx
- components/InputNumber/interface.ts
- components/InputNumber/utils.ts
- stories/InputNumber.story.tsx
|   InputNumber      |  `InputNumber` 新增 `strictMode` 以支持大数和高精度小数。 |    `InputNumber` adds `strictMode` to support large numbers and high precision decimals.         |  Close #1531       Close #1263   |
> feat: InputNumber support BigInt and strictMode

- components/List/index.tsx
- components/Transfer/README.en-US.md
- components/Transfer/README.zh-CN.md
- components/Transfer/interface.tsx
- components/Transfer/list.tsx
|   Transfer     | `Transfer` 组件新增 `virtualListProps` 属性以支持开启列表虚拟滚动。  |  `Transfer` adds `virtualListProps` property to support virtual scrolling of the list.  |  Close #1595  |
> feat: Transfer add virtualListProps to turn on virtual-scrolling

- components/Trigger/__test__/case.test.tsx
- components/Trigger/index.tsx
- components/_util/dom.ts
|     Trigger      |  修复 `Trigger` 组件的 `containerScrollToClose` 属性在页面滚动容器为 document.documentElement 时不生效的 bug。              |      Fix the bug that the `containerScrollToClose` property of the `Trigger` component does not take effect when the page scrolling container is document.documentElement.         |       close #1599          |
> fix: containerScrollToClose not work

- components/Drawer/README.en-US.md
- components/Drawer/README.zh-CN.md
- components/Drawer/index.tsx
- components/Drawer/interface.ts
- components/Radio/interface.ts
|  Drawer         |  `Drawer` 组件支持 `zIndex` 属性             |    `Drawer` component supports `zIndex` property           |  close #1601               |
> feat: drawer supports zindex property

- components/Modal/__test__/confirm.test.tsx
- components/Modal/__test__/useModal.test.tsx
- components/Modal/confirm.tsx
- components/Modal/useModal/hookModal.tsx
|      Modal     |  修复 `Modal` 组件通过 `update` 方法更新弹窗内容时丢失创建弹出层时传入的 config 的 bug.             |     Fixed the bug that the config passed in when creating the popup layer was lost when the `Modal` component updated the popup content through the `update` method.          |        close #1605         |
|      Modal     |    修复 `Modal` 组件通过静态方法创建弹出层时设置 `title={null}` & `icon={null}` 时，`.arco-modal-title` 节点仍然被渲染的 bug。           |        Fixed a bug where the `.arco-modal-title` node was still rendered when `title={null}` & `icon={null}` were set when the `Modal` component created a popup layer through a static method.       |        close #1593        |
> fix: modal.update loose origin config

- components/Select/style/mixin.less
在火狐浏览器下Select组件在设置showSearch=true或者allowCreate=true的时候，需要点击两次才能弹出popup
#1232 
select-view.tsx中原先代码逻辑设置windth： 0去隐藏input，经过测试这种隐藏方式在火狐浏览器下确实存在问题，同时看了代码中的注释需要保证tab键可以聚焦到input上面，最终选择opacity: 0这种最小影响整体代码逻辑的隐藏input方式
通过已存在的用例进行测试
|      Select     |  修复 Firefox 浏览器下当 `showSearch = true` 时，Select 需要点击两次才能弹出下拉框的问题。   |    Fix the problem that when `showSearch = true` in Firefox browser, Select needs to be clicked twice to pop up the drop-down box.   |    Close #1232           |
> fix: Select needs two clicks to show the popup when showSearch is true or allowCreate is true

- package.json
> chore: fix stylelint report error

- components/Trigger/getPopupStyle.ts
> typo: fix getPopupStyle.ts typo

- components/Pagination/__test__/index.test.tsx
- components/Pagination/pagination.tsx
|   Pagination    |   修复 `Pagination` 组件在 `sizeOptions` 模式下 `defaultPageSize` 不生效的 bug  |   Fix the bug that `defaultPageSize` does not take effect in `sizeOptions` mode of `Pagination` component.  |     Closed: #1625      |
> fix(Pagination): defaultPageSize not working in sizeOptions

- components/Switch/style/index.less
| Switch  | 修复 `Switch` 组件切换动画抖动的问题。   |  Fix `Switch` component switching animation jitter issue.   |  Close: https://github.com/arco-design/arco-design/issues/1544   |
> style: Switch check animation fix

- components/Select/select.tsx
|   Select    |  `Select` 允许在 `allowCreate` 并且无选项数据时展示下拉框。  |  `Select` allows to show dropdown when `allowCreate` is enabled and no option data is present. |  Close #1633  |
> enhance: Select show dropdown-box when allowCreate and there is no user inputing

- components/Form/control.tsx
- components/Form/form-list.tsx
- components/Form/utils.tsx
|   Form        |   优化 `Form.List` 组件在通过 Form API 更新表单项数据时全部重渲染导致页面卡顿的情况。            |      Optimize the situation where the `Form.List` component is completely re-rendered when the form item data is updated through the Form API, causing the page to freeze.         |     Close #1443            |
> enhancement: Form.List enhance

- components/Message/README.en-US.md
- components/Message/README.zh-CN.md
- components/Message/__demo__/transition.md
- components/Message/__test__/__snapshots__/demo.test.ts.snap
- components/Message/index.tsx
- components/Message/interface.ts
|  Message  |  Message 新增 `transitionTimeout` 属性，完善自定义动画配置。    |  Message adds `transitionTimeout` attribute to improve custom animation configuration.   |   Closed: #1629    |
> feat: Message support transitionTimeout

- components/DatePicker/README.en-US.md
- components/DatePicker/README.zh-CN.md
- components/DatePicker/__demo__/month.md
- components/DatePicker/__demo__/prefix.md
- components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
- components/DatePicker/interface.tsx
- components/DatePicker/picker-range.tsx
- components/DatePicker/picker.tsx
- components/TimePicker/README.en-US.md
- components/TimePicker/README.zh-CN.md
- components/TimePicker/__demo__/prefix.md
- components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
- components/TimePicker/interface.tsx
- components/TimePicker/picker.tsx
- components/_class/picker/input-range.tsx
- components/_class/picker/input.tsx
- components/_class/picker/style/index.less
- components/_class/picker/style/token.less
|     DatePicker      |      `DatePicker` 支持通过 `prefix` 设置前缀。         |    `DatePicker` supports setting prefix by `prefix`.           |        Close #1632         |
|     TimePicker      |      `TimePicker` 支持通过 `prefix` 设置前缀。         |    `TimePicker` supports setting prefix by `prefix`.           |        Close #1632         |
> feat: datepicker supports prefix & timepicker supports prefix

- components/Collapse/collapse.tsx
|    Collapse       |     修复 `Collapse` 组件在 React 18 严格模式下，组件报错的 bug。          |   Fix the bug that the `Collapse` component reported an error in React 18 strict mode.            |   Close #1472              |
> fix: collapse can not work in react 18 strictmode

- components/Checkbox/README.en-US.md
- components/Checkbox/README.zh-CN.md
- components/Checkbox/__demo__/custom_icon.md
- components/Checkbox/__test__/__snapshots__/demo.test.ts.snap
- components/Checkbox/__test__/index.test.tsx
- components/Checkbox/checkbox.tsx
- components/Checkbox/interface.ts
|  Checkbox   |  `Checkbox` 组件新增 `icon` 属性以自定义选中态图标。        | The `Checkbox` component adds an `icon` prop to customize the checked icon.    |                |
> feat(Checkbox): Checkbox增加自定义Icon功能

- components/Upload/list/index.tsx
|           |               |               |           Close #1661     |
> enhancement: remove Upload defaultProps

- components/Alert/style/index.less
- components/Button/style/index.less
- components/Switch/style/index.less
- components/Table/style/index.less
`@import '../../style/theme/default.less'` 在 `token.less` 中已经导入。
把 `@import '../../style/theme/default.less'` 从对应的 `index.less`中移除，避免重复导入。
|    Switch Table Button Alert       |     移除多余的 less          |     remove excess less          |                |
> style: less is imported twice

- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/__demo__/layout.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/form-item.tsx
- components/Form/form-label.tsx
- components/Form/interface.tsx
- components/Form/style/index.less
- components/Form/style/token.less
|     Form      |    `Form.Item` 支持通过 `tooltip` 属性设置提示信息。           |    `Form.Item` supports setting tooltip via `tooltip` property.           |           Close #1554      |
> feat: Form.Item supports tooltip props

- components/Upload/util.tsx
|     Upload      |    修复 `Upload` 组件在设置 `accept=audio/mp3` 时，mp3 文件无法被正常上传的 bug。           |       Fix the bug that mp3 files cannot be uploaded normally when the `Upload` component is set to `accept=audio/mp3`.        |       Close #1646          |
> fix: upload filter logic

- components/Trigger/index.tsx
|   Trigger        |    优化 `Trigger` 组件的触发节点样式变为 `display: none` 时弹出层位置出现闪动的问题。           |     Optimize the problem that the position of the popup layer flickers when the trigger node style of the `Trigger` component changes to `display: none`.          |    Close #436            |
|   Trigger        |    优化 `Trigger` 组件的弹出层尺寸改变定位未及时更新导致的闪动问题。           |     Optimize the flickering problem caused by the size change of the popup layer of the `Trigger` component and the location is not updated in time.         |    Close #1449          |
> enhance: trigger should keep position

- README.md
> docs: Keep consistent with Chinese documents

- components/Checkbox/__test__/group.test.tsx
- components/Checkbox/group.tsx
- components/Checkbox/interface.ts
| Checkbox          |  CheckboxGroup增加自定义Icon功能             |               |                |
> feat: checkboxgroup update

- .github/workflows/deploy-site-preview.yml
- components/Carousel/arrow.tsx
- components/DatePicker/index.tsx
- components/DatePicker/panels/date/index.tsx
- components/DatePicker/panels/month/index.tsx
- components/DatePicker/panels/quarter/index.tsx
- components/DatePicker/panels/range/index.tsx
- components/DatePicker/panels/week/index.tsx
- components/DatePicker/panels/year/index.tsx
- components/DatePicker/picker.tsx
- components/Dropdown/index.tsx
- components/Input/password.tsx
- components/Layout/index.tsx
- components/Layout/sider.tsx
- components/Menu/index.tsx
- components/Progress/line-progess.tsx
- components/Progress/steps-progress.tsx
- components/Select/opt-group.tsx
- components/Select/option.tsx
- components/Select/utils.tsx
- components/Statistic/countdown.tsx
- components/Table/summary/cell.tsx
- components/Table/summary/row.tsx
- components/_class/Draggable/index.tsx
- components/_class/Draggable/item.tsx
- components/index.tsx
|   Common        |    移除内部函数组件的 `defaultProps` 用法，避免在 React 18 严格模式下控制台 warning。          |    Remove `defaultProps` usage of inner function components to avoid console warning in React 18 strict mode.           |        close #1670         |
> enhancement: remove defaultProps from function component

- components/InputNumber/useSelectionRange.ts
#1671 
useLayoutEffect 替换为  #useIsomorphicLayoutEffect
|     InputNumber      |  修复 `InputNumber` 组件由于 `useLayoutEffect` 导致的 SSR 警告。  |    Fix SSR warning for `InputNumber` component due to `useLayoutEffect`.  |      Close #1671    |
> fix: 修复InputNumber useLayoutEffect 造成的SSR警告

- components/_util/hooks/useMergeValue.ts
|    Common       |   修复部分组件在 React 18 严格模式下，defaultValue 不生效的 bug。           |     Fix the bug that defaultValue does not take effect in React 18 strict mode for some components.          |     Close #1686            |
> fix(Input): defaultValue not work in react18 strictmode

- components/_class/VirtualList/index.tsx
- components/_class/VirtualList/utils/itemUtil.ts
|  Common   |   优化虚拟列表在列表项设置了 `margin` 值时滚动定位偏移的问题。  |     Optimize the virtual list scroll position offset problem when the list item has a `margin` value set.  |                |
> enhancement: VirtualList performance when list items have css style margin

- components/Anchor/anchor.tsx
Anchor element will not be judged in-view when the element cover the startTop and targetOffset;
update anchor element in-view judgment logic.
|    Anchor       |    优化 `Anchor` 组件在锚点元素高度较大时，滚动目标容器可能出现激活 `Anchor.Link` 计算不准确的 bug。           |     Optimize the `Anchor` component. When the height of the anchor element is large, the scroll target container may have a bug that activates `Anchor.Link` calculation inaccurately.          |                |
> fix: update anchor element in-view judgment logic

- README.md
Currently the original url links to a broken link:
This PR links it to the correct one instead:
Url changed
No test, is a documentation fix
> docs: fix broken url link

- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Input/input-element.tsx
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/input-tag.tsx
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Select/__test__/index.test.tsx
- components/Select/utils.tsx
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/_class/select-view.tsx
- components/_util/fillNBSP.ts
|  Select  |  优化 `Select` 组件选项值的空字符串展示。   |   Optimize the empty string display of `Select` component option value.   |   Close #1695   |
> enhance: Select replace empty string in option label with &nbsp

- components/Image/image-preview-group.tsx
|   Image        |   修复在 `ImagePreviewGroup` 内嵌套  `Popover` 组件导致报错的 bug。             |      修复在 `ImagePreviewGroup` 内嵌套  `Popover` 组件导致报错的 bug。         |                |
> fix: Popover error in  ImagePreviewGroup

- .config/webpack.config.js
- components/Tabs/__demo__/drag.md
- site/package.json
Demo: Tabs - Draggable rely on react-dnd, the version of react-dnd is bad to use. And the demo is a little hard to adapt to TS.
[related issue #898](https://github.com/arco-design/arco-design/issues/898)
View the site.
There might be a compile fault about react-dnd while compiling, 
I change the import path to fix this error locally, I have no idea how to fix this problem without changing the webpack config. I think it might be fixed by your guys.
[refer issue of react-dnd #3432](https://github.com/react-dnd/react-dnd/issues/3423)
> docs: Docs/draggable tabs update

- components/Table/style/index.less
| Table  | 修复 `Table` 组件总结行在 `fixed=top` 时有问题的 bug。  | Fix `Table` component summary row style error when `fixed=top`.   |   Close: https://github.com/arco-design/arco-design/issues/1713  |
> style: Table summary fixed top

- components/TimePicker/__demo__/basic.md
- components/TimePicker/picker.tsx
| TimePicker |  `TimePicker` 组件支持设置 `triggerElement=null` 只使用面板。   |  `TimePicker` support set `triggerElement=null` to use panel only.  |  Close: https://github.com/arco-design/arco-design/issues/1701    |
> feat: TimePicker triggerElement = null will change to panel only mode

- components/_class/notice.tsx
|   Notification   | 修复 `Notification` 组件偶现更新延迟后定时器错乱的 bug |   Fix the bug that the `Notification` component occasionally updates the timer after the delay.  |   Closed: #1710   |
> fix(notice): May be uncleared timers affected by mouse events

- components/Image/interface.ts
- components/Popconfirm/__demo__/basic.md
- components/Popconfirm/index.tsx
- components/Popconfirm/interface.ts
- components/Popconfirm/style/index.less
- components/Popconfirm/style/token.less
- components/Trigger/interface.ts
- components/Typography/interface.tsx
|     Popconfirm      |  `Popconfirm` 支持 `content` 属性              |     `Popconfirm` supports `content` property          |       close #1694          |
> feat: Popconfirm supports content property

- components/Form/__demo__/async-validate.md
- components/Form/__demo__/form-context.md
- components/Form/__demo__/form-provider.md
- components/Form/__demo__/useFormState.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/control.tsx
- components/Form/form.tsx
- components/Form/hooks/useContext.ts
- components/Form/hooks/useState.ts
- components/Form/index.tsx
- components/Form/interface.tsx
- components/Form/store.tsx
- components/Form/useForm.ts
- components/_util/is.ts
- site/public/index.ejs
|      Form     | `Form` 支持通过 `useFormState` 获取指定字段的校验信息，校验状态              |       `Form` supports to get the verification information of the specified field through `useFormState`, verification status        |      close #1677           |
> feat: Form supports useFormState hook

- components/InputTag/README.en-US.md
- components/InputTag/README.zh-CN.md
- components/InputTag/__demo__/tokenSeparator.md
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/__test__/index.test.tsx
- components/InputTag/input-tag.tsx
- components/InputTag/interface.ts
|   InputTag  |  `InputTag` 组件新增 `tokenSeparators` 属性以支持自动分词。  |  `InputTag` adds the `tokenSeparators` property to support automatic word segmentation.  |   Close  #1711  |
> (WIP)feat: InputTag add property tokenSeparators

- .config/jest.config.js
- .config/webpack.config.js
- Add `alia` attribute at the `webpack.config.js` to solve `react/runtime` compilation error. https://github.com/react-dnd/react-dnd/issues/3423
- Add `transformIgnorePatterns` attribute at the `jest.config.js` to solve  the script [`test:node` compilation error](https://github.com/arco-design/arco-design/actions/runs/4082019030/jobs/7035930308)
> fix(site config): jest config, webpack config

- components/Checkbox/style/token.less
|   Checkbox  |  调整 `disabled` 且 `checked` 状态的 Checkbox 图标颜色。  |  Adjust the Checkbox icon color for `disabled` and `checked` states.  |  Close #1737  |
> style(Checkbox): icon color of disabled-checked Checkbox

- components/Menu/interface.tsx
- components/Menu/overflow-wrap.tsx
- components/Menu/style/token.less
- components/Menu/sub-menu/inline.tsx
- components/Menu/sub-menu/pop.tsx
|  Menu  |  `Menu.SubMenu` 允许传入 HTML 原生属性。  |  `Menu.SubMenu` allows passing in native HTML attributes.   |  Close #1732   |
| Menu | 优化水平菜单项内图标与文本之间的默认间距。| Optimized the default spacing between icon and text within horizontal menu items. | Close #1726  |
> enhance: Menu.SubMenu be allowed to pass in HTMLAttributes

- components/Cascader/cascader.tsx
- components/Cascader/interface.ts
- components/Cascader/panel/list.tsx
- components/Cascader/panel/search-panel.tsx
|    Cascader       |  修复 `Cascader` 组件的键盘事件监听在其他元素被 Focus 时仍会被触发的 bug。            |      Fix the bug that the keyboard event listener of the `Cascader` component will still be triggered when other elements are Focused.         |      Close #1430    Close #1725       |
> fix: Cascader keydown event

- components/Select/select.tsx
- components/Trigger/index.tsx
- components/Trigger/interface.ts
|  Select  | 优化 `Select` 组件搜索/创建选项后，失焦导致的下拉框抖动问题。  |   Optimize `Select` drop-down box jittering due to out-of-focus after searching/creating options.  |  Close #1743 |
> enhance: optimize Select UI jittering while searching/creating options

- components/Checkbox/README.en-US.md
- components/Checkbox/README.zh-CN.md
- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Popconfirm/README.en-US.md
- components/Popconfirm/README.zh-CN.md
- components/Trigger/README.en-US.md
- components/Trigger/README.zh-CN.md
- components/Trigger/__demo__/basic.md
- components/Trigger/__test__/index.test.tsx
- components/Trigger/index.tsx
- components/Trigger/interface.ts
- components/Typography/README.en-US.md
- components/Typography/README.zh-CN.md
|   Trigger        |      修复 `Trigger` 组件的 `props.style` 不生效的 bug。        |   Fix the bug that `props.style` of `Trigger` component does not take effect.           |  close #1745               |
|   Trigger        |      修复 `Trigger` 组件的 `clickToClose` 在 trigger="hover"  时不生效的 bug。        |   Fix the bug that `clickToClose` of `Trigger` component does not work when trigger="hover".            |  close #1738               |
> fix: clickToClose not work in hover & props.style invalid

- site/src/index-en.js
- site/src/index.js
> chore: userInfo migrate to common api

- components/Transfer/__test__/__snapshots__/demo.test.ts.snap
- components/Transfer/item.tsx
|   Transfer    |   移除 `Transfer` 允许拖拽时拖拽图标的交互样式。  |  Removed `Transfer` interaction style of icon-drag.  | Close #1753  |
> style(Transfer): icon-drag style of Transfer item

- components/Typography/base.tsx
- components/Typography/useEllipsis.tsx
- stories/Typography.story.tsx
|   Typography   | 修复 `Typography` 在 `cssEllipsis` 下无法进行自适应省略的 bug|   Fix the bug that `Typography` cannot be adaptively omitted under `cssEllipsis`     |  close #1740             |
> fix: In the simple ellipsis scene, resize cannot update the status

- .browserslistrc
- README.md
修改由于 BigInt 依赖引入带来的兼容性变更
1. Readme 修改
与 BigInt 兼容性对齐 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility
2. .browserlistrc 修改
与 BigInt 兼容性对齐 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility
> docs: update browser compatibility based on bigint support

- components/AutoComplete/index.tsx
| AutoComplete           |  可选链运算符             |  Optional chaining (?.)             |                |
> style(AutoComplete): optional chaining

- components/Upload/upload.tsx
[Upload]: duplicate uid警告的判断不正确，导致正常情况下也触发警告。
https://github.com/arco-design/arco-design/issues/1780
调整warning的位置
|    Upload        |    修复 `Upload` 组件校验重复 `uid` 警告逻辑异常           |    Fix `Upload` component verification duplicate `uid` warning logic exception         | Close #1780        |
> fix: 修复[Upload]: duplicate uid警告出现的时机

- site/package.json
- site/src/utils/navbarProps.js
- site/yarn.lock
> chore: upgrade navbar and footer

- components/Calendar/index.tsx
|  Calendar   |   修复 `Calendar` 组件 `panelTodayBtn` 按钮点击无效的问题。  |  Fix `Calendar` component `panelTodayBtn` click invalid issue.   |  Close #1778 |
> fix(Calendar): panel today button not work

- components/Select/__test__/index.test.tsx
- components/Select/utils.tsx
|  Select  |  优化 `Select` 允许创建选项时，如果搜索结果返回同样 `option.value` 的选项，此选项未更新的问题。  |   Optimize the issue that `Select` user-created option not updated if the search result returns an option with the same `option.value`  |  Close #1775 |
> enhance(Select): update option created by user-inputting if props.options contain the same value option

- components/DatePicker/picker-range.tsx
|  DatePicker | `DatePicker` 组件在选择日期时，面板不再排序切换。 | `DatePicker` component no longer sorts the panel when selecting a date.  |                |
> fix: not change show dates when click panel date

- components/Avatar/avatar.tsx
|  Avatar   |    优化 `Avatar` 子节点类型判断逻辑     | Optimize `Avatar` child node type judgment logic  |  Closed: #1812     |
> enhc(Avatar): Image child judgement

- components/Badge/style/token.less
- components/Table/style/index.less
- components/Table/style/token.less
|     Table      |         修复 `Table` 组件在暗黑模式下固定列背景色存在透明度导致的样式问题      |         Fix the style problem caused by the transparency of the fixed column background color of the `Table` component in dark mode      |     close #1756            |
| Badge | 调整 `Badge` 组件文本大小从 `12px` 到 `14px`，对齐设计规范 | Adjust the text size of the `Badge` component from `12px` to `14px`, aligning with the design specification | |
> style: fix table style & badge fontSize

- tests/screenshots.js
> test: mock browser api

- .codesandbox/ci.json
- .codesandbox/template/pr-preview/package.json
- .codesandbox/template/pr-preview/public/index.html
- .codesandbox/template/pr-preview/src/App.js
- .codesandbox/template/pr-preview/src/index.js
- .codesandbox/template/pr-preview/src/styles.css
- .codesandbox/template/readme.md
Pr preview
Reference: [codesandbox ci](https://codesandbox.io/docs/ci)
Should install [codesandbox](https://github.com/apps/codesandbox) first
> ci(*): add codesandbox ci for preview pr

- .github/workflows/preview-start.yml
> ci: add preview-start

- components/Image/image-preview.tsx
|     Image      |   优化 `Image` 预览图片时，可通过鼠标滚轮进行缩放。          |    Optimize `Image` to zoom in and out with the mouse wheel when previewing images.           |   close #1818              |
> enhancement: image preview supports mousewheel

- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/Select/interface.tsx
- components/Select/select.tsx
| Select  |  `Select` 组件 `ref` 引用新增 `scrollIntoView` 方法以支持滚动列表至指定选项。   | `Select` component `ref` add new `scrollIntoView` method to support scrolling the list to the specified option.  | Close #1820  |
> feat(Select): add scrollIntoView method for SelectHandle

- .github/workflows/preview-start.yml
- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/__demo__/list.md
- components/Form/__template__/index.zh-CN.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/control.tsx
- components/Form/form-list.tsx
- components/Form/interface.tsx
- components/Form/store.tsx
- components/Form/useForm.ts
- components/TreeSelect/README.en-US.md
- components/TreeSelect/README.zh-CN.md
- components/TreeSelect/interface.ts
- components/Trigger/README.en-US.md
- components/Trigger/README.zh-CN.md
- components/Trigger/interface.ts
|     Form      | `Form.List` 支持校验规则              |     `Form.List` supports validation rules          |    close #594             |
>  form.list 支持校验规则

- components/ConfigProvider/README.en-US.md
- components/ConfigProvider/README.zh-CN.md
- components/ConfigProvider/interface.ts
- components/Grid/README.en-US.md
- components/Grid/README.zh-CN.md
- components/Grid/__demo__/grid-responsive.md
- components/Grid/__demo__/grid.md
- components/Grid/__test__/__snapshots__/demo.test.ts.snap
- components/Grid/context.ts
- components/Grid/grid-item.tsx
- components/Grid/grid.tsx
- components/Grid/hooks/useResponsiveState.ts
- components/Grid/index.tsx
- components/Grid/interface.ts
- components/Grid/style/grid.less
- components/Grid/style/index.less
- components/Grid/utils.ts
|  Grid   |    `Grid` 支持 `css grid` 进行布局    |    `Grid` supports `css grid` for layout      | close #970   |
> feat: add gird layout

- .github/workflows/deploy-site-preview.yml
- components/Switch/style/token.less
|   Switch        |    修复`Switch` 组件部分样式变量未使用 css 变量前缀的 bug。           |      Fix the bug that some style variables of the `Switch` component do not use the css variable prefix.         |    close #1841            |
> style: modify switch token prefix

- components/Table/__demo__/group-columns.md
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Table/hooks/useColumns.tsx
- components/Table/hooks/useStickyClassNames.ts
- components/Table/interface.tsx
- components/Table/thead/index.tsx
- icon/index.js
- stories/Table.story.tsx
多表头场景下，表头为树数据结构，无法与stickyOffset 一一对应，在多列的情况下会导致获取不到真实的offset值。
为表头引入列索引，可以与stickyOffset对应，其中父表头占多列，其列索引为一个数组。
| Table | 修复Table 组件在多表头多列fixed场景下scroll 时出现表头和内容无法对齐的问题 | Fix the problem of misaligned table header and content when scrolling in the Table component under the scenario of multiple headers and fixed columns. | #1759  |
> fix: Table 组件在多表头多列fixed场景下scroll 时出现表头和内容无法对齐的问题

- components/TreeSelect/__test__/index.test.tsx
- components/TreeSelect/tree-select.tsx
|      TreeSelect     | 修复 `TreeSelect` 组件在设置 `treeCheckedStrategy=all` 时，点击关闭图标不生效的 bug。              | Fix the bug that clicking the close icon does not take effect when the `TreeSelect` component is set to `treeCheckedStrategy=all`.              |      close #1846           |
> fix(tree-select): close icon not work when treeCheckedStrategy=all

- .github/workflows/deploy-site-preview.yml
- components/TreeSelect/__demo__/renderFormat.md
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/__test__/index.test.tsx
- components/TreeSelect/interface.ts
- components/TreeSelect/tree-select.tsx
|   TreeSelect        |    `TreeSelect` 组件支持通过 `renderFormat` 自定义选中节点的回填展示           |   The `TreeSelect` component supports customizing the backfill display of selected nodes through `renderFormat`            |         close #1838       |
> feat: treeselect supports renderFormat

- components/Tabs/style/index.less
- components/Tabs/style/vertical.less
- stories/Tabs.story.tsx
|   Tabs     |   修复 `Tabs` 在 `card` 模式下，`TabsHeader` 边框样式错误的 bug  |   Fix `Tabs` in `card` mode, the bug that `TabsHeader` border style is wrong   |    Closed: #1854     |
> fix(style): Tabs card header-position border

- components/Anchor/anchor.tsx
> refactor: remove unused code

- components/Table/hooks/useColumns.tsx
- stories/Table.story.tsx
| Table  |  修复 `Table` 组件组合表头和 colSpan 一起使用时，colSpan 被覆盖的 bug。 |  Fix the bug that colSpan is overwritten when the group columns of the `Table` component is used together with colSpan.  | Close: https://github.com/arco-design/arco-design/issues/1864  |
> fix: Table fix using group columns and colSpan together

- components/Form/form-list.tsx
该 bug 在 2.46.0 引入
|   Form        | 修复 `Form.List` 组件在用户对 `add/remove/move` 方法 `memo` 时，执行表现异常的 bug             |      Fix the bug that the `Form.List` component behaves abnormally when the user executes the `add/remove/move` method `memo`         |                |
> fix(Form.List): remove not work 

- components/Form/context.ts
- components/Form/hooks/useContext.ts
- components/Form/store.tsx
| Form           |     优化 `Form.useFormContext`  未在 `<Form>` 内使用时出现页面报错导致白屏的问题。        |   Optimize the problem that when `Form.useFormContext` is not used in `<Form>`, there will be a page error and cause a white screen.            |      Close #1881           |
> enhance(Form): set default value of Form Context

- components/Table/__test__/fixed-columns.test.tsx
- components/Table/hooks/useStickyOffsets.ts
- components/Table/utils.tsx
|  Table  | `Table` 在固定列时，`column.width` 可以设置为带像素的字符串。  |  When `Table` is fixed columns, `column.width` can be set to a string with pixels.   |  Close: https://github.com/arco-design/arco-design/issues/1875 |
> enhance: Table fixed columns can use string px

- components/Input/textarea.tsx
|    Input       |     完善 `Input.Textarea` TS 定义          |      Improve the definition of 'Input.Textarea' TS         |     close #1888            |
> ts: modify input.textarea ref ts

- components/Drawer/index.tsx
- components/Modal/modal.tsx
|    Drawer       |    修复同时存在多层 `Drawer` 时，按键`ESC`所有抽屉被关闭的 bug。           |   Fix the bug that all drawers are closed by pressing `ESC` when there are multiple layers of `Drawer` at the same time.            | close #1887                |
> fix: only close top level drawer when esc

- components/DatePicker/__demo__/disabled-date-advance.md
- components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
> demo: add showTime in datePicker demo

- components/DatePicker/picker-range.tsx
| DatePicker | 修复 `DatePicker.RangePicker` 组件打开状态下切换 `mode` 时，日期会不断增加的 bug。  |  Fix the bug that when the `DatePicker.RangePicker` component is opened and the `mode` is switched, the date will keep increasing.    |  Close: https://github.com/arco-design/arco-design/issues/1916   |
> fix: RangePicker pickerValue update when mode change

- components/Statistic/README.en-US.md
- components/Statistic/README.zh-CN.md
- components/Statistic/index.tsx
- components/Statistic/interface.ts
| Statistic  |  `Statistic` 组件新增 `styleDecimal` 属性设置小数部分样式。   |  The `Statistic` component adds `styleDecimal` property to set the style of the decimal part. |    Closed: #1873       |
> style: statistic decimal style

- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Image/__demo__/lazyload.md
- components/Image/__test__/__snapshots__/demo.test.ts.snap
- components/Image/image.tsx
- components/Image/interface.ts
- components/Image/utils/hooks/useImageStatus.ts
- components/_util/hooks/useInView.ts
- components/_util/hooks/useIntersectionObserver.ts
- stories/Image.story.tsx
|  Image  |   `Image` 组件添加 `lazyload` 属性，支持懒加载  |    `Image` component adds `lazyload` attribute to support lazy loading    |      Closed: #1682     |
> feat(Image): support lazyload

- components/Grid/grid-item.tsx
- components/Grid/grid.tsx
- components/Grid/interface.ts
- components/Trigger/index.tsx
- stories/Grid.story.tsx
|    Grid       |   调整 `Grid.GridItem` ts 定义             |     Adjust the 'Grid.GridItem' ts definition          |                |
|    Grid       |   修复 `Grid.GridItem` 透传 `overflow` 属性到原生 DOM 标签导致控制台警告             |     Fixed `Grid.GridItem` transparently passing `overflow` attribute to native DOM tags and causing console warnings        |                |
|    Grid       |   `Grid.GridItem` 支持函数类型的 `children`            |     `Grid.Grid` supports `children` of function type       |                |
> ts: modify grid-item interfaces

- components/Table/style/index.less
- stories/Table.story.tsx
|      Table     |        修复树形数据展示且内容为非文本时的缩进问题       |        Fixed indentation issue when tree data presentation is non-text.       |        #1896         |
> fix: fix table indent

- components/DatePicker/picker-range.tsx
| DatePicker | 修复 `DatePicker.RangePicker` 在重新打开时，面板日期改变但是没有触发 `onPickerValueChange` 的 bug。   |   Fix `DatePicker.RangePicker` when reopening, panel date changes but does not trigger `onPickerValueChange` bug.            | Close: https://github.com/arco-design/arco-design/issues/1908  |
> fix: DatePicker.RangePicker onPickerValueChange when reset

- components/Tabs/README.en-US.md
- components/Tabs/README.zh-CN.md
- components/Tabs/__test__/__snapshots__/tabs-header.test.tsx.snap
- components/Tabs/__test__/tabs-header.test.tsx
- components/Tabs/hook/useDomSize.ts
- components/Tabs/interface.ts
- components/Tabs/tab-header/dropdown-icon.tsx
- components/Tabs/tab-header/index.tsx
- components/Tabs/tab-header/tab-nav-icon.tsx
- components/Tabs/tabs.tsx
|    Tabs    |   `Tabs` 组件的 `icons` 属性支持自定义选项卡头部的滚动操作图标。     |  The `icons` attribute of the `Tabs` component supports customizing the scrolling operation icons in the tab header  |   Closed: #1885        |
> feat(Tabs): icons support scroll config

- components/InputTag/README.en-US.md
- components/InputTag/README.zh-CN.md
- components/InputTag/__demo__/prefix.md
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/input-tag.tsx
- components/InputTag/interface.ts
- components/InputTag/style/index.less
- components/InputTag/style/token.less
- components/Select/style/mixin.less
- components/_class/select-view.tsx
|  InputTag   |  `InputTag` 组件新增 `prefix/addBefore/addAfter` 属性（同 `Input`）。  | The `InputTag` component has added `prefix/addBefore/addAfter` props (same as `Input`).  |   Close #1878   |
> feat: InputTag support prefix/addbefore/addafter

- components/Grid/context.ts
- components/Grid/grid-item.tsx
- components/Grid/grid.tsx
|    Grid       |   修复 `Grid.GridItem` 透传 `overflow` 属性到原生 DOM 标签导致控制台警告             |     Fixed `Grid.GridItem` transparently passing `overflow` attribute to native DOM tags and causing console warnings        |                |
> fix: grid overflow property

- .browserslistrc
- README.md
- icon/index.js
- yarn.lock
更新 browserslistrc，避免icon打包出现es6语法
> chore: update browserslistrc

- components/Table/table.tsx
| Table | 修复 `Table` 组件分页隐藏逻辑。  | Fix `Table` component pagination hiding logic.  |  Close: https://github.com/arco-design/arco-design/issues/1930   |
> fix: Pagination hiden when no data

- package.json
Set the value of the correct url
> fix: fix repo definition

- components/Grid/__demo__/grid-responsive.md
- components/Grid/hooks/useResponsiveState.ts
- components/Grid/interface.ts
|  Grid         |   修复 `Grid` 组件响应式布局 `xxxl` 属性不生效的 bug。            |   Fix the bug of `Grid` that `xxxl` property in responsive layout  does not work.            |                |
> fix: xxxl in grid not work

- components/_util/getHighlightText.tsx
|  Select  | 修复 `Select` 组件允许创建时输入文本内容过长导致的页面报错。   |  Fix the error caused by inputing long text when `Select` is allowed to be created.  |  Close #1945  |
> fix(Select): error caused by input large-size text to Select input box

- components/Table/hooks/useExpand.tsx
- stories/Table.story.tsx
|     Table      |        修复 `Table` 组件 `defaultExpandAllRows` 属性不生效的问题。       |       Fix the problem that the `defaultExpandAllRows` attribute of the `Table` component does not take effect.   |       Close: #1951          |
> fix(Table): Fixed defaultExpandAllRows property not taking effect

- README.md
- README.zh-CN.md
- site/docs/designlab/use-theme-package.en-US.md
- site/docs/designlab/use-theme-package.zh-CN.md
- site/docs/start.en-US.md
- site/docs/start.zh-CN.md
> docs: add introduction about unplugin

- components/DatePicker/__test__/date.test.tsx
- components/List/__test__/index.test.tsx
- components/ResizeBox/__test__/group.test.tsx
- components/_class/VirtualList/__test__/index.test.tsx
- components/_util/resizeObserver.tsx
- stories/Resizebox.story.tsx
- tests/mockRAF.ts
- tests/setup.js
|  Common         |   优化 `ResizeObserver` 监听逻辑，避免某些场景下出现 `ResizeObserver loop limit exceeded` 报错             |               Optimize `ResizeObserver` monitoring logic to avoid `ResizeObserver loop limit exceeded` error reporting in some scenarios|         close #1660  close #1856       |
> fix: add throttle logic to ResizeObserver

- components/_class/Draggable/style/index.less
|    InputTag       |  调整 `InputTag` 组件的拖拽样式类名 `arco-draggable` => `@{prefix}-draggable`              |    Adjust the drag style class name of `InputTag` component `arco-draggable` => `@{prefix}-draggable`           |   close #1956             |
> style: use prefix vars to replace arco

- components/Grid/README.en-US.md
- components/Grid/README.zh-CN.md
- components/Popconfirm/README.en-US.md
- components/Popconfirm/README.zh-CN.md
- components/Popconfirm/index.tsx
- components/Popconfirm/interface.ts
- components/Popover/README.en-US.md
- components/Popover/README.zh-CN.md
- components/Popover/index.tsx
- components/Popover/interface.ts
- components/Table/README.en-US.md
- components/Table/README.zh-CN.md
- components/TreeSelect/README.en-US.md
- components/TreeSelect/README.zh-CN.md
|    Popover       |   `Popover` 组件支持函数类型的 `title` , `content` 属性            |       `Popover` component supports `title`, `content` properties of function type        |                |
|    Popconfirm       |   `Popconfirm` 组件支持函数类型的 `title` , `content` 属性            |       `Popconfirm` component supports `title`, `content` properties of function type        |                |
> feat: popove & popconfirm support function content property

- components/DatePicker/__demo__/disabled-date.md
- components/DatePicker/panels/body.tsx
- components/DatePicker/panels/date/index.tsx
- components/DatePicker/panels/month/index.tsx
- components/DatePicker/panels/quarter/index.tsx
- components/DatePicker/panels/year/index.tsx
- components/DatePicker/util.ts
|  DatePicker   | 修复 `DatePicker` 组件 `disabledDate` 在快捷选择面板内，禁用掉不应该禁用日期的问题。 |   Fix `DatePicker` component `disabledDate` in the shortcut selection panel, disabling the date should not be disabled. |   Close: https://github.com/arco-design/arco-design/issues/1901   |
> fix: DatePicker disabledDate in quick selection

- components/index.tsx
|   Grid        |  导出 `Grid` 组件的 `GridProps`, `GridItemProps` 类型定义。             |     Export the `GridProps`, `GridItemProps` typedefs for the `Grid` component.          |                |
> feat: index file update gridprops

- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/_class/select-view.tsx
Select support `id` property. Close #939
> feat(Select): support HTML id property

- package.json
Modify repository url to support renovte recognition
> feat: update repo define

- components/Drawer/index.tsx
- components/Modal/__test__/popup.test.tsx
- components/Modal/modal.tsx
|     Drawer      |    修复 `Drawer` 第一次挂载时，内部弹出型组件 `zIndex` 计算错误的 bug.          |     Fix the bug that internal popup component `zIndex` is calculated incorrectly when `Drawer` is mounted for the first time.          |                |
|     Modal      |    修复 `Modal` 第一次挂载时，内部弹出型组件 `Modal` 计算错误的 bug.          |      Fix the bug that internal popup component `zIndex` is calculated incorrectly when `Modal` is mounted for the first time.          |                |
> fix: popupZIndex invalid in drawer

- components/Input/__test__/index.test.tsx
- components/Input/search.tsx
|     Input      |  修复 `Input.Search` 组件点击搜索图标或搜索按钮时错误触发 `onPressEnter` 回调的 bug。             |      Fix the bug that the `onPressEnter` callback is incorrectly triggered when the `Input.Search` component clicks the search icon or search button.         |       close #1978         |
> fix: pressenter should not be excuted when click search button

- components/Pagination/__test__/index.test.tsx
- components/Pagination/pagination.tsx
|   Pagination   |  修复 `Pagination` 组件在 `props` 更新为空的时候，报错的 bug   |  Fix the bug that `Pagination` reports an error when the `props` update is empty    |       Closed: #1984        |
> fix(Pagination):  pagesize illegal scene

- components/Menu/style/index.less
|  Menu   |  优化 `Menu` 折叠之后，菜单项图标未水平居中的问题。  |  优化 `Menu` 折叠之后，菜单项图标未水平居中的问题。 |  Close #1444   |
> style(Menu): ensure that icon of menu item is horizontal-center after Menu collapsed

- components/BackTop/__test__/__snapshots__/demo.test.ts.snap
- components/Calendar/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/__test__/index.test.tsx
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
- components/Input/__test__/__snapshots__/demo.test.ts.snap
- components/Pagination/__test__/__snapshots__/demo.test.ts.snap
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Select/__test__/index.test.tsx
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/__test__/index.test.tsx
- components/_class/select-view.tsx
当 `SelectView` 的 `<input />` 节点处于隐藏状态时，移除其 `value` 属性。
> enhance: remove value of <input/> in SelectView if it is hidden

- components/DatePicker/picker.tsx
| DatePicker | 修复 `DatePicker` 组件在设置时区之后，输入时间没有正确转换的问题。  | Fix `DatePicker` component, after setting the timezone, the input time is not converted correctly.  |  Close: https://github.com/arco-design/arco-design/issues/1986  |
> fix: DatePicker input error when set timezone or utcOffset

- components/Table/interface.tsx
- components/Table/table.tsx
- stories/Table.story.tsx
|      Table     |       修复Table默认排序信息丢失问题        |       Fixed the default Table sorting information loss        |       #1985          |
> fix: Default sorting information loss

- site/package.json
- site/yarn.lock
> chore: support juejin playground

- site/package.json
- site/yarn.lock
> chore: upgrade site footer

- components/Slider/index.tsx
#1999 
|     Slider      |  消除 `Slider` 组件因数值转换越界导致的控制台警告。   |   Eliminate console warnings from the `Slider` due to  beyond boundary when transfer to integer. |    Close #1999            |
> fix: Slider number-precision disable boundary checking

- components/Drawer/README.en-US.md
- components/Drawer/README.zh-CN.md
- components/Drawer/__test__/index.test.tsx
- components/Drawer/index.tsx
- components/Drawer/interface.ts
- components/Table/README.en-US.md
- components/Table/README.zh-CN.md
|  Drawer         |   `Drawer` 组件支持通过 `closeIcon` 属性自定义关闭按钮。            |      The `Drawer` component supports customizing the close button via the `closeIcon` property.         |                |
> feat: drawer supports closeIcon

- components/Form/interface.tsx
- components/Pagination/__test__/__snapshots__/demo.test.ts.snap
- components/Pagination/page-jumper.tsx
- components/Pagination/style/index.less
- components/Pagination/style/token.less
|    Pagination       |  `Pagination` 组件调整默认文案：前往 => 前往 x 页             |    The `Pagination` component adjusts the default text: Goto => Goto x pages           |                |
|    Pagination       |  `Pagination` 组件调整快速跳转字体颜色为 `color-text-2`             |        The `Pagination` component adjusts the quick jump font color to `color-text-2`       |                |
> style:  pagination add suffix & update text color

- components/Notification/__demo__/useNotification.md
- components/Notification/__test__/useNotification.test.tsx
- components/Notification/index.tsx
- components/Notification/useNotification.tsx
|   Notification        |    `Notification.useNotification` 支持通过 `getContainer` 设置元素挂载节点。             |    `Notification.useNotification` supports setting elements to mount nodes via `getContainer`.           |    close #1997             |
> feat: useNotification supports getContainer

- components/TimePicker/time-column.tsx
| TimePicker         |  修复 `TimePicker` 组件在 `scrollSticky={false}` 时控制台出现 warning 的 bug。              |    Fix the bug that the warning appears in the console when the `TimePicker` component is set to `scrollSticky={false}`.           |                |
> fix: timepicker warning in dev

- components/Cascader/__test__/case.test.tsx
- components/Cascader/__test__/index.test.tsx
- components/Cascader/panel/list.tsx
|     Cascader      |    修复 `Cascader` 组件无法通过键盘事件删除已选项的 bug。           |      Fix the bug that the `Cascader` component cannot delete selected items through keyboard events.         |      close #2019           |
> fix: cascader can not be delete by backspace

- components/Message/index.tsx
- components/Notification/index.tsx
|       Message    |   修复 `Message` 组件在特殊场景下 `getContainer` 变化导致组件报错的bug。            |      Fix the bug that the `Message` component will report an error when `getContainer` changes in a special scenario.         |                |
|       Notification    |   修复 `Notification` 组件在特殊场景下 `getContainer` 变化导致组件报错的bug。            |      Fix the bug that the `Notification` component will report an error when `getContainer` changes in a special scenario.         |                |
> fix: notice render error

- components/Modal/interface.ts
|  modal         |   修复ts类型错误，应该为version，但展示defaultValue。            |               |                |
> fix: modal defaultValue -> version

- components/Transfer/__test__/index.test.tsx
- components/Transfer/index.tsx
|   Transfer   |  优化 `Transfer` 组件 `onChange` 回调参数，保证回调返回的 `targetKeys` 数组顺序与目标列表实际渲染顺序一致。  |    Optimize the `onChange` callback parameters of the `Transfer` to ensure that the array order of `targetKeys` is consistent with the actual rendering order of the target list.       |   Close #2034  |
> enhance(Transfer): onChange callback value is inconsistent with the order of target list items

- components/DatePicker/picker-range.tsx
- components/DatePicker/picker.tsx
| DatePicker | 修复 `DatePicker` 组件 `showTime.defaultValue` 在设置时区之后显示不准确的 bug。 |  Fix `showTime.defaultValue` of `DatePicker` component shows inaccurate bug after setting timezone.   |    Close: https://github.com/arco-design/arco-design/issues/2033     |
> fix: DatePicker showTime.defaultValue not correct when set timezone

- components/Input/README.en-US.md
- components/Input/README.zh-CN.md
- components/Input/__test__/index.test.tsx
- components/Input/input-element.tsx
- components/Input/interface.tsx
- components/Input/textarea.tsx
支持配置清除按钮
|     Input     |   `Input` 支持配置清除按钮            | `Input` supports clearIcon property |                |
> feat(Input): input supports clearIcon

- components/Message/README.en-US.md
- components/Message/README.zh-CN.md
- components/Message/__test__/index.test.tsx
- components/Message/interface.ts
- components/_class/notice.tsx
支持配置关闭按钮
|   Message        |   `Message` 支持配置关闭按钮     |    `Message` supports closeIcon           |                |
> feat(Message): supports closeIcon

- components/Notification/README.en-US.md
- components/Notification/README.zh-CN.md
- components/Notification/__test__/index.test.tsx
- components/Notification/interface.ts
- components/_class/notice.tsx
支持配置关闭按钮
|   Notification        |     `Notification` 支持配置关闭按钮          |    `Notification`  supports closeIcon          |                |
> feat(Notification): supports closeIcon

- components/_class/select-view.tsx
|   Select   |  修复 `Select` 组件被 `ConfigProvider.componentConfig.InputTag` 设置的默认属性影响的问题。    |   Fix `Select` component being affected by default properties set by `ConfigProvider.componentConfig.InputTag`.   |     Close #2047      |
> fix(Select): select-view is affected by InputTag properties inherit from ConfigProvider.componentConfig.InputTag

- components/Carousel/indicator.tsx
|  Carousel |  修复 `Carousel` 组件 `trigger` 设置为 `hover` 时页面切换异常的问题。  | Fix the problem that the page switch is abnormal when the `trigger` of the `Carousel` is set to `hover`. |    Close #2048   |
> fix(Carousel): slide not working properly if trigger is [hover]

- components/Descriptions/interface.ts
|   Descriptions     |   修复 `Descriptions` 组件 `column` 属性响应式布局缺少 `xxxl` 字段声明的问题。   |   Fix `Descriptions` component `column` attribute responsive layout missing `xxxl` ​​field declaration.  |    Close #2049  |
> type(Descriptions): DescriptionsProps.column missing [xxxl] option

- components/_class/VirtualList/index.tsx
|  Table   |  修复 `Table` 开启虚拟滚动且数据量较小时可能出现的表头对齐问题。  |  Fix the header alignment problem that may occur when virtual scrolling is enabled for `Table` and the amount of data is small.   |     Close #2040   |
> fix: VirtualList outerStyle not worked when list is not virtual

- components/Upload/__demo__/drag.md
|   `Upload`   |     修复`Upload`组件沙盒预览错误    |      fix the error about sandbox of `Upload`        |            #1527    |
> fix: error reported when open sandbox of upload component case

- components/Input/README.en-US.md
- components/Input/README.zh-CN.md
- components/Input/__demo__/basic.md
- components/Input/__demo__/normalize.md
- components/Input/__test__/__snapshots__/demo.test.ts.snap
- components/Input/__test__/index.test.tsx
- components/Input/input-element.tsx
- components/Input/interface.tsx
- components/Input/useComposition.ts
- components/Modal/README.en-US.md
- components/Modal/README.zh-CN.md
|   Input        |    `Input` 支持通过 `valueNormalize` 在指定时机对输入值进行格式化。             |    `Input` supports `valueNormalize` to format the input value at the specified time.           |                |
> feat: Input supports valueNormalize

- components/_util/dom.ts
Remove any type of `on` `off` utils.
Set a clear type.
> ts: enhance any type

- components/Cascader/style/index.less
|   Cascader        |       修复 `Cascader` 组件多选时选中节点会触发 onBlur 的 bug。        |      Fix the bug that the onBlur will be triggered when the node is selected when the `Cascader` component is multi-selected.         |       close #2051         |
> fix: Cascader onBlur

- components/Input/style/index.less
|  Input     |  修复 `Input` 组件设置 `allowClear` 且宽度不固定时 hover 前后出现的宽度抖动问题。  |  Fix the width jitter problem before and after hover when `Input` is set to `allowClear` and the width is not fixed.  |     Close #2042          |
> style(Input): Input width change after hovering due to clear icon

- components/Table/__test__/components.test.tsx
- components/Table/utils.tsx
> fix(Table): make __ORIGIN_DATA enumerable: false

- components/Tabs/tab-header/index.tsx
|       Tabs    |      修复 `Tabs` 组件在宽度动态改变时边界条件下出现组件不停抖动的问题。          |        Fix the problem that the `Tabs` component will vibrate continuously under boundary conditions when the width changes dynamically.       |               close #2070  |
> fix: tabs resize throttle

- components/Dropdown/README.en-US.md
- components/Dropdown/README.zh-CN.md
- components/Dropdown/button.tsx
- components/Dropdown/interface.ts
|  Dropdown   |  `Dropdown.Button` 允许传入所有的 `DropdownProps`。   |   `Dropdown.Button` support all `DropdownProps`.  |  Close #2086  |
> feat(Dropdown): add [popupVisible/defaultPopupVisible/getPopupContainer] properties for Dropdown.Button

- components/Menu/README.en-US.md
- components/Menu/README.zh-CN.md
- components/Menu/__demo__/collapse-control.md
- components/Menu/__test__/__snapshots__/demo.test.ts.snap
- components/Menu/interface.tsx
- components/Menu/item.tsx
|   Menu  | `Menu.Item` 组件新增 `renderItemInTooltip` 属性，用以指定 `Menu` 收起时 `Tooltip` 中展示的菜单项节点。     |   The `Menu.Item` adds `renderItemInTooltip` property, which is used to specify the menu item node displayed in `Tooltip` when `Menu` is collapsed.            |   Close #2088  |
> feat(Menu): add new property renderItemInTooltip

- components/Table/table.tsx
to get the actual width of the table
using `element.clientWidth` will give an incorrect width when the actual width of the table is not an integer. For example if the width of the table is a decimal number 1489.5999755859375 `element.clientWidth` will give a rounded one 1490. This will sometimes cause the browser to show **an unwanted scrollbar**.
use `element.getBoundingClientRect().width`
|    Table       |     优化表格宽度在特定场景下出现不必要滚动条的问题。          |    Optimize the width of the table and the problem of unnecessary scroll bars in certain scenarios.           |                |
> fix(Table): use element.getBoundingClientRect().width to get the table width

- components/Descriptions/README.en-US.md
- components/Descriptions/README.zh-CN.md
- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Mentions/README.en-US.md
- components/Mentions/README.zh-CN.md
- components/Typography/__demo__/operations.md
- components/Typography/__test__/__snapshots__/demo.test.ts.snap
- components/Typography/base.tsx
- components/Typography/edit-content.tsx
- components/Typography/interface.tsx
- components/Typography/style/index.less
|    Typography       |    修复 `Typography.Title` 切换为编辑状态时字体样式未继承 Title 样式的 bug。           |      Fix the bug that the font style does not inherit the Title style when `Typography.Title` is switched to the edit state.         |            close #2090   |
|    Typography       |    修复 `Typography` 切换为编辑状态时用户传入的 `className` 和 `style` 属性丢失的 bug。           |      Fix the bug that the `className` and `style` attributes passed in by the user are lost when `Typography` is switched to the editing state.     |               |
> style: update Typography editable style

- components/InputNumber/index.tsx
|   InputNumber   |   修复 `InputNumber` 初始 `value` 设置为 `undefined` 时可能导致的报错问题。   |  Fix the error that may be reported when the initial `value` of `InputNumber` is set to `undefined`.    |                |
> fix(InputNumber): avoid string replace error due to undefined

- components/Carousel/style/index.less
修复carousel双击箭头导致底部文字被选中问题。
https://codepen.io/Wenping-Liao/pen/RwqvyVe?editors=0011
- [x ] Bug fix
> fix carousel-arrow dbclick text select

- components/Select/select.tsx
- components/Transfer/style/index.less
|     Transfer      |   修复 `Transfer` 在列表项移动时，可能出现的高度抖动。  |  Fix possible height jitter in `Transfer` when moving list items.  |                |
> fix: Transfer item height jittering

- components/_util/hooks/useUpdate.ts
> chore: add type limit

- components/Trigger/getPopupStyle.ts
|     Trigger      |     优化 `Trigger` 组件在内容高度存在小数时会出现定位误差导致出现不必要滚动条的问题。         |       Optimize the `Trigger` component when there is a decimal in the content height, there will be a positioning error, which will cause unnecessary scroll bars.        |   close #2132             |
> enhancement: get Content Size by offsetWidth

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Cascader/__test__/index.test.tsx
- components/Cascader/cascader.tsx
- components/Cascader/interface.ts
- components/Cascader/panel/list.tsx
- components/Cascader/panel/option.tsx
- components/Cascader/panel/search-panel.tsx
支持选项图标
|    Cascader      |     `Cascader` 组件支持 `icons` 参数设置图标。          |     The `Cascader` component supports the `icons` parameter to set icons.     |                |
> feat(Cascader): support icons

- components/Image/image.tsx
|  Image  |   修复 `Image` 配合 `previewProps.actions` 使用报错的问题。  |  Fix `Image` error caused by `previewProps.actions` usage.  |  Close #2128   |
> fix(Image): error caused by JSON.stringfy a object with ReactNode as property value

- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/Select/__test__/index.test.tsx
- components/Select/interface.tsx
- components/Select/select.tsx
|   Select   |  `Select` 新增 `onSelect` 回调（仅对多选模式生效）。  |  `Select` adds `onSelect` callback (only valid for multi-select mode).  |  Close #2150    |
|   Select   |  `Select` 调整 `defaultActiveFirstOption` 对于选中的选项亦生效。   |  `Select` adjusts `defaultActiveFirstOption` to also take effect for the selected option. |  Close #2154    |
> Select add onSelect & enhance behavior of defaultActiveFirstOption

- components/Tabs/style/rtl.less
- components/Tabs/style/vertical.less
- stories/Tabs.story.tsx
|    Tabs       |   修复 `Tabs`  组件 rtl 视图下，竖直方向选项卡样式表现异常的 bug。           |      Fix the bug that the vertical tab style behaves abnormally in the rtl view of the `Tabs` component.         |                |
|    Tabs       |   修复 `Tabs` 竖直方向选项卡高度未和内容区域保持一致的 bug（此修复调整了 `tabPosition` 为 left / right 的选项卡的布局方式为 flex 布局） 。           |      Fix the bug that the vertical tab height of `Tabs` is not consistent with the content area (this fix adjusts the layout method of tabs whose `tabPosition` is left / right to flex layout).         |        close #2123        |
> style: tabs style in rtl & veritcal

- components/Tree/index.tsx
- components/Tree/interface.ts
- stories/Tree.story.tsx
> enhancement: __ArcoFakeNode__ => __ArcoAdapterMode__

- site/src/index-en.js
- site/src/index.js
> chore: add RENDER_BY_HOST flag to control the rendering of Index component

- components/Steps/__demo__/onchange.md
`Steps` 组件没有 `arrow` 属性，应该是 `type = "arrow"`
> docs(Step): change arrow prop to type

- components/TimePicker/__demo__/status.md
- components/TimePicker/__demo__/timezone.md
- components/TimePicker/__demo__/use-12-hours.md
- components/TimePicker/__demo__/utcOffset.md
- `TimePicker.RangePicker` 的 `placeholder` 属性应该是 `[string, string]`，不应该是 `string`
- `TimePicker` 上没有 `showTime` 属性，如果是显示此刻的时间，默认是 `true`
> docs(TimePicker): update placeholder and showTime

- components/Cascader/__demo__/visible.md
> docs(Cascader): duplicate style props

- components/Form/__demo__/validate-status.md
hasFeedback 属性不应该设置在 TimePicker 上，而应该是在 FormItem 上
> docs(Form):   hasFeedback should be FormItem props

- components/Image/image.tsx
|   Image  |   避免 `Image` 未传入 `src` 时浏览器控制台的 404 报错。   |   Avoid 404 error in the browser console when `src` is not passed to `Image`.   |   Close #2168  |
> enhance(Image): avoid 404 error when src is undefined

- components/Table/style/index.less
https://github.com/arco-design/arco-design/issues/1958
|     Table      |      修复 `Table` 组件设置 scrollX 时空白状态可能会出现滚动条样式的问题。         |        Fix the problem that the scrollbar style may appear in the blank state when the `Table` component is setting scrollX.      |      https://github.com/arco-design/arco-design/issues/1958          |
> style(table): fix the blank state style when setting scrollX

- components/Tree/context.tsx
> ts: context tree

- .github/workflows/deploy-site-preview.yml
> ci: update argos-cli

- components/Cascader/cascader.tsx
- components/Menu/style/index.less
|   Cascader    |  修复 `Cascader` 组件 `rtl` 模式下面板选项箭头位置异常的问题。   |  Fixed the issue of abnormal position of panel option arrow in `Cascader` component `rtl` mode.  |   Close #2199   |
|   Menu    |  修复 `Menu` 组件 `rtl` 模式下折叠按钮的位置问题。   |  Fix the location of the collapse button in the `rtl` mode of the `Menu` component  |     |
> style(Cascader): panel item arrow style in rtl direction

- site/src/widget/Anchor/index.less
- site/src/widget/ThemeBox/index.less
> feat: adjust the position of the floating navigation

- components/Transfer/style/index.less
|  Transfer   |   修复 `Transfer` 列表项溢出的问题。  |  Fix the issue  about `Transfer` list items overflow.  |                |
> style(Transfer): list item overflow

- components/Form/__test__/case.test.tsx
- components/Form/control.tsx
- components/Form/form-item.tsx
- tests/screenshots.js
|    Form       |   修复  `Form.Item` 组件的 `disabled` 属性覆盖了子节点的 `disabled` 属性的 bug。           |     Fix the bug that `Form.Item` component's `disabled` property overrides the child node's `disabled` property.          |     close #2172           |
> fix: form item disbaled

- components/_class/VirtualList/index.tsx
|Common| 修复内部组件 `VirtualList `  边界场景下控制台报错问题  |Fixed the problem of console error reporting in boundary scenarios of internal component `VirtualList` | |
> fix(VirtualList): error caused by get clientHeight from null

- components/Input/README.en-US.md
- components/Input/README.zh-CN.md
- components/Table/README.en-US.md
- components/Table/README.zh-CN.md
- components/Table/__test__/pagination.test.tsx
- components/Table/interface.tsx
- components/Table/table.tsx
|  Table | `Table` 组件 `onChange` 回调增加参数 `extra.currentAllData`。  |  `Table` component `onChange` callback adds parameter `extra.currentAllData`. |  Close: https://github.com/arco-design/arco-design/issues/2213      |
> feat: Table add onChange.extra.currentAllData

- components/Drawer/__test__/index.test.tsx
- components/Drawer/index.tsx
|    Drawer       |   修复 `Drawer` 组件在点击文本内容后，escToExit 不生效的 bug。            |    Fix the bug that escToExit does not take effect after clicking on the text content of the `Drawer` component.           |      close #2121           |
> fix: drawer esc not work

- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Image/image-preview.tsx
- components/Image/interface.ts
|   Image   |   `Image.Preview` 组件新增 `extra` 属性，用于指定在预览区域的额外节点。    |   `Image.Preview` add a new `extra` property, which is used to specify extra nodes in the preview area.  |  Close #2050  |
> feat(Image): support specify extra node in ImagePreview container

- components/Image/__test__/__snapshots__/demo.test.ts.snap
- components/Image/image.tsx
- components/_util/hooks/useInView.ts
|   Image    |   修复 `Image` 首次渲染会展示图片加载错误图标的 bug。  |  Fixed the bug that the first rendering of `Image` would display the load-failed icon.  |  Close #2215   |
> fix(Image): image shows error placeholder during first render

- components/Table/__demo__/virtualized.md
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Table/interface.tsx
- components/Table/table.tsx
- components/Table/tbody/index.tsx
- components/index.tsx
- stories/Table.story.tsx
|  Table   | `Table` 组件支持在虚拟列表的场景下通过 `ref.scrollIntoView` 滚动到指定区域。   |   The `Table` component supports scrolling to the specified area through `ref.scrollIntoView` in the virtual list scenario. |  Close: https://github.com/arco-design/arco-design/issues/2193 |
> feat: Table ref add scrollIntoView

- components/Message/index.tsx
- components/Message/interface.ts
- components/Message/useMessage.tsx
- components/Modal/interface.ts
- components/Modal/useModal/index.tsx
- components/Notification/index.tsx
- components/Notification/interface.ts
- components/Notification/useNotification.tsx
- components/index.tsx
|  Modal   |  导出 `ModalHookReturnType` 类型。  | Export `ModalHookReturnType` type.  | Close: https://github.com/arco-design/arco-design/issues/2230  |
|  Message   |  导出 `MessageHookReturnType` 类型。  | Export `MessageHookReturnType` type.  | Close: https://github.com/arco-design/arco-design/issues/2230  |
|  Notification   |  导出 `NotificationHookReturnType` 类型。  | Export `NotificationHookReturnType` type.  | Close: https://github.com/arco-design/arco-design/issues/2230  |
> enhance: Modal,Message,Notification export hook return type

- components/Tree/context.tsx
- components/Tree/index.tsx
- components/Tree/node-list.tsx
- components/_class/VirtualList/index.tsx
- stories/TreeSelect.story.tsx
|     TreeSelect      |   优化 `TreeSelect` 大数据下的性能表现            |      Optimize the performance of `TreeSelect` under big data         |       close #2225          |
> enhance: tree-select in  large data

- site/src/utils/navbarProps.js
> chore: docs remove hardcoded domain

- components/Drawer/__demo__/container.md
- components/Message/index.tsx
- components/Notification/index.tsx
|   Message   |   修复 `Message` 在 RTL 模式开启后无法关闭的问题。  |    Fixed the issue that `Message` could not disable RTL mode after it was enabled.   |  Close #2244    |
> fix(Message): Message.config cannot set rtl from true to false

- components/Modal/modal.tsx
|    Modal       |    修复 `Modal` 组件隐藏时重渲染组件可能触发子组件 ref 丢失的 bug。           |     Fixed a bug where re-rendering the component may trigger the loss of sub-component ref when the `Modal` component is hidden.          |        close #2241        |
> fix: modal ref error

- site/docs/start.en-US.md
- site/docs/start.zh-CN.md
When using cdn to introduce arco, I found that there was a lack of css links.
Add a link.
|          |               |               |                |
> docs: add css cdn link

- components/Divider/style/index.less
|    Divider       |    优化 `Divider` 组件的内联样式 borderStyle 能作用在分割线。           |     Optimize the inline style borderStyle of the `Divider` component to work on the dividing line.          |   close #2254              |
> enhance: divider line style inherit

- components/Tabs/interface.ts
- components/Tabs/style/index.less
- components/Tabs/style/vertical.less
- components/Tabs/tab-header/index.tsx
- components/Tabs/tab-header/tab-ink.tsx
|    Tabs       |   `Tabs` 支持定制下划线尺寸             |   `Tabs` supports custom underline size            |   close #2245              |
> feat: tabs support inkbarsize

- components/InputNumber/index.tsx
| InputNumber          |     修复 `InputNumber` 长按按钮时，因按钮事件抖动引起的增减异常。          |  Fixed the abnormal increase and decrease of `InputNumber` caused by the jitter of the button event when the button is long pressed.    |                |
复现Demo：
```ts
function Demo1() {
const [value, setValue] = useState(1e20);
const [num, setNum] = React.useState(0);
return (
<InputNumber
mode="button"
precision={0}
style={{ width: 100 }}
min={0}
max={1}
value={num}
onChange={(v) => {
setNum(v);
console.log('demo', v);
}}
/>
);
}
```
复现方式：快速点击加号，再点击减号
> 修复因按钮事件抖动引起的异常

- components/Pagination/page-jumper.tsx
|   Pagination    |    在 `simple` 模式下，跳转器的值不变的情况下不再触发更新事件     |    In `simple` mode, the update event is no longer triggered when the value of the jumper remains unchanged.    |                |
> enhance(pagination): enhance jumper blur

- components/DatePicker/picker-range.tsx
- components/DatePicker/picker.tsx
| DatePicker | 修复 `DatePicker.RangePicker` 设置 `shortcuts={[]}` 意外显示 0 的 bug。 |  Fixed `DatePicker.RangePicker` setting `shortcuts={[]}` unexpectedly displayed 0.   |  Close: https://github.com/arco-design/arco-design/issues/2300 |
> fix: DatePicker.RangePicker shortcuts={[]} unexpected display 0

- components/Table/colgroup.tsx
- components/Table/table.tsx
- stories/Table.story.tsx
|      Table     |       修复 `Table` 组件在 `scroll={x: 'max-content', y: true}` 时，表头和内容无法对齐的问题        |        Fixed an issue where the `Table` component would not align with the table header when `scroll={x: 'max-content', y: true}`      |        close #2280         |
> fix(Table): Fixed header alignment issue when scroll-x: max-content

- components/Button/style/index.less
|  Button   |   修复 `Button.Group` 在单个按钮下的圆角样式问题。   |   Fix `Button.Group` border-radius style under single button.  |                |
有场景需要使用ButtonGroup展示一组Button，Button个数动态变化。
当Button只有1个的时候，圆角会有问题。
```ts
export const ButtonGroup = () => {
const [rtl, setRtl] = React.useState(false);
return (
<Space direction="vertical">
<Button onClick={() => setRtl(!rtl)}>rtl</Button>
<ConfigProvider rtl={rtl}>
<Space direction="vertical">
<Button.Group>
<Button type="primary" shape="round">
Prev
</Button>
</Button.Group>
<Button.Group>
<Button type="primary">Prev</Button>
</Button.Group>
<Button.Group>
<Button type="primary" size="default">
Prev
</Button>
</Button.Group> …
```
> fix: button-group radius style.

- components/Cascader/cascader.tsx
- components/DatePicker/picker-range.tsx
- components/DatePicker/picker.tsx
- components/Dropdown/index.tsx
- components/Select/select.tsx
- components/Slider/button.tsx
- components/Table/thead/column.tsx
- components/TimePicker/picker.tsx
- components/Tooltip/index.tsx
- components/TreeSelect/tree-select.tsx
Too many temp objects would be created at every render, it's not necessary.Also, if they are been used as other component's prop value, it will cause useless renders.
Store them as const vars.
> perf: remove temp objects at every render, store as const vars.

- components/Form/__demo__/async-validate.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/control.tsx
- components/Form/form-item.tsx
- components/Form/hooks/useContext.ts
- components/Form/interface.tsx
- components/Form/store.tsx
- components/Form/style/status.less
|    Form       |   修复 `Form` 组件校验通过时表现了校验成功样式的 UI 问题（该 bug 在 `2.54.2` 引入）。            |    Fixed the UI problem of displaying the verification success style when the `Form` component is verified (this bug was introduced in `2.54.2`).       |                |
相关 PR：#2299
> fix: form ui

- components/Upload/README.en-US.md
- components/Upload/README.zh-CN.md
- components/Upload/__test__/index.test.tsx
- components/Upload/interface.tsx
- components/Upload/request.ts
- components/Upload/upload.tsx
- components/Upload/uploader.tsx
|    Upload       |    `Upload` 支持自定义上传 method           |     `Upload` supports custom upload method            |      close #2281           |
> feat: Upload support method prop

- components/Trigger/README.en-US.md
- components/Trigger/README.zh-CN.md
- components/Trigger/index.tsx
- components/Trigger/interface.ts
- site/docs_spec/style-guideline.en-US.md
- site/docs_spec/style-guideline.zh-CN.md
|     Trigger      |  `Trigger` 支持配置在捕获阶段触发 `clickOutside` 逻辑              |     `Trigger` 支持配置在捕获阶段触发 `clickOutside` 逻辑          |       close #2290          |
> feat: Trigger clickoutside supports capture

- components/_class/picker/input-range.tsx
|  DatePicker  | 修复 `DatePicker.RangePicker` 组件 Tab 键切换焦点错位的 bug。   |  Fixed the bug that the Tab key switching focus of the `DatePicker.RangePicker` component was misaligned.  | Close: https://github.com/arco-design/arco-design/issues/2288    |
> fix: DatePicker.RangePicker stop default behavior

- components/Image/image-preview.tsx
- stories/Image.story.tsx
|   Image  |   `Image.PreviewGroup` 组件增加方向键的快捷键支持    |    `Image.PreviewGroup` component adds shortcut key support for arrow keys    |   Close #2285     |
> enhance(image): add preview-group key event

- components/Table/utils.tsx
- stories/Table.story.tsx
|      Table     |       修复 `Table` 组件 `data` 属性为二维数组时，`render` 参数可能为空的问题。        |       Fixed an issue where the `render` parameter might be empty when the `Table` component's `data` attribute is a two-dimensional array.        |        close #2318         |
> fix(Table): __ORIGIN_DATA might be undefined

- components/DatePicker/panels/date/index.tsx
- components/DatePicker/panels/header.tsx
- components/DatePicker/panels/month/index.tsx
- components/locale/ar-EG.tsx
- components/locale/de-DE.tsx
- components/locale/en-US.tsx
- components/locale/es-ES.tsx
- components/locale/fr-FR.tsx
- components/locale/id-ID.tsx
- components/locale/interface.tsx
- components/locale/it-IT.tsx
- components/locale/ja-JP.tsx
- components/locale/ko-KR.tsx
- components/locale/ms-MY.tsx
- components/locale/pt-PT.tsx
- components/locale/ru-RU.tsx
- components/locale/th-TH.tsx
- components/locale/tr-TR.tsx
- components/locale/vi-VN.tsx
- components/locale/zh-CN.tsx
- components/locale/zh-HK.tsx
- components/locale/zh-TW.tsx
|     DatePicker      |    优化 `DatePicker` 面年月的显示顺序根据语言自动适配           |       Optimize the display order of year and month in `DatePicker` to automatically adapt according to the language        |               close #2305  |
中文默认不变，英文显示如下：
> enhancement: Datepicker panel order

- components/DatePicker/__test__/format.test.tsx
- components/DatePicker/interface.tsx
- components/DatePicker/panels/range/index.tsx
- components/DatePicker/picker-range.tsx
- components/DatePicker/util.ts
- components/_class/picker/input-range.tsx
- components/_util/dayjs.ts
| DatePicker  |  `DatePicker.RangePicker` 组件 format 参数支持数组。  |  The format parameter of the `DatePicker.RangePicker` component supports array.   | Close: https://github.com/arco-design/arco-design/issues/2304 |
> feat: DatePicker.RangePicker format can use string[]

- .github/workflows/deploy-site-preview.yml
- components/Input/__test__/index.test.tsx
- components/Input/input-element.tsx
- components/Input/useComposition.ts
- site/docs_spec/style-guideline.en-US.md
- site/docs_spec/style-guideline.zh-CN.md
|  Input         |   修复 `Input` 组件默认传入包含换行符的字符串且未做值的改动时， `onChange` 会在 blur 时触发一次的 bug。        |    Fixed a bug where `onChange` would be triggered once during blur when the `Input` component passed in a string containing a newline character by default without changing the value.           |      close #2332
> fix: Input should not trigger onChange when blur

- components/Table/table.tsx
|  Table         |    修复 `Table` 在动态更新 `scrollY`  时表头横向滚动失效的问题。           |   Fixed the problem of horizontal scrolling failure of table header when dynamically updating `scrollY` in `Table`.    |  [#2326](https://github.com/arco-design/arco-design/issues/2326)               |
> fix: table dynamic change scrolly.

- components/DatePicker/panels/header.tsx
> enhancement: panel header month order

- components/List/README.en-US.md
- components/List/README.zh-CN.md
> docs(List): fix props hoverable

- components/ResizeBox/__test__/index.test.tsx
- components/ResizeBox/index.tsx
|      ResizeBox     |     修复 `ResizeBox` 拖动后覆盖了 body 内联 cursor 样式的 bug。         |        Fixed the bug where `ResizeBox` covered the body inline cursor style after dragging.       |         Close #2341       |
> fix: resizebox cursor reset

- components/Table/colgroup.tsx
- components/Table/table.tsx
- components/Table/tbody/index.tsx
- components/_class/VirtualList/Filler.tsx
- components/_class/VirtualList/index.tsx
- stories/Table.story.tsx
|     Table      |       修复 `Table` 的 `columns` 中未指定 `dataIndex` 也未指定`key`时， `col key` 可能会重复的问题。        |    Fixed an issue where `col key` could be repeated when neither `dataIndex` nor `key` was specified in columns of `Table`.           |        #2349         |
|     Table      |        修复`Table`开启虚拟滚动后，横向滚动样式问题 。      |      Fixed horizontal scrolling style issue in `Table` after virtual scrolling is enabled.        |        #2342         |
|     Table      |        修复`Table` 的 `scroll.x={max-content}`，`scroll.y={true}`且数据为空时，表头样式错乱的问题 。      |      Fixed `Table` `scroll.x={max-content}`, `scroll.y={true}` and the data is empty, the table header style is …
> fix(Table): Fixed scrolling issues

- components/Upload/uploader.tsx
fileList 受控批量上传时，beforeUpload 为异步且在下一个 asyncUpload 之前 fileList 有更新，将导致 fileList 里的文件状态被覆盖为 init
复现 demo: https://codesandbox.io/s/arco-react-pr-template-forked-3nty67
原因是 syncUpload 里用到的 list 是初次使用时 this.props.fileList 拿到的闭包值。改为每次 asyncUpload 都取一下最新值
，这样即使外部更新，也能拿到最新值
|   Upload        |      修复 `Upload` 批量上传时已上传文件状态被覆盖成 init         |     Fixed the issue that the uploaded file status was overwritten to init during batch upload         |   Close  #2252           |
> fix(Upload): 修复批量上传时已上传文件状态被覆盖成 init

- site/package.json
- site/yarn.lock
在官网搜索框里输入 [ 会报错导致页面崩溃
Related: https://github.com/arco-design/arco-official-materials/pull/38
> docs: upgrade navbar version to fix search regexp issue

- components/Tree/style/index.less
- stories/Tree.story.tsx
|     Tree      |       修复`Tree`组件`size`不为`default`时，连接线样式不正确的问题。        |       Fixed an issue where the connection line style was incorrect when the `size` of the `Tree` component was not `default`.        |        #2333         |
> fix(Tree): fix style issues

- components/Form/__demo__/methods.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/validate.test.tsx
- components/Form/control.tsx
- components/Form/interface.tsx
- components/Form/store.tsx
|      Form     |  `Form` 组件支持设置 `validateOnly` 进行静默校验，不做 UI 表现             |     The `Form` component supports setting `validateOnly` for silent verification without UI performance.          |      close #2334           |
> feat: Form supports validateOnly

- components/Slider/hooks/useLegalValue.ts
|  Slider  |   修复 `Slider` 组件可能因读取 `undefined` 属性导致的报错问题。   |   Fixed the issue that `Slider` component may report an error due to reading property from `undefined`.   |    Close #2364    |
> fix(Slider): error caused by reading property from undefined

- .gitignore
- components/Table/hooks/useColumns.tsx
- components/Table/table.tsx
- components/Watermark/style/index.less
- stories/Table.story.tsx
| Table  | 优化 `Table` 组件 `data` 和 `columns` 空数据的定义方式，避免无限重绘。 | Optimize the definition of empty `data` and `columns` for the `Table` component to avoid infinite re-renders.  |  Close: https://github.com/arco-design/arco-design/issues/2368   |
> fix: Table enhance data and columns empty value

- components/Trigger/style/index.less
|     Trigger      |     修复不同弹出方向的 `Trigger` 组件在嵌套使用时，箭头样式被相互覆盖的 bug。          |    Fixed a bug where the arrow styles would overwrite each other when `Trigger` components with different pop-up directions are used in nests.           |       close #2360          |
> fix: trigger arrow style

- components/Message/__test__/index.test.tsx
- components/Message/index.tsx
- components/Notification/__test__/index.test.tsx
- components/Notification/index.tsx
- components/_class/notification.tsx
| Notification | 修复 `Notification` 组件在设置 `maxCount` 之后更新的逻辑。  |  Fix logic for `Notification` component to update after setting `maxCount`.   | Close: https://github.com/arco-design/arco-design/issues/2377  |
| Message |  修复 `Message` 组件在设置 `maxCount` 之后更新的逻辑。  |  Fix logic for `Message` component to update after setting `maxCount`.   | Close: https://github.com/arco-design/arco-design/issues/2377  |
> fix: Message and Notification update when set maxCount

- components/Layout/README.zh-CN.md
- components/Layout/interface.ts
- components/Table/hooks/useSorter.tsx
- stories/Table.story.tsx
|     Table      |       兼容`Table`组件在同一个生命周期内 `column` 中的 `sortOrder` 开始不受控，之后又受控的情况。        |    Compatible cases in which the `sortOrder` in `column` is initially uncontrolled and then controlled within the same life cycle of the `Table` component.            |               |
> fix(Table): fix sort order in control

- components/Form/utils.tsx
|      Form     |     优化 `Form` 中 value 为大数据数组时的性能       |        Optimize performance when field value is a large data array in a Form       | close #2394          |
> perf: optimize form getKeys func

- components/Tree/index.tsx
- components/Tree/node-list.tsx
- stories/Tree.story.tsx
|     Tree      |        修复 `Tree` 组件在虚拟滚动场景下，`onCheck` 回调参数`extra.checkedNodes` 未能返回所有选中节点信息的问题。       |       Fixed an issue where the `Tree` component `onCheck` callback parameter `extra.checkedNodes` failed to return information about all selected nodes in virtual scrolling scenarios.        |       #2374          |
> fix(Tree): checkedNodes error

- components/Form/store.tsx
|   Form  |  修复 `Form` 内部问题     |     Fix `Form` internal issues   |                |
> fix(form): fix undefined problem

- components/Drawer/index.tsx
|  Drawer   |  修复 `Drawer` 组件 `autoFocus` 失效的问题  |   Fix the problem of `Drawer` component `autoFocus` failure   |  Close #2404   |
> fix(drawer): fix autoFocus problem

- components/Form/form.tsx
- components/_util/hooks/useCreate.ts
> refactor(form): add useCreate hook, optimize component form code

- components/_class/notification.tsx
|     Message      |     修复 `Message[method]` 快速触发时，部分节点一直不会消失的 bug.          |   Fixed a bug where some nodes would never disappear when `Message[method]` was triggered quickly.            |                Close #2406 |
> fix: close Message

- components/Alert/index.tsx
- components/Anchor/utils.ts
- components/DatePicker/picker.tsx
- components/Drawer/index.tsx
- components/Form/hooks/useContext.ts
- components/Form/hooks/useState.ts
- components/Form/hooks/useWatch.ts
- components/Image/image-preview-arrow.tsx
- components/Image/image-preview.tsx
- components/Input/input-element.tsx
- components/Input/textarea.tsx
- components/InputTag/input-tag.tsx
- components/Modal/modal.tsx
- components/Portal/Portal.tsx
- components/Select/option.tsx
- components/Statistic/countdown.tsx
- components/Table/thead/column.tsx
- components/Tabs/tab-header/index.tsx
- components/TimePicker/picker.tsx
- components/Trigger/index.tsx
- components/_class/picker/input-range.tsx
- components/_class/picker/input.tsx
- site/src/pages/home/content/Pro/index.tsx
- site/src/pages/home/content/Token/index.tsx
- site/src/pages/home/sections/Banner/animationIcon.tsx
Use optional chaining instead of && is ore concise
| -  | 使用可选链代替短路语句 |  Use optional chaining instead of && | - |
> refactor: Use optional chaining instead of &&

- components/Upload/__test__/drop.test.tsx
- components/Upload/trigger-node.tsx
Upload 组件设置directory false，但手动拖拽文件夹到上传区域时，会将文件夹作为文件加入列表
|    Upload       |     修复 `Upload` 组件在 directory = false 场景下，手动拖拽文件夹到上传区域时会将文件夹作为文件加入列表的问题          |    Fixed the issue  that `Upload` would add the folder to the list as a file when `directory = false`     |   Close #2418             |
> fix: filter directories items if directory prop is not true

- components/Trigger/index.tsx
- components/_util/mergeProps.ts
|      Trigger     |     优化 `Trigger` 部分逻辑耗时问题          |    Optimize the time-consuming problem of `Trigger` part of the logic           |     close #2322           |
> enhance: trigger-mergeprops

- components/Watermark/interface.ts
According to the Arco site, `content` should be able to accept a string array to display multi-line content
https://arco.bytedance.net/react/en-US/components/watermark#multiple-line-content
Updated `content` type to accept both string and string[]
Before: 
After:
|  Watermark |    调整 Watermark 组件 `content` 属性 ts 定义          | Adjust the `content` attribute ts definition of the Watermark component|              |
> fix: watermark content accept string array

- components/Table/README.en-US.md
- components/Table/README.zh-CN.md
- components/Table/interface.tsx
- components/Typography/useEllipsis.tsx
|    Typography       |    优化 `Typography` 组件节点长度计算逻辑      |      Optimize `Typography` component node length calculation logic         |           close #2433      |
> fix: isSameNode should be excute as function

- components/_hooks/useWatermark/index.ts
|     Watermark      |     修复 `Watermark` 旋转后文字形变的 bug。          |       Fix the bug of text deformation after `Watermark` is rotated.        |      close #2436           |
> fix: fix watermark text size when rotate

- components/Select/__test__/index.test.tsx
- components/Select/select.tsx
|  Select   |  修复 `Select` 组件 `allowCreate.formatter` 属性在单选模式下 `creating` 参数始终为 `true` 的问题。  |  Fixed the issue where the `creating` parameter of the `allowCreate.formatter` property of the `Select` is always `true` in single-select mode.   |   Close #2445   |
> fix(Select): allowCreate.formatter not work for Select with single mode

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Image/image-preview-group.tsx
- components/Image/image-preview.tsx
- components/Image/interface.ts
- components/Menu/README.en-US.md
- components/Menu/README.zh-CN.md
- components/Table/README.en-US.md
- components/Typography/README.en-US.md
- components/Typography/README.zh-CN.md
- components/Watermark/README.en-US.md
- components/Watermark/README.zh-CN.md
|     Image      |  `Image.Preview` 组件增加 `imageRender` 属性允许自定义图片渲染，`imgAttributes` 属性自定义 src 内容              |  The `Image.Preview` component adds the `imageRender` attribute to allow custom image rendering, and the `imgAttributes` attribute customizes src content.   |    Close #2441            |
|     Image      |  `Image.PreviewGroup` 组件增加 `forceRender` 属性，用于提前加载图片      |    The `Image.PreviewGroup` component adds the `renderImages` attribute for loading images in advance    |   Close #2423             |
> Enhance image

- icon/build/getSvgData.js
> fix(scripts): fix icon init problem

- components/Message/__demo__/update_duration.md
- components/Message/index.tsx
- components/_class/notification.tsx
|   Message        |     修复相同id调用，during不更新问题          |   Fixed the problem of calling with the same ID and not updating during            |                |
> fix(Message): fixed the problem of calling with the same ID and not updating during

- components/Notification/index.tsx
|    Notification       |    修复相同id调用，during不更新问题           |     Fixed the problem of calling with the same ID and not updating during          |                |
> fix(Notification): 修复相同id调用，during不更新问题

- components/Breadcrumb/index.tsx
|  Breadcrumb          |  修复 `Breadcrumb.Item` 存在条件渲染时，出现多余分隔符的 bug。|Fixed the bug of extra delimiters appearing when conditional rendering exists in `Breadcrumb.Item`.  | close #2126|
> fix: breadcrumb  show extra separator

- components/InputNumber/index.tsx
|     InputNumber      |       修复`InputNumber`组件在 vscode 的 webview 下键盘操作不响应的问题。       |        Fixed bug `InputNumber` component does not respond to keyboard actions in vscode webview.       |                |
> fix: 修复vscode的webview下cv操作不了

- components/Space/__test__/index.test.tsx
- components/Space/index.tsx
- components/Space/toArray.ts
- package.json
- yarn.lock
|  Space |  修复 `Space` 组件包裹 Fragment 不能正确解析的问题。   | Fixed the issue where the `Space` component wrapping Fragment could not be parsed correctly.  |  Close: https://github.com/arco-design/arco-design/issues/2464 |
> fix: Space items wrap with fragment

- site/src/App.js
- site/src/pages/dark/md/header.zh-CN.md
> doc: update doc

- components/AutoComplete/README.en-US.md
- components/AutoComplete/README.zh-CN.md
- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/List/README.en-US.md
- components/List/README.zh-CN.md
- components/Menu/README.en-US.md
- components/Menu/README.zh-CN.md
- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/Table/README.en-US.md
- components/Table/README.zh-CN.md
- components/Table/__test__/virtualized.test.tsx
- components/Transfer/README.en-US.md
- components/Transfer/README.zh-CN.md
- components/Tree/README.en-US.md
- components/Tree/README.zh-CN.md
- components/Typography/README.en-US.md
- components/Typography/README.zh-CN.md
- components/_class/VirtualList/index.tsx
- stories/Table.story.tsx
|     Common      |      虚拟列表新增 `wrapperChild` 和` onScroll `属性。         |    VirtualList add new `wrapperChild` and `onScroll` properties           |                |
> add wrapperChild in virtualList

- components/Image/image-preview-group.tsx
- stories/Image.story.tsx
|  Image         | 修复 `Image` 组件边界场景下循环渲染导致白屏的 bug。               |   Fixed the bug causing white screen due to loop rendering in `Image` component boundary scene.            |          close #2128      |
> fix: image previewProps

- components/Image/image.tsx
> enhancement: image do not render loader when lazyload

- components/Form/store.tsx
|   Form        |     修复 `Form` 组件的 `resetFields` 方法传入非 string/array 类型 的参数时，所有表单项都被重置的 bug。           |    Fixed a bug that caused all form items to be reset when the `resetFields` method of the `Form` component passed in non-string/array type parameters.           |        #2486        |
> enhance: form resetFields when  get a number or symbol as argument

- components/Popover/index.tsx
- components/Tooltip/index.tsx
- components/_util/is.ts
| Popover  | `Popover` 组件当内容为空时不显示弹出框。  |  The `Popover` component does not display the popup box when the content is empty.    |  Close: https://github.com/arco-design/arco-design/issues/2498   |
> enhance: Popover hide when content is empty

- components/Trigger/getPopupStyle.ts
- components/style/theme/color/colors.less
- components/style/theme/color/css-variables.less
- components/style/theme/css-variables.less
- components/style/theme/global.less
- site/src/pages/token/tokens.js
|   Common        |  新增数据色色彩序列              |  新增数据色色彩序列             |                |
> feat: add data color list

- components/Popover/index.tsx
Popover's title and content can be function
> fix: popover title and content is function

- components/InputTag/README.en-US.md
- components/InputTag/README.zh-CN.md
- components/InputTag/__demo__/max-tag-count.md
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/input-tag.tsx
- components/InputTag/interface.ts
- components/InputTag/style/index.less
|  InputTag   |  `InputTag` 组件新增 `maxTagCount` 属性以支持自定义最多展示的标签数量。  |  `InputTag` adds a `maxTagCount` property to support customizing the maximum number of displayed tags.  |  Close #2496  |
> feat(InputTag): add new property maxTagCount

- components/InputNumber/index.tsx
优化 InputNumber 首次点击 +/- 按钮时的初始值。
> enhance(InputNumber): initial value while clicking plus/minus button

- components/ConfigProvider/README.en-US.md
- components/ConfigProvider/README.zh-CN.md
- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Trigger/README.en-US.md
- components/Trigger/README.zh-CN.md
- components/Trigger/__demo__/boundaryDistance.md
- components/Trigger/__test__/__snapshots__/demo.test.ts.snap
- components/Trigger/getPopupStyle.ts
- components/Trigger/index.tsx
- components/Trigger/interface.ts
|     Trigger      |       `Trigger` 支持根据视口自动调整位置时，设置视口偏移量        |    `Trigger` supports setting the viewport offset when automatically adjusting the position according to the viewport.           |       #2151         |
> feat: trigger supports boundaryDistance

- components/_hooks/useWatermark/index.ts
|    Watermark       |  修复 `Watermark` 在边界场景下内容显示不完全的 bug。             |      Fixed the bug of incomplete display of `Watermark` content in boundary scenes.         |   close #2499             |
> fix: watermark fix

- components/Carousel/__demo__/selfComponent.md
- components/Carousel/__demo__/vertical-card.md
- components/Carousel/__test__/__snapshots__/demo.test.ts.snap
- components/Carousel/index.tsx
- components/Carousel/style/index.less
- components/Carousel/style/slide.less
|   Carousel   |  `Carousel` 组件的 `card` 模式增加纵向排列支持            |    The `card` mode of the `Carousel` component adds vertical arrangement support   |     Close #2391     |
> feat(carousel): support vertical card

- components/ConfigProvider/README.en-US.md
- components/ConfigProvider/README.zh-CN.md
- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/__template__/index.en-US.md
- components/Form/__template__/index.zh-CN.md
- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Typography/__demo__/ellipsis.md
- site/docs/question.zh-CN.md
- site/package.json
> doc: udpate doc

- components/Typography/base.tsx
- components/_util/throttleByRafV2.ts
|  Typography  |    修复 `Typography` 组件 `resize` 节流问题    |    Fix `Typography` component `resize` throttling issue    |  Close #2485 |
> fix(typography): fix throttle problem

- CONTRIBUTING.zh-CN.md
> doc: update contribute doc

- components/DatePicker/README.en-US.md
- components/DatePicker/README.zh-CN.md
- components/DatePicker/__test__/range.test.tsx
- components/DatePicker/interface.tsx
- components/DatePicker/picker-range.tsx
- components/_class/picker/input-range.tsx
- stories/DatePicker.story.tsx
| DatePicker   | `DatePicker.RangePicker` 新增 `inputProps`.  | `DatePicker.RangePicker` adds `inputProps`.    |   Close: https://github.com/arco-design/arco-design/issues/2460  |
> feat: DatePicker add inputProps

- site/package.json
- site/src/locale/en.js
- site/src/locale/zh.js
- site/src/pages/vchart/chart/demo.js
- site/src/pages/vchart/chart/index.js
- site/src/pages/vchart/index.js
- site/src/pages/vchart/md/doc.en-US.md
- site/src/pages/vchart/md/doc.zh-CN.md
- site/src/pages/vchart/md/header.en-US.md
- site/src/pages/vchart/md/header.zh-CN.md
- site/src/pages/vchart/style.less
- site/src/routes.js
- site/yarn.lock
> doc: add vchart doc

- components/_class/picker/input-range.tsx
- stories/DatePicker.story.tsx
> Enhance rangepicker input events

- site/package.json
- site/yarn.lock
upgrade sidebar version to fix whether user has logged in checking
|           |               |               |    Close #2535            |
> chore: upgrade sidebar version to fix whether user has logged in checking

- components/ColorPicker/style/index.ts
When using babel-import-plugin, the only style introduced is `@arco-design/web-react/es/ColorPicker/style`. Because Select is used in the component, the style will be lost if there is no Select in the project.
import `Select/style`
|     ColorPicker      |       修复 `ColorPicker` 按需样式引入缺失的 bug |       Fix the bug of missing on-demand style introduction in `ColorPicker`        |                |
> fix: ColorPicker style

- components/Table/interface.tsx
|  Table         |    `Table` 组件 column 属性 TS 定义调整           |      `Table` component column attribute TS definition adjustment         |                |
报错复现：https://codesandbox.io/p/sandbox/red-glade-wwmgl2?file=%2Fdemo.tsx%3A1%2C1-109%2C1
原因：childrenColumnName被指定后，column也会会读取该字段进行遍历，但是类型接口中没有该字段，所以类型报错
看了下官网也只提到了column可以通过children嵌套。
所以增加一个判断使指定childrenColumnName不报错。
> fix: column type error

- components/ColorPicker/style/index.ts
> style: fix color-picker style import

- components/ColorPicker/README.en-US.md
- components/ColorPicker/README.zh-CN.md
- components/ColorPicker/__demo__/trigger.md
- components/ColorPicker/__test__/__snapshots__/demo.test.ts.snap
- components/ColorPicker/index.tsx
- components/ColorPicker/interface.ts
| ColorPicker  |   `ColorPicker` 组件增加对自定义触发元素的支持  |   `ColorPicker` component adds support for custom trigger elements    |    Close #2536   |
> feat(color-picker): add custom render

- components/Tooltip/index.tsx
| tooltip          |    合并className           |               |                |
复现Demo：
```tsx
<Tooltip
position="tl"
trigger="hover"
content="上左～～～"
className="a"
triggerProps={{ className: 'b' }}
>
<Button style={{ position: 'absolute', top: 20, left: 70 }}>上左</Button>
</Tooltip>
```
a和b className无法同时展示
> fix: tooltip merge classname

- components/Select/style/token.less
|   Select  |  `Select` 组件 `large` 尺寸下的选择框文本由 `16px` 调整为 `14px`。  |   The font size of the selection box under the `large` size of the `Select` component is adjusted from `16px` to `14px`.   |                |
> style(Select): change font size of Select with size:large to 14px

- components/Tabs/tab-header/tab-ink.tsx
|   Tabs        |      优化默认类型的 `Tabs` 组件 activeTab 不存在时，下划线位置未调整的问题。        |      Optimize the problem that the underline position is not adjusted when the default type of `Tabs` component activeTab does not exist.         |   close #2568             |
> style: line tabs hide ink

- components/Form/context.ts
| Form          |    修复 `Form.useFormContext` 未在 `Form` 组件下使用导致的内部方法调用报错的 bug。            |       Fixed the bug of internal method call error caused by `Form.useFormContext` not being used under `Form` component.        |                |
> fix: form should determine whether getInnerMethods exists

- components/Table/tbody/index.tsx
|  Table   |   修复 `Table` 由于 ReactKey 缺失导致的控制台警告。 |  Fix `Table` console warning due to missing ReactKey.  |   Close #2579     |
> fix(Table): React unique-key warning caused by TBody

- components/Input/__test__/index.test.tsx
- components/Input/input-element.tsx
|  Input         |   `Input` 组件支持 `onCompositionStart`、  `onCompositionUpdate`、 `onCompositionEnd` 事件             |                  `Input` supports `onCompositionStart`、  `onCompositionUpdate`、 `onCompositionEnd` property                |close #2581|
> feat: input supports onCompositionEvent

- .github/workflows/deploy-site-preview.yml
- components/Form/hooks/useContext.ts
| Form          |    修复 `Form.useFormContext` 未在 `Form` 组件下使用导致的内部方法调用报错的 bug。            |       Fixed the bug of internal method call error caused by `Form.useFormContext` not being used under `Form` component.        |                |
> fix: form context

- components/InputNumber/README.en-US.md
- components/InputNumber/README.zh-CN.md
- components/InputNumber/__test__/index.test.tsx
- components/InputNumber/index.tsx
- components/InputNumber/interface.ts
- components/Slider/input.tsx
|   InputNumber  |  `InputNumber` 组件 `onChange` 回调新增 `reason` 参数用于通知组件值改变的原因。   |   The `onChange` callback of the `InputNumber` component adds a `reason` parameter to notify the component of the reason for the value change.    |     Close #2556      |
> feat(InputNumber): notify reason of onChange callback triggered

- components/Image/image-preview.tsx
- components/Image/interface.ts
|  Image  |  `Image` 新增 `resetTranslate` 属性  |  `Image`  supports `resetTranslate`property   |   Close #2580    |
> feat: add disableTranslateCorrection

- .github/workflows/deploy-site-preview.yml
- components/Slider/__demo__/input.md
- components/Slider/__demo__/marks.md
- components/Slider/__demo__/range-multi.md
- components/Slider/__test__/__snapshots__/demo.test.ts.snap
- components/Slider/dots.tsx
- components/Slider/hooks/useLegalValue.ts
- components/Slider/index.tsx
- components/Slider/interface.tsx
- components/Slider/ticks.tsx
- components/Slider/utils.ts
|     Slider      |   `Slider` 支持范围内多点选择            |      `Slider` supports multi-point selection within a range         |    close #2575             |
> feat: slider supports multiple points

- components/Input/style/index.less
|    Input       |  修复 `Input` 组件设置 `allowClear`且自适应宽度时，清除图标错位的 bug。             |    Fixed the bug of icon misalignment when the `Input` component is set to `allowClear` and the width is adaptive.           |        close #2598         |
|    Input       |   自适应宽度的 `Input` 组件在文本被 Hover 时不显示省略状态。             |       The autowidth `Input` component does not show the omitted state when the text is hovered.        |   close #2598              |
> fix: input autowidth fix

- components/AutoComplete/index.tsx
- components/Input/search.tsx
| Input          |     修复 `Input.Search` 无法透传 `suffix` 和 `addAfter` 的问题          |     Fix the problem that `Input.Search` cannot transparently transmit `suffix` and `addAfter`          |                |
已经在oncall群里反馈过该问题
> fix: can not use suffix and addAfter prop in input-search

- components/Table/style/index.less
- components/Table/table.tsx
|   table        |   修复rtl切换时fixedClassName错误的问题            |               |                |
复现Demo：
```ts
import React from "react";
import { Table, ConfigProvider } from "@self";
const columns = [
{
title: "Name",
dataIndex: "name",
fixed: "left",
width: 140,
},
{
title: "Address",
dataIndex: "address",
},
{
title: "Email",
dataIndex: "email",
},
{
title: "Other",
dataIndex: "other",
render: () => "Other",
},
{
title: "Other 1",
dataIndex: "other1",
render: () => "Other 1",
},
{
title: "Other 2",
dataIndex: "other2",
render: () => "Other 2",
},
{
title: "Salary",
dataIndex: "salary",
fixed: "right",
width: 120,
},
];
const data = [
{
key: "1",
name: "Jane Doe", …
```
> fix: wrong fixedClassName

- components/Watermark/__demo__/props.md
- components/Watermark/__test__/__snapshots__/demo.test.ts.snap
- components/_hooks/useWatermark/index.ts
|    Watermark       |     修复 `Watermark` 在像素比=1 时显示不完全的 bug。           |      Fix the bug of incomplete display of `Watermark` when pixel ratio=1.         |       close #2585         |
> fix: watermark in ratio=1

- components/Carousel/index.tsx
- components/Carousel/style/index.less
- components/Carousel/style/slide.less
|    Carousel       |   修复 Carousel 在组件 rtl  视图下指示器表现异常的 bug。   |    Fixed the bug where the Carousel indicator behaved abnormally in the component rtl view.           |                |
|    Carousel       |  修复 Carousel 组件 rtl 下 animation='card' 展示异常的 bug    |           Fixed the bug of abnormal display of animation='card' under Carousel component rtl    |                |
> fix: carousel rtl

- components/Tooltip/style/index.less
|     tooltip      |    修复rtl是文本没对齐的问题           |               |                |
> fix: tooltip rtl

- components/Form/__test__/validate.test.tsx
- components/Form/utils.tsx
执行 `form.validate({ validateOnly: true });` 时会报错：
对 rules 为 null 或 undefined 时进行兜底取 '[]'
补充未设置 rules 的 form item 作为测试用例：
|  Form  |    修复 `Form` 组件 rules 未设置且 validate 方法 validateOnly 为 true 时报错问题           |   Fixed an error issue when `Form` component rules is not set and validate method validateOnly is true   |                |
> fix: 修复 rules 未设置且 validate 方法 validateOnly 为 true 时报错问题

- components/Form/__test__/use.test.tsx
- components/Form/hooks/useContext.ts
- components/Form/store.tsx
|   Form        |      修复 `Form.useFormContext` 组件 `isSubmitting` 有误的 bug。        |      Fix the bug that `Form.useFormContext` component `isSubmitting` is incorrect.         |      close          #2628 |
> fix: form submitting

- components/Tree/index.tsx
|    Tree       |    修复 `Tree` 组件在 React 18 下边界场景出现折叠后的节点无法展开的 bug           |     Fixed the bug where the collapsed nodes of the `Tree` component in the lower boundary scene of React 18 cannot be expanded.          |     close #2617           |
> fix: tree expand not work in react 18

- components/Dropdown/index.tsx
|  Dropdown         |  修复 `Dropdown` 组件的全局 componentConfig 不生效的 bug             |     Fix the bug that the global componentConfig of the `Dropdown` component does not take effect          |        close #2630         |
> fix: dropdown componentConfig

- components/Form/style/status.less
- components/InputNumber/index.tsx
- components/InputNumber/style/index.less
|       Form     |      修复 `Form` rtl 视图样式问题         |     Fix `Form` rtl view style issue          |                |
|       InputNumber     |      修复 `InputNumber` rtl 视图样式问题         |     Fix `InputNumber` rtl view style issue          |                |
> fix: form rtl

- components/Radio/README.en-US.md
- components/Radio/README.zh-CN.md
RadioGroup 文档中遗漏 disabled 配置项，不知道是否是有意为之，但是我发现  RadioGroup  中 disabled 可以正常使用
|    Radio       |      RadioGroup 文档中新增 `disabled` 配置项         |     Add `disabled` option to RadioGroup docs          |                |
> docs: add 'disabled' option to RadioGroup docs

- components/Message/index.tsx
|       Message    | `Message.config` 支持 `closable` 参数            |      `Message.config` supports `closable` parameter         |      close #2648          |
> feat: message.config supports closable

- .github/workflows/deploy-site-preview.yml
- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/InputNumber/__demo__/format.md
- components/InputTag/README.en-US.md
- components/InputTag/README.zh-CN.md
- components/InputTag/__demo__/responsive-tag.md
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/input-tag.tsx
- components/InputTag/interface.ts
- components/Radio/README.en-US.md
- components/Radio/README.zh-CN.md
- components/Radio/interface.ts
- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/Select/__demo__/darggable.md
- components/Select/__demo__/maxTag.md
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Select/select.tsx
- components/TreeSelect/README.en-US.md
- components/TreeSelect/README.zh-CN.md
- components/_class/OverflowEllipsis/OverflowItem.tsx
- components/_class/OverflowEllipsis/index.tsx
- components/_class/OverflowEllipsis/style/index.less
- components/_class/select-view.tsx
|   Select        |   `Select` 支持响应式 Tag 数            |       `Select` supports responsive Tag number        |            close #2619     |
|   InputTag        |   `InputTag` 支持响应式 Tag 数            |       `InputTag` supports responsive Tag number        |            close #2619     |
> feat: select supports max tag

- components/Typography/ellipsis.tsx
|   Typography   |   修复 `Typography.Ellipsis`  在 safari 下不显示的问题。因环境差异， safari 下为兼容显示         |   Fix the problem that `Typography.Ellipsis` is not displayed in safari. Due to environmental differences, compatibility is displayed under safari.   |     Close #2646   |
> fix: fix safari problem

- components/ColorPicker/README.en-US.md
- components/ColorPicker/README.zh-CN.md
- components/ColorPicker/index.tsx
- components/ColorPicker/interface.ts
- components/ColorPicker/panel.tsx
- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Image/image.tsx
- components/Image/interface.ts
|  ColorPicker  |   `ColorPicker` 组件增加 `onChangeComplete` 和 `renderFooter` 属性            |    `ColorPicker` component adds `onChangeComplete` and `renderFooter` properties    |   Close #2561 , Close #2560     |
补充 Image 文档 Close #2530
> feat: add props & doc

- components/InputTag/input-tag.tsx
|    InputTag       |    修复 `InputTag` 组件 maxTagCount.render 属性报错的 bug.           |    Fixed the bug where the maxTagCount.render property of the `InputTag` component reported an error.           |                |
> fix: max tag render

- components/_class/select-view.tsx
|     Select      |  修复 `Select` renderTag 和 maxTagCount 同时使用时渲染节点样式有误的 bug(`2.62.0` 引入)。             |  Fixed a bug in which the rendering node style is incorrect when `Select` renderTag and maxTagCount are used at the same time (introduced in `2.62.0`).             |                |
> fix: select  tag render

- components/Upload/__demo__/renderUploadList.md
- [√ ] Bug fix
图例中的image弹框没有展示图片
修改下内部取值逻辑，用一下自己处理的url
修改即可生效查看
无
无
> fix:upload image demo

- components/Select/__test__/index.test.tsx
- components/_util/hooks/usePersistCallback.ts
- stories/Select.story.tsx
|  Select         |     修复 `Select` 组件 options 改变时，选中项展示未及时更新的 bug（`2.63.0` 引入）          |      Fixed a bug where the selected item display was not updated in time when the `Select` component options changed (introduced in `2.63.0`)         |                |
> fix: select label render

- components/_util/react-dom.ts
|      Common     |       优化 `findDOMNode` 控制台 warning          |         Optimize `findDOMNode` console warning      |   close #2713             |
> fix: dedupe findDOMNode warnings

- components/Avatar/style/index.less
close #2691 
https://github.com/ant-design/ant-design/blob/502dac12aaddaf407565c8698abd29dd1fc892dc/components/avatar/style/index.ts#L104
> fix: prevent phantom space in avatar image

- components/DatePicker/index.tsx
- components/DatePicker/interface.tsx
- components/DatePicker/picker-range.tsx
- components/DatePicker/picker.tsx
| DatePicker  | 修复`DatePicker`和`DatePicker.RangePicker`组件缺失ref的问题，使用`forwardRef`转发ref | Fixed a bug where `DatePicker` and `DatePicker.RangePicker` components missing refs, add `forwardRef` to expose refs. |  |
> fix: DatePicker and DatePicker.RangePicker missing refs

- components/Upload/util.tsx
|     Upload      |  优化 `Upload`  组件文件夹上传读取文件判空逻辑，避免边界场景下报错            |       Optimize the logic of judging empty files when reading files in folder upload of `Upload` component to avoid errors in edge scenarios        |     close #2766            |
> fix: upload

- components/_util/is.ts
- components/_util/react-dom.ts
|     Common      |    兼容 react 19 findDOMNode 报错             |        Compatible with react 19 findDOMNode error       |                close #2696|
> enhance: warning tip only in react18

- package.json
- yarn.lock
react-focus-lock 依赖的 focus-lock 使用了WeakRef，在较低版本浏览器中存在兼容性问题
|  Common         |    升级依赖 `react-focus-lock` 版本，解决  WeakRef 不兼容问题           |         Upgrade the dependency `react-focus-lock` version to solve the WeakRef incompatibility issue      |                |
> chore: 升级react-focus-lock,解决WeakRef不兼容问题

- package.json
- yarn.lock
> Upgrade focus lock

- components/_class/picker/input-range.tsx
- components/_class/picker/input.tsx
> Fix datepicker focus

- components/InputTag/input-tag.tsx
- components/Tabs/tab-header/tab-ink.tsx
- components/_class/picker/input.tsx
|      DatePicker     |  修复 `DatePicker` 组件弹出层位置未对齐选择框的样式问题             |      Fixed the problem that the popup layer position of the `DatePicker` component is not aligned with the selection box style         |                |
> fix: datepicker 弹出层位置对齐问题 bugfix

- components/Form/__demo__/normalize.md
- components/Form/__demo__/update.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Modal/__demo__/custom_button_text.md
- components/Notification/__demo__/btn.md
- components/Popconfirm/__test__/index.test.tsx
- components/locale/en-US.tsx
- components/locale/pt-BR.tsx
- components/locale/pt-PT.tsx
- site/src/index-en.js
> chore: update ok text

- components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
- components/DatePicker/__test__/panel.test.tsx
- components/DatePicker/__test__/range.panel.test.tsx
- components/DatePicker/__test__/range.test.tsx
- components/DatePicker/panels/header.tsx
- components/DatePicker/panels/quarter/index.tsx
- components/locale/en-US.tsx
- components/locale/interface.tsx
- components/locale/ja-JP.tsx
- components/locale/ko-KR.tsx
- components/locale/zh-CN.tsx
- components/locale/zh-HK.tsx
- components/locale/zh-TW.tsx
| DatePicker  | `DatePicker` 支持通过配置 `locale` 文件中的 `yearFormat` 和 `monthFormat` 来定制面板头部的时间格式。   |`DatePicker` supports customizing the time format of the panel header by configuring `yearFormat` and `monthFormat` in the `locale` file.   | close: https://github.com/arco-design/arco-design/issues/2783   |
> Feat datepicker panel header

- components/Badge/index.tsx
> fix: ts error in badge component

- components/_class/VirtualList/Filler.tsx
|  Table   |    `Table` 组件修复开启虚拟列表且数据量少时，固定列失效的问题   |  `Table` component fixes the problem that fixed columns become invalid when the virtual list is enabled and the amount of data is small   |                |
> fix(table): fix virtual list problem

- components/Timeline/__demo__/pending.md
修复文档中关于Timeline幽灵节点horizontal复选框无法反复勾选
> 修复文档中关于Timeline幽灵节点horizontal复选框无法反复勾选

- components/TreeSelect/README.zh-CN.md
- components/TreeSelect/interface.ts
- [ √ ] Documentation change
树形选择器treeCheckStrictly属性文档内容与属性命名关联不强，增加文档解释说明，更加贴切
修改文档
|    TreeSelect       |       树选择        |       docx explain        |      none          |
> docx:对树形选择器treeCheckStrictly属性文档进行说明，防止歧义

- site/src/pages/dark/md/header.en-US.md
- site/src/pages/dark/md/header.zh-CN.md
The `addListener` method is deprecated. See https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
Use `addEventListener` instead. 
> docs: update the sample code related to dark mode

- components/ColorPicker/hooks/useControlBlock.ts
ColorPicker在弹出画板上按下鼠标后，鼠标移出画板,继续拖动鼠标，会选中外层DOM元素。
拖动鼠标浏览器默认行为会选中文字。在onMouseDown事件中增加ev.preventDefault();组织浏览器默认行为。
弹出画板，拖动鼠标不会再选中外层文字。
|    ColorPicker       |     修复 `ColorPicker` 在弹出画板上按下鼠标后，鼠标移出画板时，会选中外层 DOM 元素          |     Fix for `ColorPicker` to select the outer DOM element when the mouse is moved out of the popup artboard after pressing the mouse          |      close   https://github.com/arco-design/arco-design/issues/2817       |
> fix: 修复ColorPicker在弹出画板上按下鼠标后，鼠标移出画板时，会选中外层DOM元素

- components/Input/input.tsx
|     AutoComplete      |  修复 `AutoComplete` 下拉框未完全对齐 bug。             |          修复 `AutoComplete` 下拉框未完全对齐 bug。     |                |
> fix: autocomplete dropdown align

- components/Anchor/anchor.tsx
- components/Cascader/panel/search-panel.tsx
- components/_class/VirtualList/index.tsx
- components/_util/scrollIntoView.ts
- package.json
- yarn.lock
|   Common        |    依赖库 `scroll-into-view-if-needed` 版本号更新           |        Dependency library `scroll-into-view-if-needed` version number updated       |                |
|   Cascader        |    修复 `Cascader` 搜索面板键盘操作时当前高亮选项未自动滚动到视口的 bug。           |      Fixed the bug that the currently highlighted option did not automatically scroll to the viewport when using the keyboard in the `Cascader` search panel.         |                |
> fix: update scroll-into-view-if-needed deps version

- package.json
- yarn.lock
https://github.com/theKashey/react-focus-lock/releases/tag/v2.13.0
> when the focus lock is active inside iframe
> before: it will (endlessly) fight with focus lock that might be present in the parent frame
> now: the parent frame always wins
>    explanation: as for parent focus inside iframe means iframe is focused, and it will prevent another element on the same page from being focused
|      Common     |      升级 `react-focus-lock` 依赖版本，解决 iframe 焦点抢占问题         |     Upgrade `react-focus-lock` dependency version to solve the iframe focus grabbing problem          |                |
> fix:  focus is trapped inside the iframe

- components/DatePicker/panels/header.tsx
See #2849 .Some components are missing the key attribute, which is causing errors during the date picker rendering.
Add key attributes.
|      DatePicker     |      修复因为key属性缺失发生的控制台报错问题         |         Fix the console errors caused by the missing key attributes.      |        #2849         |
> fix: datepicker key prop missing

- components/Form/utils.tsx
|   Form        |    修复 `Form` 组件里 `flat` 语法不兼容低版本浏览器 bug            |      Fixed the bug that `flat` syntax in `Form` component is not compatible with lower version browsers         |         close #2879       |
> fix: form flat

- components/Tree/context.tsx
- components/Tree/index.tsx
- components/Tree/interface.ts
- components/Tree/node.tsx
|    Tree       |     `Tree` 组件支持通过 `animation` 属性关闭节点展开收起动画          |       `Tree` component supports turning off node expansion and collapse animations through the `animation` property        |                |
> feat: tree supports animation property

- components/Tree/animation.tsx
- components/_class/OverflowEllipsis/index.tsx
|   Select        |     修复 `Select` 组件 maxTag=responsive 时偶发表现异常的 bug。          |     Fixed a bug where `Select` component occasionally behaved abnormally when maxTag=responsive.          |     close #2852           |
> fix: select responsive max tag

- components/Cascader/panel/search-panel.tsx
- components/Tree/animation.tsx
- components/_class/OverflowEllipsis/index.tsx
|     Cascader      |    `Cascader` 设置`changeOnSelect`  时，搜索面板渲染节点表现异常          |    When `Cascader` sets `changeOnSelect`, the search panel rendering node behaves abnormally           |                |
> fix: cascader 搜索面板显示bug

- components/_class/select-view.tsx
support select component maxTagCount popover attribute modification
support select component maxTagCount popover attribute modification
|    Select       |      `Select/Cascader/TreeSelect` 组件 `maxTagCount.showPopover` 支持传入 `popoverProps`         |               |    `Select/Cascader/TreeSelect` component `maxTagCount.showPopover` supports passing `popoverProps`.            |
> support select component maxTagCount popover attribute modification 

- site/docs/designlab/use-theme-package.en-US.md
- site/docs/designlab/use-theme-package.zh-CN.md
https://github.com/arco-design/arco-design/issues/2914
Update the correct npm dependency package name.
> docs: updated use theme package (#2914)

- components/Trigger/index.tsx
After using clickOutsideToClose.capture of triggerProps, an error will occur: Uncaught Error: Unable to find node on an unmounted component.
Remove clickOutsideToClose capture event when component is destroy
|      Trigger     |       修复 `Trigger` 组件 `clickOutsideToClose` capture event 未销毁报错问题        |      Fixed the issue that clickOutsideToClose capture event was not destroyed and reported an error         |     close   https://github.com/arco-design/arco-design/issues/2883        |
> fix: Remove clickOutsideToClose capture event when component is destroy

- components/_util/dayjs.ts
|  DatePicker   |  修复 `DatePicker` 组件设置时区后，如果有冬令时和夏令时，在边界点会存在多一个小时或者少一个小时的情况。  |  Fixed the issue that after the `DatePicker` component sets the timezone, if there is PST and PDT, there will be one hour more or less at the boundary point.  |  Close: https://github.com/arco-design/arco-design/issues/2937 |
> timezone PST and PDT case, find the lost 1 hour

- components/Form/control.tsx
FormItem `shouldUpdateItem` check will **always** triggered when declaring dependencies of these field, as they are always `string[]` according to the documents. the code logic may be short-circuit .
Changed it to `&&`
Not so easy to unittest as it is some internal logic, but we surely encountered performance issues of so many unnecessary validations in our biz code..
|     Form      | 修复 `Form` 组件 dependcies 执行时机 bug。（仅在 dependencies 指定的字段的值发生改变时，才触发自身 Form.Item 的校验）              |     Fixed the "Form" component dependcies execution timing bug. (Only when the value of the field specified by dependencies changes, the validation of Form.Item itself is triggered) …
> fix: form dependencies should check only if contains field

- components/Mentions/__demo__/prefix.md
- components/Mentions/__test__/__snapshots__/demo.test.ts.snap
- components/Mentions/index.tsx
[#2829](https://github.com/arco-design/arco-design/issues/2829)
> fix: 修复了提及组件自定义触发字符设置多个字符的问题

- components/_util/dayjs.ts
> fix: when set utcOffset, timezone not work

- .github/workflows/deploy-site-preview.yml
- .github/workflows/pr_check.yml
- components/Collapse/item.tsx
- package.json
|     Collapse      |   修复 `Collapse` 在 react 19 下报错问题            |    Fix `Collapse` error in react 19           |   close #2949             |
> fix: collapse react19 not work

- components/Message/__test__/useMessage.test.tsx
- components/Message/useMessage.tsx
- stories/Message.story.tsx
|Message| 修复 `Message.useMessage` 在异步执行场景报错的 bug。|Fixed the bug that `Message.useMessage` reports an error in asynchronous execution scenarios.|close #2934|
> fix(Message): correct useMessage hook usage in test cases

- components/Carousel/README.en-US.md
- components/Carousel/README.zh-CN.md
- components/Carousel/interface.ts
Fix #2943 
| Carousel  | 修正 `Carousel` 组件 `CarouselProps. indicatorPosition` 定义 | Revise the definition of `CarouselProps.indicatorPosition` | close #2943          |
> fix: 修正 CarouselProps 定义 #2943

- components/Cascader/cascader.tsx
- stories/Cascader.story.tsx
Update the dependency array in the useMemo hook to use `getSelectedOptionsByValue` instead of `store` for better consistency and accuracy in the Cascader component. Also, add a new `MultiDemo` story to demonstrate the multiple mode functionality.
|Cascader |修复 `Cascader` 组件受控时延迟设置值时未正确回显选项标签的 bug 。 |Fixed a bug where the `Cascader` component was not echoing option tags correctly when setting values ​​lazily while being controlled.| close #2941|
> fix(Cascader): update dependency array in useMemo #2941

- components/ColorPicker/style/index.less
- components/ColorPicker/style/token.less
|    ColorPicker       |      修复 `ColorPicker` 组件样式变量引用未加 css 变量前缀的 bug。         |        Fixed the bug that `ColorPicker` component style variable reference was not prefixed with css variable.       |                |
> fix: colorpicker colors

- components/Collapse/item.tsx
- stories/Collapse.story.tsx
|   Collapse        |   修复 `Collapse` 组件内容异步加载时，已展开面板展示不完整bug。            |      Fixed the bug that the expanded panel is not fully displayed when the `Collapse` component content is loaded asynchronously.         |                |
> fix: collapse.item 异步加载显示异常的bug

- components/InputTag/style/index.ts
| InputTag  | 修复 `InputTag` 组件按需引入样式时 maxTagCount="responsive" 不生效的问题 |  Fixed the issue where maxTagCount="responsive" does not take effect when the `InputTag` component imports styles on demand |close #2991  |
> fix: InputTag未引用OverflowEllipsis的样式

- components/Table/table.tsx
| Table  | 修复`ConfigProvider` 配置的 `size=mini` 对 `Table` 组件不生效的问题 |  Fixed the issue that `size=mini` configured by `ConfigProvider` does not work for `Table` component |   |
> fix(table): support inherited 'mini' size in Table

- components/_util/color.ts
|   ColorPicker  |    修复 RGB 值在清空时导致不可输入的问题   |  Fixed the issue that RGB value cannot be input when cleared   |                |
> fix(color-picker): fix undefined value problem

- components/Cascader/base/node.ts
- components/Cascader/base/store.ts
|  Cascader  |  修复 `Cascader` 组件在开启 `loadMore` 之后，对 `isLeaf` 节点选中判断有问题的 bug。   | Fixed a bug in the `Cascader` component where the `isLeaf` node selection check would fail after `loadMore` was enabled.   |                |
> Fix Cascader loadmore half select and full select, isLeaf check

- components/Steps/style/circle.less
|   Steps   |    修复完成状态下连线没有变色的问题  |   Fixed the issue where the connection line did not change color in the completed state    |                |
> fix(steps): fix tail color problem
