- CONTRIBUTING.zh-CN.md
> docs: fix incorrect link

- site/src/pages/icon/style.less
> doc: Resolves #82

- README.md
- README.zh-CN.md
> docs: readme add gif

- .github/workflows/release.yml
Add a new CI pipeline to auto create release when a new tag is created.
> Add a new CI pipeline to auto create release when a new tag is created.

- site/docs/question.zh-CN.md
| question.zh-CN.md | "偷传” -> "透传", "的时" -> "的时候" |               |                |
> chore: fix typo

- components/Progress/index.tsx
- components/Progress/interface.ts
- components/Progress/line-progess.tsx
- components/Progress/steps-progress.tsx
|       Progress    |   添加trailColor改变Progress剩余颜色            |  add trailColor to change the rest of progress bar             |                |
> feat: add trailColor to progress

- components/DatePicker/__test__/format.test.tsx
- components/_util/dayjs.ts
|  DatePicker | `DatePicker` 组件如果值是 `string` 类型，且跟 format 不一致导致解析为 Invalid Date 时，会兜底尝试 format="YYYY-MM-DD"   | If the value of the `DatePicker` component is `string` and it's dayjs value parsed as Invalid Date, will fallback format to "YYYY-MM-DD" | Close：https://github.com/arco-design/arco-design/issues/105 |
> enhancement: DatePicker dayjs add fallback format

- components/Form/__demo__/async-validate.md
- components/Form/__demo__/control.md
- components/Form/__demo__/custom.md
- components/Form/__demo__/disabled.md
- components/Form/__demo__/layout.md
- components/Form/__demo__/list-nest.md
- components/Form/__demo__/list.md
- components/Form/__demo__/nest-form-item.md
- components/Form/__demo__/nest.md
- components/Form/__demo__/normalize.md
- components/Form/__demo__/register.md
- components/Form/__demo__/scrollToField.md
- components/Form/__demo__/setFields.md
- components/Form/__demo__/size.md
- components/Form/__demo__/validate-status.md
- components/Form/__demo__/validate.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/interface.tsx
- components/Form/store.tsx
|   Form        | 调整 `Form` 组件的 TS 定义为 `FormHTMLAttributes`  |    Adjust the TS definition of the `Form` component as `FormHTMLAttributes`           |    close #100             |
|   Form        |   修复 `Form.List` 组件通过 `add()` 方法创建表单项，传入的默认值在该表单项带有 `initialValue` 时候未生效的 `bug` 。              |      Fix the `bug` that the `Form.List` component creates form items through the `add()` method, and the default value passed in does not take effect when the form item has an `initialValue`.         |       close #117         |
> fix: 修复 Form  组件 ts 定义 & 修复通过 Form.List 的 add 方法创建的 Form.Item 的初始值不应该生效的bug。

- components/Table/style/index.less
| Table | 修复 `Table` 组件在表头分组时，`border={{ border: true, headerCell: true }}` 时，表头边框线断裂的问题。  | Fix the problem that the border line of the header is broken when `border={{ border: true, headerCell: true }}` when the `Table` component is grouped columns in the header.  |  Close: https://github.com/arco-design/arco-design/issues/92 |
> style: fix table border and cell border when group header columns

- components/InputNumber/index.tsx
InputNumber should NOT show error status when given a value with wrong precision
Only show error status when given value is out of range defined by min/max.
|InputNumber | 修复 `InputNumber` 在传入与 `precision` 精度不一致的 `value` 时展示了错误状态的 bug。 | Fix the bug that `InputNumber` showed an error status when passing in `value` that is inconsistent with `precision`. |        |
> fix: InputNumber should NOT show error status when given a value with wrong precision

- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Image/__test__/preview.test.tsx
- components/Image/image-preview.tsx
- components/Image/interface.ts
feat(image): support pressing ESC to close the preview Close #31 
|     Image      |      `Image.Preview` 组件支持按 `ESC` 关闭         |   Component `Image.Preview` support pressing `ESC` to close           |       Close #31          |
> feat(image): support pressing `ESC` to close the preview

- site/docs/material/develop.docgen.en-US.md
- site/docs/material/develop.docgen.zh-CN.md
Update some document for Material Market.
> doc: update document for Material Market

- components/Table/style/index.less
| Table  | 修复 `Table` 组件在列存在筛选时，单元格 align = 'right' 时会重叠的样式问题。 | Fix the style problem that the cell align ='right' will overlap when the `Table` component has filter in the column.  | Close: https://github.com/arco-design/arco-design/issues/132   |
> style: fix Table column align right + filter

- components/Tabs/tabs.tsx
add property `addButton` `deleteButton` `icons ` `children `  `size` `type` to the function `omit`.
|   tabs        |      从 `tabs` 的 `div` 标签中删除无法识别的属性         |     remove props which can not be recognized in div tag of tabs          |       -         |
> fix(tabs): remove props which can not be recognized in div tag of tabs

- components/Image/image.tsx
- components/Image/style/image.less
Hide img after loading error.
|      Image     |    加载错误后图片应该隐藏           |      the img should be hidden after loading failure         |       -         |
> fix(image): the img should be hidden after loading failure

- components/Form/__demo__/async-validate.md
- components/Form/__test__/case.test.tsx
- components/Form/store.tsx
- components/style/theme/color/colors.less
- components/style/theme/global.less
|       Form    |   修复 `Form.Item` 的初始值不生效的 bug            |    Fix the bug that the initial value of `Form.Item` does not take effect           |                |
> fix: 修复 `Form.Item` 初始值不生效的bug & style: 色彩变量 @color-link-x 从预置色板取值

- components/Tooltip/style/index.less
| Tooltip | `Tooltip` 组件在暗黑模式下添加边框，避免在弹出框内跟底色重合。  |`Tooltip` component add a border in dark mode to avoid overlapping with the background color in the popup box.| Close: https://github.com/arco-design/arco-design/issues/134 |
> style: Tooltip dark mode add border

- components/Descriptions/__test__/__snapshots__/demo.test.ts.snap
- components/Descriptions/__test__/__snapshots__/index.test.tsx.snap
- components/Descriptions/index.tsx
- components/Descriptions/style/index.less
- components/Typography/__test__/__snapshots__/demo.test.ts.snap
| Descriptions | 修复 `Descriptions` 组件在 `tableLayout=fixed` 且为非 inline 布局时错位的问题。  | Fix the problem that the `Descriptions` component is misplaced when `tableLayout=fixed` and non-inline layout. | Close: https://github.com/arco-design/arco-design/issues/143 |
> style: Descriptions table-layout: fixed

- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Table/__test__/columns.test.tsx
- components/Table/colgroup.tsx
Table remove colgroup style min-width.
> style: remove table colgroup min-width

- components/style/theme/color/css-variables.less
> style: add link css-variables

- components/Popconfirm/index.tsx
- components/Popconfirm/interface.ts
- components/Tooltip/index.tsx
- components/Tooltip/interface.ts
- components/Trigger/README.en-US.md
- components/Trigger/README.zh-CN.md
- components/Trigger/index.tsx
- components/Trigger/interface.ts
Close #58 
在 `Trigger` 组件中添加 `escToClose`，默认为 `false`。
在 `Tooltip` 组件中添加 `escToClose`，默认为 `false`。
在 `Popconfirm` 组件中添加 `escToClose`，默认为 `true`。
|Trigger|`Trigger` 组件添加 `escToClose` 设置是否允许按 `ESC` 关闭，默认为 `false`。|`Trigger` add `escToClose` to set whether to allow close the popup by pressing `ESC`, default value is `false`.|Close #58|
|Tooltip|`Tooltip` 组件添加 `escToClose`，默认为 `false`。|`Trigger` add `escToClose`, default value is `false`.|Close #58|
|Popconfirm|`Popconfirm` 组件添加按 `ESC` 关闭弹出框功能。|`Popconfirm` allow close confirmation box by pressing `ESC`.|Close #58|
> feat: add prop escToClose in Trigger

- components/Select/__demo__/custom-trigger.md
- components/Select/__demo__/group.md
Close: https://github.com/arco-design/arco-design/issues/168
> docs: select typo and demo fix

- components/Image/__test__/__snapshots__/demo.test.ts.snap
- components/Image/image.tsx
- components/Image/style/image.less
set the max size of error to fit parent.
|     Image      |    `Image` 组件将错误状态的最大尺寸设置为父元素的大小。      |  The `Image` component sets the maximum size of the error state to the size of the parent element.  |     Close #135            |
> style(image): set the max size of error to fit parent

- components/Progress/__demo__/trailColor.md
- components/Progress/__test__/__snapshots__/demo.test.ts.snap
- components/Progress/__test__/index.test.tsx
- components/Progress/index.tsx
- components/Progress/steps-progress.tsx
|     Progress      |     `Progress` 修复 `trailColor` 属性在环形进度条和步骤进度条不生效的 bug。          |     `Progress`  gix the bug that the'trailColor 'attribute does not take effect on the circular progress bar and the step progress bar. |     close #159            |
> fix: trailColor does not work on CircleProgress

- components/Button/style/token.less
| Button | `Button` 组件左右边距 + 边框为 16px。  | The padding + border of the `Button` component is 16px.| Close: https://github.com/arco-design/arco-design/issues/172 |
> style: Button horizontal padding change to 15px

- components/Form/interface.tsx
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- package.json
- yarn.lock
| Form  | `Form` 组件 `rule.message` 支持使用 `ReactNode`。 | The `Form` component `rule.message` supports the use of `ReactNode`. |  Close: https://github.com/arco-design/arco-design/issues/171   |
> feat: Form rules message support ReactNode

- components/Carousel/README.en-US.md
- components/Carousel/README.zh-CN.md
- components/Carousel/__test__/index.test.tsx
- components/Carousel/arrow.tsx
- components/Carousel/index.tsx
- components/Carousel/interface.ts
Allow user to customize icon of Carousel arrows.
Add a new property `icons`.
Test case has been added for it.
|  Carousel    | `Carousel` 新增 `icons` 属性以支持自定义箭头图标。 |   `Carousel` adds `icons` property to support custom arrow icons.   | #162  |
> feat: Carousel add propery icons to customize icon in arrows

- components/Progress/steps-progress.tsx
https://codesandbox.io/s/suspicious-ptolemy-kcp08?file=/index.js
|     Progress      |    修复 `Progress` 组件步骤显示计算错误的 bug。        |   Fix the bug that the steps of the `Progress` component are displayed incorrectly.    |                |
> fix(steps-progress): step active display error because calculation

- components/ResizeBox/__test__/index.test.tsx
- components/ResizeBox/interface.ts
- components/ResizeBox/split.tsx
#166 
trigger callback when pane size is changed
|      ResizeBox     |    `ResizeBox.Split` 增加 `onPaneResize` 属性           |    add property `onPaneResize` to `ResizeBox.Split`           |      Close  #166         |
> feat(resizebox): add onPaneResize to ResizeBox.Split

- components/Dropdown/__demo__/control.md
- components/Dropdown/__test__/__snapshots__/demo.test.ts.snap
- components/Dropdown/__test__/index.test.tsx
- components/Dropdown/index.tsx
- components/Menu/README.en-US.md
- components/Menu/README.zh-CN.md
- components/Menu/interface.tsx
- components/Select/__demo__/group.md
- components/_class/VirtualList/index.tsx
Allow users to control whether the `Menu` is hidden after clicking through the return value of `onClickMenuItem`.
Test case has beed updated for this.
|  Dropdown  |  `Dropdown` 配合 `Menu` 使用时，允许通过 `onClickMenuItem` 的返回值控制菜单点击后是否自动隐藏。   |     When `Dropdown` is used with `Menu`, user can control whether the menu will be hidden after clicking by the return value of `onClickMenuItem` .    | #61  |
> feat: Dropdown allows the return value of onClickMenuItem to determine whether to automatically hide the menu

- components/Typography/README.en-US.md
- components/Typography/README.zh-CN.md
- components/Typography/__test__/__snapshots__/demo.test.ts.snap
- components/Typography/base.tsx
- components/Typography/interface.tsx
- components/Typography/style/index.less
- components/Typography/utils.tsx
- stories/components/Typography.jsx
|-------------| ------------- | ------------- | -------------- |
| Typography |`Typography` 的 `Ellispsis` 支持 `cssEllipsis`属性，在简单场景下，默认使用 css 进行省略。|The `Ellispsis` of `Typography` supports the `cssEllipsis` property. In simple scenarios, css is used by default. | |
> feat: Typography support cssEllipsis in simple ellipsis scene.

- components/InputTag/README.en-US.md
- components/InputTag/README.zh-CN.md
- components/InputTag/__demo__/labelInValue.md
- components/InputTag/__demo__/render-tag.md
- components/InputTag/__demo__/save-on-blur.md
- components/InputTag/__demo__/validate.md
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/__test__/index.test.tsx
- components/InputTag/input-tag.tsx
- components/InputTag/interface.ts
Allow users to automatically save the input content when the InputTag is blur.
Add a new property `saveOnBlur`.
A new test case has beed added for it.
| InputTag | `InputTag` 新增 `saveOnBlur` 属性以支持在失焦时自动保存用户正在输入的内容。 | `InputTag` adds `saveOnBlur` property to support automatically saving what the user is typing when blur it. |  #144  |
> feat: InputTag add property saveOnBlur

- components/Card/__test__/__snapshots__/demo.test.ts.snap
- components/Tabs/README.en-US.md
- components/Tabs/README.zh-CN.md
- components/Tabs/__demo__/scrollPosition.md
- components/Tabs/__test__/__snapshots__/demo.test.ts.snap
- components/Tabs/__test__/__snapshots__/index.test.tsx.snap
- components/Tabs/interface.ts
- components/Tabs/tab-header/index.tsx
- components/Tabs/tabs.tsx
- stories/components/Tab.jsx
| Tabs  | `Tabs` 新增 `scrollAfterEdit` 属性，支持用户设置在 `Tabs` 增删后需不需要进行滚动位置调整 | `Tabs` adds the `scrollAfterEdit` property, which allows users to set whether to adjust the scroll position after adding or deleting `Tabs`|                #158 
| Tabs  | `Tabs` 新增 `scrollPosition` 属性，可设置选中 `Tab` 的滚动位置 |`Tabs` adds the `scrollPosition` property, which can set the scroll position of the selected `Tab`| #146
> feat: Tabs add the scrollAfterEdit and scrollPosition properties

- components/Form/__demo__/validateLevel.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/form.test.tsx
- components/Form/__test__/useform.test.tsx
- components/Form/__test__/validate.test.tsx
- components/Form/control.tsx
- components/Form/form-item.tsx
- components/Form/form-label.tsx
- components/Form/interface.tsx
- components/Form/store.tsx
- components/Form/style/status.less
- components/Form/utils.tsx
|    Form       |  `Form` 支持在 `rules` 中设置 `validateTrigger` 属性指定规则在特定事件触发时候执行。              |      `Form` support to set the `validateTrigger` property in `rules` to specify that the rule will be executed when a specific event is triggered.         |                 close #173  |
|    Form       |  `Form` 支持在 `rules` 中设置 `validateLevel` 属性指定规则校验失败时仅显示 `warning` 状态，不阻塞表单提交。              |      `Form` support setting the `validateLevel` property in `rules` to specify that only the `warning` status is displayed when the rule validation fails, and the form submission is not blocked.         |                |
> feat: Form supports validateTrigger and validateLevel

- components/Form/form-item.tsx
> fix: update form-item classname

- components/Avatar/README.en-US.md
- components/Avatar/README.zh-CN.md
- components/Avatar/interface.ts
Modify the Avatar.Group document,  I found the document description is wrong
Example: https://codesandbox.io/s/unruffled-feather-gd6x1?file=/src/App.js
> docs: Avatar.Group document

- components/Grid/__test__/index.test.tsx
- components/Grid/col.tsx
- components/Grid/context.ts
- components/Grid/interface.ts
- components/Grid/row.tsx
| Grid | `Grid.Row` 使用 context 传递 `gutter`，避免自定义 `Grid.Col` 时不能正确接收参数。 |`Grid.Row` uses context to pass `gutter` to `Grid.Col` to avoid incorrectly receiving parameters when customizing `Grid.Col`. | Close https://github.com/arco-design/arco-design/issues/221 |
> enhance: grid.row use context to pass gutter to grid.col

- components/DatePicker/__demo__/showtime.md
- components/DatePicker/__test__/range.test.tsx
- components/DatePicker/interface.tsx
- components/DatePicker/picker-range.tsx
- components/DatePicker/picker.tsx
| DatePicker | `DatePicker.RangePicker` 组件 `showTime.defaultValue` 支持传入 `number[] \| string[] \| Date[]`，避免出现 dayjs 实例不一致引发的报错。 |  The `DatePicker.RangePicker` component `showTime.defaultValue` supports passing in `number[] \| string[] \| Date[]` to avoid errors caused by inconsistent dayjs instances.| Close https://github.com/arco-design/arco-design/issues/212, Close: https://github.com/arco-design/arco-design/issues/213  |
> fix datepicker issue 212, 213

- site/package.json
- site/src/page.js
- site/src/pages/customer/index.tsx
- site/src/pages/home/sections/Resource/locale/en-US.ts
- site/src/pages/home/sections/Resource/locale/zh-CN.ts
- site/yarn.lock
1. Home Page Navbar versionList bugfix.
2. Dosc Page Footer add LarkGroup
> feat: update navbar, docs footer add lark group

- components/Dropdown/__demo__/right-click.md
- components/Image/__demo__/extra-actions.md
- components/Image/__demo__/preview-group.md
- components/Input/textarea.tsx
- components/Progress/__demo__/size.md
- components/Select/__demo__/custom-trigger.md
- components/Select/__demo__/virtual-list.md
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Table/table.tsx
- components/TreeSelect/__demo__/self-input.md
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/_class/VirtualList/index.tsx
- components/_util/hooks/useIsomorphicLayoutEffect.ts
- package.json
Close: https://github.com/arco-design/arco-design/issues/199
> enhance: remove ssr warnings

- .github/workflows/pr_check.yml
Some scenes currently test errors
Add the `build:cjs` step before `run test`
> fix: actions add build:cjs

- components/Avatar/group.tsx
- components/Avatar/style/index.less
- components/Avatar/style/token.less
- components/Link/style/token.less
- components/Radio/style/index.less
- components/Radio/style/token.less
- components/Tabs/style/index.less
- components/style/theme/css-variables.less
- components/style/theme/global.less
|        Avatar   |     修复 `Avatar.Group` 未设置 `size` 属性时，头像间距未设置的样式问题。          |      Fix the style problem that the spacing between avatars is not set when the `size` property is not set for the avatar group.         |                |
|        Tabs   |     修复 `Tabs` 组件 的 `card` 类型头部高度不对的问题。          |      Fix the problem that the head height of the `Tabs` component of the `card` type is incorrect.       |                |
> style: fix avatar group style

- components/Cascader/__demo__/onSearch.md
- components/Cascader/cascader.tsx
- components/Input/style/textarea.less
- components/Tree/README.zh-CN.md
- components/Tree/__template__/index.zh-CN.md
- components/Upload/trigger-node.tsx
|     Cascader      |     修复受控模式下 `cascader` 组件的 `value` 未改变，选项的选中状态仍然改变了的问题 。        |         Fix the problem that the value of the `cascader` component in the controlled mode is not changed, and the selected state of the option is still changed.      |    close #214             |
|     Upload      |     修复 `Upload` 组件在拖拽移出时，上传节点仍然显示高亮样式的 bug。        |     Fix the bug that the upload node still shows the highlighted style when the `Upload` component is dragged out.     |    close #210            |
> fix: Upload node still keep active style when dragleave & fix: Cascader options checked status

- components/Anchor/__test__/index.test.tsx
- components/Anchor/anchor.tsx
| Anchor | fix: 修复 `Anchor` 组件设置 `affix`时，滚动容器未传递到 `Affix` 组件上的bug | fix: Fix the bug that the scroll container is not passed to the `Affix` component when the `Anchor` component is set to `affix` |   Close #209   |
> fix: Anchor's scrollContainer should be added to Affix

- components/Input/input-element.tsx
- [ x ] Bug fix
事件绑定在icon上，hover时候点击边缘位置时，无法清空value。应绑定在icon外层的icon-hover的上
|      Input     |       把clear事件触发绑定在icon外层的icon-hover上        |               |                |
- [ x ] Test suite passes (`npm run test`)
- [ x ] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ x ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others should be submitted to `main` branch)
> fix: 事件绑定在icon上，hover时候点击边缘位置时，无法清空value。应绑定在icon外层的icon-hover的上

- components/Table/style/index.less
- site/src/pages/home/sections/Banner/style/content.module.less
| Table |修复 `Table` 组件复选框列在固定表头时没有对齐的样式问题。 |Fix the style problem that the checkbox column of the `Table` component is not aligned when the table header is fixed.| Close: https://github.com/arco-design/arco-design/issues/217 |
> style: Table operation cell padding when fixed header

- components/Form/__demo__/validateLevel.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/control.tsx
- components/Form/form-item.tsx
- components/Form/interface.tsx
- components/Form/store.tsx
> ts: modify form warnings ts

- components/Menu/style/index.less
| Menu | 修复 `Menu` 组件已选中菜单项中的 Icon 颜色变化没有过渡效果的问题。 |  Fix the problem that the color change of Icon in the selected menu item of the `Menu` component has no transition effect. |  Close #238    |
> style: Menu icon color transition of selected items

- components/Tabs/README.zh-CN.md
- components/Tabs/interface.ts
- components/Tabs/tab-header/index.tsx
> fix(docs): tabs `size` in docs and remove the `lodash` import; 

- components/Drawer/README.en-US.md
- components/Drawer/README.zh-CN.md
- components/Drawer/index.tsx
- components/Drawer/interface.ts
|    Drawer       |       `Drawer` 组件支持 `okButtonProps` 和 `cancelButtonProps` 属性。        |     The `Drawer` component supports the `okButtonProps` and `cancelButtonProps` properties.          |         close #216        |
> feat: drawer supports okButtonProps & cancelButtonProps

- components/Trigger/index.tsx
|    Trigger       |    优化 `Trigger` 组件计算子节点尺寸和位置的逻辑，避免重复计算。           |     Optimize the logic used by the `Trigger` component to calculate the size and position of child nodes to avoid double-counting          |   close #240               |
> enhancement: trigger computed children dom

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/TreeSelect/README.en-US.md
- components/TreeSelect/README.zh-CN.md
- components/_class/select-view.tsx
Select/TreeSelect/Cascader support customize icon of clear button.
| Select | `Select` 组件新增 `clearIcon` 属性用于自定义清除按钮图标。 |  `Select` adds the `clearIcon` property to customize the clear button icon.   |    Close #218       |
> feat: SelectView add new property clearIcon

- components/Steps/style/dot.less
|     Steps      |    修复 `Steps` 组件的标题和图标在垂直模式下没有对齐的问题           |       Fix the problem that the title and icon of the `Steps` component are not aligned in the vertical mode        |                |
> fix(steps): The step icon and title are not aligned vertically

- components/Grid/README.en-US.md
- components/Grid/README.zh-CN.md
- components/Grid/__demo__/flex.md
- components/Grid/__template__/index.en-US.md
- components/Grid/__template__/index.zh-CN.md
- components/Grid/__test__/__snapshots__/demo.test.ts.snap
- components/Grid/__test__/index.test.tsx
- components/Grid/col.tsx
- components/Grid/interface.ts
| Grid  | `Grid.Col` 组件增加 `flex` 属性。 | The `Grid.Col` component adds the `flex` property.  | Close: https://github.com/arco-design/arco-design/issues/243 |
> feat: Grid.Col add flex

- components/Tag/README.en-US.md
- components/Tag/README.zh-CN.md
- components/Tag/__demo__/bordered.md
- components/Tag/__test__/__snapshots__/demo.test.ts.snap
- components/Tag/index.tsx
- components/Tag/interface.ts
- components/Tag/style/index.less
- components/Tag/style/token.less
|     Tag      |       `Tag` 组件支持 `bordered` 属性        |    `Tag` supports `bordered` property.           |      close #228           |
> feat: tag supports bordered prop

- components/Trigger/index.tsx
This reverts commit e17506cefbc71ce4b5134e636846efd5348b14fd.
> Revert "enhancement: trigger computed children dom"

- components/Tag/__test__/__snapshots__/demo.test.ts.snap
- components/Upload/__test__/__snapshots__/demo.test.ts.snap
- components/Upload/trigger-node.tsx
> test: update snapshots & modify upload onDragFiles parameters

- components/List/index.tsx
| List | `List` 组件修复使用虚拟列表时 `scrollLoading` 失效的问题。 | `List` fixes the issue that `scrollLoading` fails when using virtual lists. |                |
> fix: List scrollLoading not works when it's virtual

- .github/workflows/build_size.yml
- .github/workflows/pr_check.yml
separately execute the packaging and testing pipeline
> ci: separation of pipeline packaging and testing

- components/Select/style/index.less
- components/Trigger/index.tsx
|  Trigger         |     修复 `Trigger` 组件触发方式为 `contextMenu` 时，点击触发节点，弹出层未隐藏的 bug。          |  Fix the bug that when the trigger mode of the `Trigger` component is `contextMenu`, the pop-up layer is not hidden when the trigger node is clicked.             |      close #284           |
| Select | 修复 `Select` 组件多选时，`prefix` 节点丢失`font-size` 样式的 bug。 | Fix the bug that the `prefix` node loses the style of `font-size` when the `Select` component is multi-selected.｜
> fix: trigger hide the popup layer when click

- components/Upload/__test__/drop.test.tsx
- components/Upload/trigger-node.tsx
|      Upload     |     修复 `Upload` 组件拖拽上传文件夹不生效的 bug。          |    Fix the bug that the upload folder does not take effect when dragging and dropping the upload component.           |                |
> fix: Upload directory not work when drop is true

- .browserslistrc
- package.json
- site/src/pages/customer/sections/Banner/style/text.module.less
- yarn.lock
Chore: add browserslistrc.
chrome 49
edge 16
firefox 31
safari 10
opera 36
> chore: add browserslistrc

- components/Anchor/style/index.less
- components/Upload/upload.tsx
- components/Upload/uploader.tsx
|        Upload   |  修复 `Upload` 组件设置 `customRequest` 是一个异步函数时，请求无法被终止的 bug 。           |            Fix the bug that the request cannot be terminated when the `CustomRequest` setting of the `Upload` component is an asynchronous function.   |    close #286             |
> fix: customeRequest can not be aborted

- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Table/style/index.less
- components/Table/tbody/td.tsx
- components/Tag/__demo__/close-async.md
- components/Tag/index.tsx
- site/docs/start.en-US.md
- site/docs/start.zh-CN.md
|  Table | 修复 `Table` 组件树形数据时，`column.render` 返回 `div` 会导致折行的问题。  |Fix the problem that table cell will break line when `Table` component is tree data and `column.render` returns `div`.| Close: https://github.com/arco-design/arco-design/issues/298 |
> style: Table indent cell style

- components/Table/__demo__/attribution.md
I checked `Header Fixed` at website [arco table props](https://arco.design/react/components/table#%E8%A1%A8%E6%A0%BC%E5%B1%9E%E6%80%A7), but there is no effect in addition to table header row width changes. So I suggest decreasing  `scroll.y` to `120`, it will make user see the effect clearly.
Decrease `Header Fixed` checked condition `Table`'s  `scroll.y` to 120.
> docs: fix table-'Header Fixed' no effect in most screens

- package.json
I search this package in npmjs.com, but the search result page can not jump directly to a Git repository
add bugs, homepage, repository property to the package.json 
> chore: add hompage, bugs, repository url to the package.json

- components/DatePicker/hooks/useCellClassName.ts
- components/DatePicker/picker-range.tsx
| DatePicker | `DatePicker.RangePicker` 组件选中交互优化。  | `DatePicker.RangePicker` component selected interactive optimization. | Close: https://github.com/arco-design/arco-design/issues/276 |
> enhance: DatePicker select range

- components/DatePicker/__demo__/control.md
- components/DatePicker/picker-range.tsx
- components/DatePicker/picker.tsx
- components/Upload/upload.tsx
| DatePicker | 修复 `DatePicker` 组件在受控模式下不触发 `onVisibleChange` 的 bug。 | Fix the bug that the `DatePicker` component does not trigger `onVisibleChange` in the controlled mode. | Close: https://github.com/arco-design/arco-design/issues/290 |
> fix: onVisibleChange not work when control mode

- components/locale/en-US.tsx
> fix: fix spelling error

- components/Statistic/__demo__/countdown.md
- components/Statistic/__test__/__snapshots__/demo.test.ts.snap
related issue [#315](https://github.com/arco-design/arco-design/issues/315)
|       no    |        no       |       no        |        no        |    no
> fix(doc): fix the statistic example page flashing

- components/InputTag/README.en-US.md
- components/InputTag/README.zh-CN.md
- components/InputTag/__demo__/draggable.md
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/input-tag.tsx
- components/InputTag/interface.ts
- components/InputTag/style/index.less
- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/Select/__demo__/darggable.md
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Select/select.tsx
- components/_class/Draggable/index.tsx
- components/_class/Draggable/interface.ts
- components/_class/Draggable/item.tsx
- components/_class/Draggable/style/index.less
- components/_class/select-view.tsx
- stories/components/Draggable.jsx
- stories/components/InputTag.jsx
- stories/components/Select.jsx
- stories/index.stories.js
Allow users to sort the selected values ​​of InputTag/Select by dragging.
New property `dragToSort` has been added for InputTag/Select.
| InputTag |`InputTag` 新增 `dragToSort` 属性以支持通过拖拽为已输入的值排序 。|`InputTag` adds `dragToSort` property to support sorting the entered value by dragging. |  Close #176   |
| Select |`Select` 新增 `dragToSort` 属性以支持通过拖拽为已输入的值排序 。|`Select` adds `dragToSort` property to support sorting the entered value by dragging. |  Close #176   |
> feat: InputTag enable user darg of its values

- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/InputNumber/index.tsx
- components/InputNumber/interface.ts
| InputNumber | `InputNumber` 允许通过属性传递所有的 `InputHTMLAttributes`。 |  `InputNumber` allows all `InputHTMLAttributes` to be passed through properties.   |   Close #318   |
> enhancement: InputNumber can receive all InputHTMLAttributes from its properties

- components/Typography/README.en-US.md
- components/Typography/README.zh-CN.md
- components/Typography/__test__/index.test.tsx
- components/Typography/base.tsx
- components/Typography/interface.tsx
|  Typography  | `Typography` 组件的 `onExpand` 回调参数新增 `event` 参数。  | The `event` parameter has been added to the `onExpand` callback parameter of the Typography` component. |  Close #317 |
> feat: typography onExpand params add click event

- components/Table/README.en-US.md
- components/Table/README.zh-CN.md
- components/Table/__test__/common/data.ts
- components/Table/__test__/expand.test.tsx
- components/Table/interface.tsx
- components/Table/tbody/tr.tsx
| Table | `Table` 组件新增参数 `expandProps.strictTreeData`。  |  `Table` add prop `expandProps.strictTreeData`. | Close: https://github.com/arco-design/arco-design/issues/299 |
> feat: add expandProps.strictTreeData

- components/Layout/__test__/__snapshots__/demo.test.ts.snap
- components/ResizeBox/README.en-US.md
- components/ResizeBox/README.zh-CN.md
- components/ResizeBox/__demo__/splitGroup.md
- components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap
- components/ResizeBox/__test__/__snapshots__/index.test.tsx.snap
- components/ResizeBox/__test__/group.test.tsx
- components/ResizeBox/__test__/index.test.tsx
- components/ResizeBox/index.tsx
- components/ResizeBox/interface.ts
- components/ResizeBox/resize-trigger.tsx
- components/ResizeBox/split-group.tsx
- components/ResizeBox/style/index.less
- components/ResizeBox/style/token.less
- components/Typography/README.en-US.md
- components/Typography/README.zh-CN.md
- stories/components/Resizebox.jsx
- stories/index.stories.js
类似功能：https://demos.telerik.com/kendo-ui/splitter/index
| Resizebox | `Resizebox` 新增 `SplitGroup` 子组件，支持分割多个面板及快速折叠功能 |`Resizebox` adds `SplitGroup` sub-component, supports splitting multiple panels and quick folding function  | Close #215  |
> feat: resizebox add a new sub-component `Resizebox.SplitGroup`

- stories/components/Alert.jsx
```shell
yarn run demo
```
storybook  Alert Demo error like this:
```js
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `unboundStoryFn`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `unboundStoryFn`.
at createFiberFromTypeAndProps (http://x.x.x.x/vendors~main.iframe.bundle.js:72165:21)
at createFiberFromElement (http://x.x.x.x/vendors~main.iframe.bundle.js:72188:15)
at reconcileSingleElement (http://x.x.x.x/vendors~main.iframe.bundle.js:62433:23)
at reconcileChildFibers (http://x.x.x.x/vendors~main.iframe.bundle.js:62493:35)
at reconcileChildren …
```
> chore: fix Alert demo error in storybook

- components/Upload/style/index.less
|      Upload     |        修复 `Upload` 组件在上传文件列表为空时存在外边距的样式问题       |    Fix the style problem of the margin when the upload file list is empty in the `Upload` component           |                |
> style: fix upload list margin

- components/Table/table.tsx
- stories/components/Table.jsx
| Table  | 修复 `Table` 当数据量变化时，当前页计算出错的 bug。| Fix the bug that the current page calculation error occurs when the amount of data in `Table` changes. |   Close  #304 |
> fix: Recalculate the current page number when the data length changes

- components/ConfigProvider/index.tsx
- components/Modal/confirm.tsx
- components/Modal/locale.tsx
- components/Modal/modal.tsx
When the modal visible value is true, the locale config does not work
related issue [#338](https://github.com/arco-design/arco-design/issues/338)
Use the locale value of ConfigProvider instead of retrieving it again in Modal
|     Modal      |     修复```Modal``` 组件在默认打开状态时国际化不起作用的问题          |     fix when ```Modal``` component  the visible is true, the locale does not work         |          [#338](https://github.com/arco-design/arco-design/issues/338)
> fix(modal): fix when the modal visible value is true,  locale config does not work

- components/Menu/README.en-US.md
- components/Menu/README.zh-CN.md
- components/Menu/__test__/index.test.tsx
- components/Menu/interface.tsx
- components/Menu/sub-menu/inline.tsx
| Menu | `Menu.SubMenu` 在非弹出模式下同样支持 `selectable` 属性。   | `Menu.SubMenu` also supports `selectable` property in non-popup mode.  | Close #345 |
> enhancement: SubMenu inline support selectable

- components/Button/style/index.less
- components/Card/style/index.less
- components/Carousel/style/index.less
- components/Radio/style/index.less
- components/Tabs/style/index.less
- components/Tag/style/index.less
- components/Tooltip/style/index.less
- components/style/theme/color/compiled-colors.less
- components/style/theme/color/css-variables.less
- components/style/theme/css-variables.less
> style: arco-theme-tag 

- components/Calendar/style/token.less
- components/Tag/style/token.less
- components/style/animation/slide.less
|        Tag   |      修复 `pinkpurple` 颜色 的 `Tag` 组件图标色样式不对的问题。         |  Fix the problem that the icon color style of the `Tag` component of the `pinkpurple` color is incorrect.             |                |
|        Trigger   |      修复 `Trigger` 组件在 `slideDynamicOrigin` 类型的动画效果丢失的问题。| Fix the issue that the animation effect of the `Trigger` component in the `slideDynamicOrigin` type is lost. | close: #366
> style(Tag): Fix pinkpurple icon & style(Trigger): fix slideDynamicOrigin animation 

- components/Button/__test__/__snapshots__/demo.test.ts.snap
- components/Divider/__test__/__snapshots__/demo.test.ts.snap
- components/Divider/index.tsx
- components/Divider/style/index.less
- components/Grid/__test__/__snapshots__/demo.test.ts.snap
- components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap
|     Divider      |      优化带有文字的 `Divider` 组件的样式实现         |  Optimize the style implementation of the `Divider` component with text             |       close: #374          |
> enhancement(divider): use flex to replace absolute style

- package.json
> chore: add compute-scroll-into-view to package dependencies

- components/Table/hooks/useStickyClassNames.ts
- components/Table/tbody/td.tsx
| Table |  修复 `Table` 组件在异步更新 `column.className` 时，类名有问题的 bug。   | Fix the bug that the className is incorrect when the `Table` component updates the `column.className` asynchronously. | Close: https://github.com/arco-design/arco-design/issues/392 |
> fix: Table column.className update

- components/Divider/style/index.less
|   Divider        |       修复 `Divider` 组件文字换行样式错误        |    Fix `Divider` component text wrapping style error           |                Close #397 |
> style: divider text wrap line

- components/Table/__demo__/table-edit.md
Unused constant: 'Option'.
Delete.
> docs: unused constant

- components/Image/image-preview.tsx
- stories/components/Image.jsx
| Image | 修复 `Image` 组件预览模式下部分全局配置丢失的bug  | Fix the bug that some global configuration were lost in the preview mode of the `Image` component  |  Close  #387   |
> fix: image preview configContext

- site/docs/designlab/use-theme-package.en-US.md
- site/docs/designlab/use-theme-package.zh-CN.md
The doc did not mention Vite. Also has some typos in package names. 
Fixed package names and added links in the doc.
> update config instruction for vite

- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/__template__/index.en-US.md
- components/Form/__template__/index.zh-CN.md
- components/Form/__test__/validate.test.tsx
- components/Form/control.tsx
- components/Form/form-item.tsx
- components/Form/form.tsx
- components/Form/interface.tsx
|    Form       |     `Form` 组件支持通过 `validateTrigger` 属性全局设置校验规则触发的时机          |  The `Form` component supports the global setting of the triggering timing of the verification rule through the `validateTrigger` property             |                Close #341 |
> feat(Form): supports validateTrigger props

- components/Button/style/token.less
| Button  | 修复 `Button` 组件在 `mini` 尺寸时图标没有完全垂直居中的问题。 | Fixed `Button` component icon not fully vertically centered at `mini` size.  | Close: https://github.com/arco-design/arco-design/issues/389 |
> style: Button mini size vertical-align

- components/Upload/README.en-US.md
- components/Upload/README.zh-CN.md
- components/Upload/__test__/apis.test.tsx
- components/Upload/interface.tsx
- components/Upload/upload.tsx
- components/Upload/uploader.tsx
…umber is exceeded
| Upload          |        `Upload` 组件的 `limit` 参数支持指定超出限制数量后禁用上传节点      |       The limit parameter of the `Upload` component supports specifying that the upload node is disabled after the limit number is exceeded        |    Close #365             |
> feat:   The limit parameter of the `Upload` component supports specifying that the upload node is disabled after the limit number is exceede

- components/locale/es-ES.tsx
A few fixes for Spainish i18n translations.
See this commit for details.
N/A
N/A
> fix: es translation

- components/Tabs/tab-header/index.tsx
- components/Tabs/utils.tsx
- stories/components/Tab.jsx
| Tabs | 修复`Tabs` 组件在子元素 `autofocus`情况下滚动出错的问题 | Fix the bug that the Tabs component scrolled incorrectly in the sub-element `autofocus` scene  |   Close: #422    |
> fix: tabs scroll position

- components/DatePicker/panels/month/index.tsx
- components/DatePicker/panels/year/index.tsx
| DatePicker |  修复 `DatePicker` 组件 `disabledDate` 在父面板不准确的 bug。  | Fixed a bug where the `disabledDate` of the `DatePicker` component was inaccurate in the parent panel.  | Close: https://github.com/arco-design/arco-design/issues/421  |
> fix: DatePicker disabledDate father panel

- components/Anchor/anchor.tsx
|   Anchor        |    修复 `Anchor` 组件在设置了 `scrollContainer` 时，点击锚点元素滚动位置不对的 bug。           |     Fix the bug that the scroll position of the clicked anchor element is wrong when the `Anchor` component is set with a `scrollContainer`.          |    Close #429             |
> fix: anchor scroll position error when scrollContainer is not window

- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/Table/__test__/__snapshots__/index.test.tsx.snap
- components/Table/__test__/pagination.test.tsx
- components/Table/table.tsx
[#433](https://github.com/arco-design/arco-design/issues/433)
|     ```Table```     |    如果表格没有数据，分页不应该展示 。       |  Pagination should not be displayed if the table has no data.            |   Close: https://github.com/arco-design/arco-design/issues/433         |
> fix(table): Pagination should not be displayed if the table has no data

- components/BackTop/__test__/__snapshots__/demo.test.ts.snap
- components/Calendar/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/__test__/__snapshots__/index.test.tsx.snap
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Input/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/__test__/__snapshots__/index.test.tsx.snap
- components/InputTag/input-tag.tsx
- components/Pagination/__test__/__snapshots__/demo.test.ts.snap
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Select/__test__/__snapshots__/index.test.tsx.snap
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/Trigger/__test__/__snapshots__/demo.test.ts.snap
- components/_class/select-view.tsx
|  Select   |  禁用浏览器对于 `Select` 输入框的自动填充。   |  Disable browser autocomplete for `Select`.   |   Close: #431    |
> enhancement: turn off autocomplete for Select & InputTag

- components/Dropdown/index.tsx
| Dropdown | `Dropdown` 为下拉框节点补充 `arco-dropdown` 的类名。 | `Dropdown` supplements the class name of `arco-dropdown` for dropdown box nodes. |    Close: #423    |
> enhancement: Dropdown add className arco-dropdown for popup element

- components/Select/option.tsx
- components/Select/select.tsx
> enhancement: Select.Option without children

- components/Skeleton/interface.tsx
- [ x ] Bug fix
Skeleton的text属性应该接收`(number|string)[]`的类型而不是number[]|string[]
|     Skeleton      |      修复`Skeleton` `text`属性类型不正确的问题        |     fix `Skeleton` `text` type        |                |
- [ x ] Test suite passes (`npm run test`)
- [ x ] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ x ] Changes are submitted to the appropriate branch (e.g. features should be submitted to `feature` branch and others should be submitted to `main` branch)
> fix: correct the type of SkeletonTextProps

- components/Upload/list/textItem.tsx
| Upload           |  修复上传组件文件列表项移除按钮的边缘点击不可用的问题             |    Fixed the edge click of the remove button not working in the Upload component upload list           |    Fix #456             |
> fix(Upload): expand the clickable area of the remove button

- components/Button/style/index.less
If the button content in the Button Group is empty, styling errors occur
|     Button      |  修复 `Button` 内容为空时垂直方向无法对齐的问题。      |      Fix the incorrectly style when  `Button` content is empty.        |        Close #467    |
> fix(button): fix incorrectly style when button content is empty

- components/Table/table.tsx
| Table |修复 `Table` 组件 `size` 没有作用到分页的 bug。| Fixed the bug that `Table` component `size` did not work on `Pagination`.  | Close: https://github.com/arco-design/arco-design/issues/474 |
> fix: Table pagination size not work

- components/Upload/__test__/__snapshots__/demo.test.ts.snap
- components/Upload/uploader.tsx
修复uploader组件的webkitdirectory属性的类型
根据MDN文档 https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLInputElement/webkitdirectory
webkitdirectory是boolean类型
|     Uploader      |      修复uploader组件的`webkitdirectory`属性的类型         |      Fix the type of the `webkitdirectory` attribute of the uploader component         |                |
> fix: uploader webkitdirectory type

- components/Timeline/style/horizontal.less
> style: timeline token

- components/DatePicker/__demo__/shortcuts-placement-left.md
> docs(date-picker): fix mistake in demo `custom shortcus position`

- components/Table/__demo__/expandable.md
- components/Table/hooks/useExpand.tsx
| Table |  优化 `Table` 组件 `expandedRowRender` 会执行多次导致卡顿的问题。 | Optimize the `Table` component `expandedRowRender` to cause the problem of freezing.|  Close: https://github.com/arco-design/arco-design/issues/453   |
> enhance: Table expandedRowRender exec multi times

- components/Table/__demo__/virtualized.md
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Table/hooks/useRowSelection.tsx
- components/Table/thead/index.tsx
| Table | 优化 `Table` 在开启 `virtualized` 之后，大于 10000 条数据时全选会卡的性能问题。 | Optimized `Table` performance problem when selecting all data is larger than 10000 after enabling `virtualized`. | Close: https://github.com/arco-design/arco-design/issues/462 |
> enhance: Table virtualized optimization

- components/Grid/col.tsx
- components/Grid/style/col.less
|  Grid  | `Grid` 支持设置 `span` 为 0。  | `Grid` supports setting `span` to 0. |   Close: #458  |
> enhancement: Grid.Col support span 0

- components/Pagination/style/index.less
- components/Tabs/hook/useHeaderScroll.ts
> enhance: touchstart listener add passive flag

- components/Select/__test__/index.test.tsx
- components/Select/select.tsx
The ```allowCreate``` property will not working,  when set ```allowCreate``` and ```tokenSeparators```  together
Always  ```allowCreate``` first
|     Select      |   `Select` 修复 `allowCreate` 为 `false` 时，自动分词引入了新选项的问题。    |    `Select` fixes an issue where automatic word segmentation introduced new options when `allowCreate` was `false`.   |    Close: #463   |
> fix(select): fix allowCreate and tokenSeparators property is conflict

- components/Tag/__demo__/close-async.md
| Tag | 修正 Tag 组件文档中的拼写错误 | Fix spelling errors in Tag component documentation |                |
> docs: correct spelling mistake in tag

- components/Upload/uploader.tsx
|     Upload      |       修复 `Upload` 组件触发两次 `onClick` 的问题         |     Fixed `Upload` component triggering `onClick` twice          |       close #489          |
> fix: 修复upload组件触发onClick事件两次的问题

- components/Tree/__test__/index.test.tsx
- components/Tree/context.tsx
- components/Tree/index.tsx
- components/Tree/interface.ts
- components/Tree/node.tsx
|     Tree      |    `Tree` 组件支持通过 `expandOnClick` 属性设置点击节点时展开子节点         |       The `Tree` component supports expanding child nodes when a node is clicked via the `expandOnClick` property        |          close #426      |
> feat: Tree supports actionOnClick

- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/interface.tsx
- package.json
- site/docs/question.en-US.md
- site/docs/question.zh-CN.md
- yarn.lock
|    Common       |  升级 `b-validate` 版本以支持 `Form` 在 `validator` 中传入 `ReactNode`  |       Upgrade `b-validate` version to support `Form` passing `ReactNode` in `validator`        |     close #502            |
> feat: 升级 b-validate 版本以支持 Form 在callback中传入ReactNode

- components/Table/thead/column.tsx
| Table |修复 `Table` 组件 `onDropdownVisibleChange` 在点击确定按钮时不触发的 bug。 | Fix the bug that `Table` component `onDropdownVisibleChange` does not trigger when the OK button is clicked. | Close: https://github.com/arco-design/arco-design/issues/497  |
> fix: Table filter onFilterDropdownVisibleChange

- components/Cascader/base/node.ts
- components/Cascader/base/store.ts
- components/Cascader/cascader.tsx
- components/Cascader/panel/list.tsx
- components/Cascader/panel/option.tsx
- components/Cascader/util.tsx
- stories/components/Cascader.jsx
|    Cascader       |    优化 `Cascader` 组件大数据下多选时候选中操作卡顿的问题。           |   Optimized the problem of stuck operation when selecting multiple selections under the big data of the `Cascader` component.            |   Close #208              |
> enhancement: cascader render logic

- components/Input/input-element.tsx
| Input |   修复 `Input` 组件在 Firefox 中输入中文会连续触发两次 `onChange` 的 bug。  |   Fixed the bug that the `Input` component would trigger `onChange` twice in a row when entering Chinese in Firefox.    |  Close: #520 |
> fix: Input will trigger onChange twice when input Chinese in Firefox

- components/Statistic/index.tsx
|     Statistic      |      修复 `Statistic` 组件 `precision=0` 不生效的 问题         |    Fix `Statistic` component `precision=0` does not take effect           |     close #529            |
> fix(Statistic): precison=0 not work

- components/TreeSelect/README.en-US.md
- components/TreeSelect/README.zh-CN.md
- components/TreeSelect/__test__/index.test.tsx
- components/TreeSelect/hook/useStateValue.ts
- components/TreeSelect/interface.ts
- components/TreeSelect/tree-list.tsx
- components/TreeSelect/tree-select.tsx
|  TreeSelect         |    `TreeSelect` 的 `onChange` 函数新增节点信息参数           |    Added node information parameter to `onChange` function of `TreeSelect`           |  close #514               |
> feat(TreeSelect): onChange supports extra params

- components/Upload/trigger-node.tsx
- components/Upload/upload.tsx
|      Upload     |  优化照片墙类型的 `Upload` 组件 `tip` 文本的渲染位置            |      Optimize the rendering position of the `tip` text of the `Upload` component of the photo wall type         |      close #492           |
> fix: upload tip position when listtype=card

- components/Radio/group.tsx
- components/Radio/interface.ts
- components/Radio/radio.tsx
> enhancement: allow user to visit RadioGroupContext

- components/Tree/README.en-US.md
- components/Tree/README.zh-CN.md
- site/docs/version_v2.en-US.md
- site/docs/version_v2.zh-CN.md
Irregular pr content leads to missing changelog information
Complement and improve the changelog documentation
> docs: changelog

- components/Cascader/cascader.tsx
|    Cascader       |  修复 `Cascader` 组件多选情况下出现选中状态渲染出错的问题。              |      Fixed the issue that the selected state rendering error occurs when the `Cascader` component is multi-selected.         |       Close #538         |
> fix: cascader checkbox status error

- components/InputTag/__demo__/draggable.md
- components/Typography/utils.tsx
- stories/components/Typography.jsx
| Typography  |  降低 `Typography` 组件折叠计算后，镜像 `dom` 对自动化测试的影响。| Reduce the impact of the mirror `dom` on automated tests after `Typography` folding calculation |   Close: #542  |
> enhancement(Typography): Typography mirrorElement final performance

- CONTRIBUTING.md
- CONTRIBUTING.zh-CN.md
1. New contributors may get confused on how to preview locally modified components in browser.
2. Contributors may have problem running the test suite on their personal computer
1. Added instruction about the command to start Storybook
2. Added note about alternative approach to run the test suite (using Github Actions in a personal fork)
N/A
N/A
> doc: Enhance Contributor Guide

- components/Tooltip/__test__/index.test.tsx
- components/Tooltip/index.tsx
|   Tooltip        |      `Tooltip` content 值是 false 时不显示弹窗         |     ` Tooltip ` content value is false does not display the popup          |       Close: [#571](https://github.com/arco-design/arco-design/issues/571)         |
> fix(tooltip): does not show tooltip when content is false

- components/Form/useForm.ts
When I looked at the source code of useForm, I found a branching logic problem, I need you to confirm if this is a bug
|       Form    |      修复 `Form.useForm` 方法传入 `form` 参数不生效的 bug。         |     Fixed the bug that the `form` parameter passed to the `Form.useForm` method did not take effect.|                |
> fix(useForm): fix branch logic

- components/InputTag/style/index.less
|  InputTag  |  InputTag less选择器语法错误  | InputTag Less selector syntax error |   Close: #570    |
> fix: inputTag less selector error

- components/Form/store.tsx
> fix(Form): word spelling, Registed to Registered

- components/Slider/README.en-US.md
- components/Slider/README.zh-CN.md
- components/Slider/__demo__/interval.md
- components/Slider/__test__/__snapshots__/demo.test.ts.snap
- components/Slider/dots.tsx
- components/Slider/hooks/useInterval.ts
- components/Slider/index.tsx
- components/Slider/interface.tsx
- components/Slider/marks.tsx
- components/Slider/ticks.tsx
- components/Slider/utils.ts
|   Slider  | Slider 支持按区间分段设置宽度和步长 | `Slider` supports setting width and step size by interval segment |             |
> feat(Slider): slider supports segment interval configuration

- components/Calendar/style/index.less
The month width of calendar component becomes larger in year mode
change `box-sizing: content-box` to `box-sizing: border-box`
|      Calendar     |       修复 `Calendar` 组件年模式下选中当天使月块宽度变大的样式问题       |    Fix the style issue that the width of the month block becomes larger when the year mode of the `Calendar` component is selected           |                |
> fix: calendar today outline

- components/Image/__test__/preview.test.tsx
- components/Image/image-preview.tsx
- components/Image/image.tsx
- components/Image/interface.ts
- components/Image/utils/getScale.ts
- stories/components/Image.jsx
| Image  | `Image` 组件 新增 `index` 参数，表示预览时的索引，在复杂的多图预览场景下可指定，保证预览顺序一致 | Image component Added `index` parameter, which indicates the index during preview, which can be specified in complex multi-image preview scenarios to ensure consistent preview order | Close: #550 |
| Image  | `Image.Preview` 组件 新增 `scales` 参数，支持自定义图片预览缩放百分比 |`Image.Preview` component Added `scales` parameter to support custom image preview zoom percentage| Close: #517  |
> feat(Image): support users to manually pass in the preview index

- components/Tree/index.tsx
- components/Tree/interface.ts
- components/Tree/node-list.tsx
- components/TreeSelect/tree-list.tsx
- components/TreeSelect/tree-select.tsx
|      TreeSelect     |  修复 `TreeSelect` 组件在扩展下拉菜单中的输入框无法被聚焦的问题。             |      Fixed the problem that the input box of the `TreeSelect` component in the extension drop-down menu could not be focused.         |    Close #597             |
> fix[tree-select]: input can not be focused

- components/Transfer/__test__/index.test.tsx
- components/Transfer/index.tsx
- components/Transfer/interface.tsx
- components/Transfer/list.tsx
- stories/components/Transfer.jsx
…check all
| `Transfer`  |  `Transfer` 组件在全选/反选时，仅对过滤后的项目进行操作。     |   When the `Transfer` component selects/unselects all, it only operates on the filtered items.     |        Close: #595     |
> enhancement: Transfer shound only handle filtered items when check/uncheck all

- components/Tree/README.en-US.md
- components/Tree/README.zh-CN.md
- components/Tree/index.tsx
- components/Tree/interface.ts
|       Tree    |  `Tree` 组件的 `allowDrop` 回调参数支持 `dragNode`              |      `Tree` component's `allowDrop` callback parameter supports `dragNode`         |                |
> feat(tree): allowDrop supports dragNode

- components/Transfer/list.tsx
| Before | After |
:-------------------------:|:-------------------------:
| ![Kapture 2022-03-08 at 13 26 40](https://user-images.githubusercontent.com/56376387/157172104-abfa5988-dcb0-4b0f-9e8b-7a76b1f43081.gif) | ![Kapture 2022-03-08 at 13 28 41](https://user-images.githubusercontent.com/56376387/157172292-cf823825-a210-4495-bffc-15392aa6c0de.gif) |
|     Transfer      |       `Transfer` 组件在清空时，仅对过滤后的项目进行操作。        |        When the `Transfer` component clears all, it only operates on the filtered items.       |                |
> enhancement(Transfer): Transfer shound only clear filtered items when clear all

- CONTRIBUTING.md
- CONTRIBUTING.zh-CN.md
- package.json
贡献指南中 `yarn test --watch TestName`  会报错 ERROR: Invalid Option: --watch。经过飞书群讨论，在 package.json 中 增加 `test:watch`，并更新了贡献者指南。
增加以下script，其中增加了`collectCoverage=false`选项以跳过`collect coverage on untested code` 步骤，减少运行时间。
```
"test:watch": "arco-scripts test:client --silent=false --collectCoverage=false --watch"
```
在本地对新增 script 进行了测试。
N/A
> Added test:watch and updated Contributor Guide

- components/DatePicker/picker-range.tsx
| DatePicker | `DatePicker` 组件在选择日期的时候不再进行面板的跳动。 | The `DatePicker` component no longer jumps the panel when picking a date.   | Close: #625  |
> enhance: DatePicker page show dates not change when select

- components/Button/index.tsx
The Button component uses createRef to cause the Effect Hook to be executed every time it is rendered
change createRef to useRef and fix deps arrays
|      change Button component useEffect dependency array  to fix  Effect Hook  executed every time |     改变Button组件Effect依赖数组修复Effect每次渲染都运行的问题        |               |                |
> fix: Button useEffect deps

- components/InputTag/input-tag.tsx
- components/_class/select-view.tsx
|  Select  | 修复 `Select` 多选时 Tag 动画失效的 bug。 |  Fix the bug that the Tag animation fails when `Select` is multiple mode. |  Close #622      |
|  Select  | 修复 `Select` 设置 `maxTagCount` 时按下 `Backspace` 键时未按正确顺序删除选项的 bug。 |  Fix the bug that the options of `Select` with `maxTagCount` are not unchecked in the correct order when press `Backspace`. |     |
> fix: Select tag animation not works

- components/DatePicker/__test__/range.test.tsx
- components/DatePicker/picker-range.tsx
|  DatePicker |   修复 `DatePicker` 组件  `separator` 参数不生效的问题。  | Fixed the issue that the `separator` parameter of the `DatePicker` component did not take effect.  | Close: https://github.com/arco-design/arco-design/issues/638   |
> fix: DatePicker.RangePicker separator not work

- components/Table/style/index.less
|  Table  |  修复 `Table` 组件开启 `virtualized` 之后 `column.align` 不生效的 bug。   | Fix the bug that `column.align` does not take effect when `virtualized` is enabled in `Table` component. |    Close: https://github.com/arco-design/arco-design/issues/626    |
> fix: Table virtualized column align right not work

- components/Form/form-provider.tsx
|      Form     |   修复 ·Form.Provider· 导致控制台 warning 的 bug            |    Fix a bug where form.provider causes console warning           |   close #643              |
> fix:  form.provider causes console warning

- site/docs/start.en-US.md
- site/docs/start.zh-CN.md
> docs: update the "load on demend" section

- components/Table/style/index.less
|   Table  |  修复 `Table` 组件 `expandProps.width` 设置小于 40 不生效的问题。    |  Fix `Table` component set `expandProps.width` is not work when less than 40. |  Close: https://github.com/arco-design/arco-design/issues/653  |
> style: Table expand and selection col remove min and max width

- package.json
> Add unpkg entry

- components/Tooltip/index.tsx
Accessibility:
Tooltip add `role="tooltip"`
> enhance: Tooltip add role="tooltip"

- components/Alert/__test__/__snapshots__/demo.test.ts.snap
- components/Alert/__test__/__snapshots__/index.test.tsx.snap
- components/Alert/index.tsx
- components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
- components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
Accessibility:
Alert add role="alert"
> enhance: Alert add role="alert"

- .github/PULL_REQUEST_TEMPLATE.md
Change pull-request template, modify Performance improvement to Enhancement
> ci(pull-request): change template

- components/Image/__demo__/basic.md
- components/Image/__demo__/caption.md
- components/Image/__demo__/custom-preview-actions.md
- components/Image/__demo__/error.md
- components/Image/__demo__/extra-actions.md
- components/Image/__demo__/loader.md
- components/Image/__demo__/preview-get-popup-container.md
- components/Image/__demo__/preview-group.md
- components/Image/__demo__/progressive-loader.md
- components/Image/__test__/__snapshots__/demo.test.ts.snap
- components/Image/image.tsx
- components/Image/interface.ts
Accessibility:
Image add `alt`
> enhance: Image demos add alt

- components/DatePicker/__demo__/disabled-date.md
- components/DatePicker/__test__/panel.test.tsx
- components/DatePicker/panels/body.tsx
- components/DatePicker/panels/date/index.tsx
- components/DatePicker/panels/month/index.tsx
- components/DatePicker/panels/quarter/index.tsx
- components/DatePicker/panels/year/index.tsx
- components/DatePicker/util.ts
| DatePicker  |修复 `DatePicker` 组件 `disabledDate` 在快捷选择面板边界不正确的问题。  |  Fixed the `disabledDate` of the `DatePicker` component being incorrect at the border of the quick selection panel.  | Close: https://github.com/arco-design/arco-design/issues/421  |
> fix: DatePicker disabledDate #421

- components/Input/style/index.less
| Input  |  修复在特定场景下 Input 的清除按钮无法隐藏的bug | Fixed the bug that the clear button of Input could not be hidden in certain scenarios |  Closed: #665  |
> style: input clear icon disply

- components/Typography/README.en-US.md
- components/Typography/README.zh-CN.md
- components/Typography/base.tsx
- components/Typography/interface.tsx
- components/Typography/operations.tsx
|  Typography |  Typography 的 `copyable` 和 `editable` 对应点击回调暴露 `event` 参数。| Typography's `copyable` and `editable` expose the `event` parameter corresponding to the click callback.  |  Close: #648  |
> feat: typography click callback add event params

- components/List/index.tsx
- components/Spin/README.en-US.md
- components/Spin/README.zh-CN.md
- components/Spin/interface.ts
|   List    |  修复 `List` 组件栅格布局下 `render` 方法的 `index` 参数错误的 bug。       |    Fixed the bug that the `index` parameter of the `render` method under the grid layout of the `List` component was incorrect.    |   Close #662    |
> fix: List render's parameter:index has a wrong value when grid is true

- components/Popconfirm/README.en-US.md
- components/Popconfirm/README.zh-CN.md
- components/Popconfirm/interface.ts
`Popconfirm` 组件支持[异步关闭](https://arco.design/react/components/popconfirm#%E5%BC%82%E6%AD%A5%E5%85%B3%E9%97%AD)，但是在类型定义中 `onOk` 函数并不支持传入返回 Promise 的函数。
仿照 `Modal` 组件中 `onOk` 函数的类型定义，增加 Promise<any> 的返回值。
|    Popconfirm       |      `Popconfirm` 组件的 `onOk` 参数支持传入返回 Promise 的函数         |      `Popconfirm`'s `onOk` attribute accepts functions that will return Promise         |                |
> fix(Popconfirm): onOk supports functions with promise as return type

- components/style/animation/zoom.less
Close: https://github.com/arco-design/arco-design/issues/591
> style: zoom.less add import default theme

- components/Slider/__test__/__snapshots__/demo.test.ts.snap
- components/Slider/hooks/useInterval.ts
- components/Slider/hooks/useLegalValue.ts
- components/Slider/index.tsx
- stories/components/Slider.jsx
|  Slider  |  修复 `Slider` 的步长设置为小数时计算出错的 bug  |  Fix the bug of calculation error when the step size of `Slider` is set to decimal  |     Close: #654    |
|  Slider  |  修复 `Slider` 点击非滑动轴区域控制台报错的 bug |  Fix the bug of `Slider` clicking on the non-sliding axis area console to report an error  |   |
> fix: slider对于小数step的支持

- components/Slider/__test__/index.test.tsx
> test: add slider test about interval

- components/AutoComplete/README.en-US.md
- components/AutoComplete/README.zh-CN.md
- components/AutoComplete/index.tsx
- components/AutoComplete/interface.ts
- components/List/__test__/index.test.tsx
- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/Select/__test__/index.test.tsx
- components/Select/interface.tsx
- components/Select/select.tsx
- components/TreeSelect/README.en-US.md
- components/TreeSelect/README.zh-CN.md
- components/TreeSelect/interface.ts
- components/TreeSelect/tree-select.tsx
- scripts/jest.config.js
…r-function
|  Select    | `Select` 组件 `triggerElement` 属性允许传入函数以自定义组件触发节点。  | `Select` component's `triggerElement` property allows passing in a function to customize the component trigger node. |       Close #641       |
|  TreeSelect    | `TreeSelect` 组件 `triggerElement` 属性允许传入函数以自定义组件触发节点。  | `TreeSelect` component's `triggerElement` property allows passing in a function to customize the component trigger node. |       Close #641       |
| AutoComplete    | `AutoComplete` 组件 `triggerElement` 属性允许传入函数以自定义组件触发节点。  | `AutoComplete` component's `triggerElement` property allows passing in a function to customize the component trigger node. |       Close #641       |
> feat: [Select, TreeSelect, AutoComplete] triggerElement support render-function

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Cascader/__demo__/multiple.md
- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/__test__/index.test.tsx
- components/Cascader/base/node.ts
- components/Cascader/base/store.ts
- components/Cascader/cascader.tsx
- components/Cascader/interface.ts
- components/Cascader/util.tsx
|   Cascader        |     `Cascader` 组件支持通过  `checkedStrategy` 属性设置多选时数据的回显方式        |     The `Cascader` component supports setting the echo mode of data when multiple selections are set through the `checkedStrategy` property          |  close #619               |
> feat: cascader supports checkedStrategy

- components/Table/style/index.less
| Table |  修复 `Table` 组件开启虚拟列表时复选框列宽度异常的问题。  |  Fix the problem that the checkbox column width is abnormal when the `Table` component enable `virtualized`.  | Close: https://github.com/arco-design/arco-design/issues/695|
> fix: issue #695

- components/Message/__test__/__snapshots__/index.test.tsx.snap
- components/Notification/__test__/__snapshots__/index.test.tsx.snap
- components/_class/notice.tsx
Accessibility:
Message and Notification add `role="alert"`.
> Accessibility message

- site/src/page.js
- site/src/widget/ThemeBox/index.tsx
Accessibility:
Document some buttons add `aria-label`.
> enhance: Docs page some button add aria-label

- components/Timeline/__test__/__snapshots__/demo.test.ts.snap
- components/Timeline/__test__/__snapshots__/index.test.tsx.snap
- components/Timeline/item.tsx
- components/Timeline/timeline.tsx
Accessibility:
Timeline set `role="list"` and `role="listitem"`.
> enhance: timeline add role=list

- components/Progress/__test__/__snapshots__/demo.test.ts.snap
- components/Progress/__test__/__snapshots__/index.test.tsx.snap
- components/Progress/circle-progress.tsx
- components/Progress/line-progess.tsx
- components/Progress/steps-progress.tsx
- components/Upload/__test__/__snapshots__/demo.test.ts.snap
Accessibility:
Progress add `role=progressbar` & aria properties
> enhance: Progress add role=progressbar

- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/Modal/modal.tsx
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Tag/__test__/__snapshots__/demo.test.ts.snap
- components/Tag/index.tsx
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/Trigger/__test__/__snapshots__/demo.test.ts.snap
Accessibility:
Tag close icon add `aria-label` and `role`.
> enhance: Tag and Modal close button add role and aria-label

- components/Modal/modal.tsx
Accessibility:
Modal add `aria-labelledby` and mask add `aria-hidden`.
> enhance: Modal add aria-labelledby

- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/List/__test__/__snapshots__/demo.test.ts.snap
- components/Pagination/__test__/__snapshots__/demo.test.ts.snap
- components/Pagination/__test__/__snapshots__/index.test.tsx.snap
- components/Pagination/page-item.tsx
- components/Pagination/page-options.tsx
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Transfer/__test__/__snapshots__/demo.test.ts.snap
- components/locale/de-DE.tsx
- components/locale/en-US.tsx
- components/locale/es-ES.tsx
- components/locale/fr-FR.tsx
- components/locale/id-ID.tsx
- components/locale/it-IT.tsx
- components/locale/ja-JP.tsx
- components/locale/ko-KR.tsx
- components/locale/th-TH.tsx
- components/locale/zh-CN.tsx
- components/locale/zh-HK.tsx
- components/locale/zh-TW.tsx
Accessibility:
Pagination step button `aria-label`.
> enhance: Pagination step button add aria-label

- components/Form/__test__/validate.test.tsx
- components/Form/form-item.tsx
Accessibility:
Form valiateMessage add role="alert"
> enhance: Form add role=alert

- components/Breadcrumb/__test__/__snapshots__/demo.test.ts.snap
- components/Breadcrumb/__test__/__snapshots__/index.test.tsx.snap
- components/Breadcrumb/index.tsx
- components/Breadcrumb/item.tsx
- components/Layout/__test__/__snapshots__/demo.test.ts.snap
- components/PageHeader/__test__/__snapshots__/demo.test.ts.snap
Add `role` `aria-label` `aria-hidden` for Breadcrumb and its items.
> enhancement: Aria for Breadcrumb

- components/Transfer/__test__/__snapshots__/demo.test.ts.snap
- components/Transfer/__test__/__snapshots__/index.test.tsx.snap
- components/Transfer/index.tsx
Add `aria-label` for Transfer's operation buttons.
Related: #160
> enhancement: Transfer add aria-label

- components/Transfer/__test__/__snapshots__/demo.test.ts.snap
- components/Tree/__test__/__snapshots__/demo.test.ts.snap
- components/Tree/__test__/__snapshots__/index.test.tsx.snap
- components/Tree/animation.tsx
- components/Tree/index.tsx
- components/Tree/node-list.tsx
- components/Tree/node.tsx
Aria improvement.
tree add role & aria properties
Related: #160
> enhance: Tree add role & aria properties

- components/Cascader/panel/list.tsx
- components/Cascader/panel/search-panel.tsx
Accessibility:
cascader add aria properties
> enhance: cascader add aria properties

- components/Badge/__test__/__snapshots__/demo.test.ts.snap
- components/Card/__test__/__snapshots__/demo.test.ts.snap
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Skeleton/__test__/__snapshots__/demo.test.ts.snap
- components/Slider/__test__/__snapshots__/demo.test.ts.snap
- components/Space/__test__/__snapshots__/demo.test.ts.snap
- components/Statistic/__test__/__snapshots__/demo.test.ts.snap
- components/Switch/__test__/__snapshots__/demo.test.ts.snap
- components/Switch/__test__/__snapshots__/index.test.tsx.snap
- components/Switch/index.tsx
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Tag/__test__/__snapshots__/demo.test.ts.snap
- components/Timeline/__test__/__snapshots__/demo.test.ts.snap
- components/Tooltip/__test__/__snapshots__/demo.test.ts.snap
- components/Tree/__test__/__snapshots__/demo.test.ts.snap
- components/Typography/__test__/__snapshots__/demo.test.ts.snap
Accessibility:
`Switch` add `aria` and `role`.
> enhance: switch add role and aria properties

- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Input/__test__/__snapshots__/demo.test.ts.snap
- components/Input/input-element.tsx
- components/InputNumber/__test__/__snapshots__/demo.test.ts.snap
- components/InputNumber/__test__/__snapshots__/index.test.tsx.snap
- components/InputNumber/index.tsx
- components/Slider/__test__/__snapshots__/demo.test.ts.snap
Accessibility:
InputNumber add role and aria properties 
input add aria-invalid properties 
Related: #160
> enhance: input-number add role and aria properties & input add aria-invalid properties 

- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Input/__test__/__snapshots__/demo.test.ts.snap
- components/Menu/__test__/__snapshots__/demo.test.ts.snap
- components/Progress/__test__/__snapshots__/demo.test.ts.snap
- components/Progress/__test__/__snapshots__/index.test.tsx.snap
- components/Progress/circle-progress.tsx
- components/Progress/line-progess.tsx
- components/Progress/steps-progress.tsx
- components/Slider/__test__/__snapshots__/demo.test.ts.snap
- components/Slider/__test__/__snapshots__/index.test.tsx.snap
- components/Slider/button.tsx
- components/Slider/index.tsx
- components/Slider/marks.tsx
- components/Upload/__test__/__snapshots__/demo.test.ts.snap
Slider add `role` & aria properties
> enhance: Slider add role & aria properties

- components/Layout/__test__/__snapshots__/demo.test.ts.snap
- components/Menu/__test__/__snapshots__/demo.test.ts.snap
- components/Menu/__test__/__snapshots__/index.test.tsx.snap
- components/Menu/context.ts
- components/Menu/index.tsx
- components/Menu/interface.tsx
- components/Menu/item.tsx
- components/Menu/sub-menu/inline.tsx
- components/Menu/sub-menu/pop.tsx
* TS interface change: Allow pass html attributes to `Menu`;
* Add `role` `aria-expanded` `aria-controls` `aria-haspopup` for `Menu` and `Menu.SubMenu`;
* Add `role` for `Menu.Item`.
> enhance: Aria for Menu

- components/Button/__test__/__snapshots__/demo.test.ts.snap
- components/Carousel/__test__/__snapshots__/demo.test.ts.snap
- components/Carousel/index.tsx
- components/Checkbox/__test__/__snapshots__/demo.test.ts.snap
- components/Collapse/__test__/__snapshots__/demo.test.ts.snap
- components/Collapse/item.tsx
- components/Comment/__test__/__snapshots__/demo.test.ts.snap
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/Divider/__test__/__snapshots__/demo.test.ts.snap
- components/Divider/__test__/__snapshots__/index.test.tsx.snap
- components/Divider/index.tsx
- components/Grid/__test__/__snapshots__/demo.test.ts.snap
- components/List/__test__/__snapshots__/demo.test.ts.snap
- components/List/__test__/__snapshots__/index.test.tsx.snap
- components/List/index.tsx
- components/List/item.tsx
- components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap
- components/Space/__test__/__snapshots__/demo.test.ts.snap
- components/Steps/__test__/__snapshots__/demo.test.ts.snap
- components/Transfer/__test__/__snapshots__/demo.test.ts.snap
- components/Transfer/__test__/__snapshots__/index.test.tsx.snap
Accessibility:
* Carousel: add `aria-hidden` for children.
* Collapse: add `role` `aria-disabled` `aria-expanded` for Collapse header.
* Divider: add `role`.
* List:  add `role` for list and list item.
> enhancement: ARIA improvement of [Carousel, Collapse, Divider, List]

- components/List/index.tsx
| List  | 优化 `List` 使用虚拟滚动时 `scrollLoading` 元素渲染的位置。 |  Optimized the rendering position of `scrollLoading` elements when `List` uses virtual scrolling.  |                |
> enhancement: List scrollLoading element position fix when it's virtual

- components/Cascader/panel/list.tsx
> fix: cascader show next level menus when loadMore

- components/DatePicker/panels/date/index.tsx
- components/DatePicker/picker-range.tsx
- components/DatePicker/style/date.less
| DatePicker | 修复 `DatePicker.RangePicker` 组件直接选择时间会报错的 bug。   | Fixed the bug that the `DatePicker.RangePicker` component would report an error when selecting the time directly. | Close: https://github.com/arco-design/arco-design/issues/748 |
> fix: DatePicker issue #748

- components/Input/autoSizeTextAreaHeight.tsx
padingSize error
padingSize= paddingTop + paddingBottom
> fix: textarea autoSizeTextAreaHeight function

- components/Calendar/interface.ts
- components/DatePicker/interface.tsx
- components/DatePicker/panels/body.tsx
- components/DatePicker/panels/range/index.tsx
- components/DatePicker/picker.tsx
|`DatePicker` | 修正 `DatePicker` 组件的 `disabledDate` 的 ts 定义。  |  Fixed ts type of `disabledDate` for `DatePicker` component. | Close: https://github.com/arco-design/arco-design/issues/735  |
> fix: DatePicker disabledDate ts type

- components/Cascader/style/index.less
- components/Cascader/style/token.less
> style: cascader add style token

- components/Cascader/panel/list.tsx
- components/Cascader/panel/search-panel.tsx
- components/Cascader/util.tsx
|       Cascader    |     修复 `Cascader` 组件 `checkedstrategy=parenet` 时，在搜索面板选中选项回显值错误的 bug 。          |               Fixed a bug where the selected option echoed the wrong value in the search panel when `checkedstrategy=parenet` in the `Cascader` component.|      close #743           |
> fix(cascader): Search panel display error

- components/Table/hooks/useRowSelection.tsx
- [] Refactoring
| Table | 优化 `Table` 组件大数据时的数组计算性能。  | Optimized the performance of array computations for large data in the `Table` component.  |  |
> enhance: 优化 getRowsFromKeys 性能, O(n^2) => O(n)

- components/ConfigProvider/__demo__/component-config.md
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/DatePicker/__demo__/timezone.md
- components/DatePicker/__demo__/utcOffset.md
- components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
- components/DatePicker/picker-range.tsx
|  DatePicker  | 修复 `DatePicker.RangePicker` 组件 `utcOffset` 和 `timezone` 不生效的 bug。  | Fixed the bug where `utcOffset` and `timezone` of `DatePicker.RangePicker` component did not work. | Close: #764   |
> fix: DatePicker.RangePicker utcOffset and timezone not work

- components/Form/control.tsx
|     Form      |   修复 `Form.Item` 包裹的表单控件是由函数类型的 `children` 返回时，`onChange` 未被调用的 bug。           |   Fix the bug that `onChange` is not called when the form control wrapped by `Form.Item` is returned by the function type `children`.            |     close: #746           |
> fix(Form): onChange should be trigger when children is a  function

- components/Pagination/README.en-US.md
- components/Pagination/__demo__/more-buffer.md
- components/Pagination/__test__/__snapshots__/demo.test.ts.snap
- components/Pagination/__test__/index.test.tsx
- components/Pagination/interface.ts
- components/Pagination/pagination.tsx
- stories/components/Pagination.jsx
`bufferSize` 以前只用于内部计算并未作为开放字段，此版本后将放开。
| Pagination |  Pagination 组件新增 `bufferSize` 属性，支持设置页码被折叠时的展示区间 | The Pagination component adds a `bufferSize` prop, which supports setting the display area when the page number is collapsed. | Closed: #757    |
> feat(pagination): support buffersize

- components/Checkbox/interface.ts
|   Checkbox        |  调整 `Checkbox` 的 `children` 属性类型定义。             |   Adjusted the `children` property type definition of `Checkbox`.            |                |
> fix: Checkbox children type

- components/Card/style/index.less
- components/Card/style/token.less
> feat(card): add style token

- components/Trigger/README.en-US.md
- components/Trigger/README.zh-CN.md
- components/Trigger/__demo__/updateAtScroll.md
- components/Trigger/__test__/__snapshots__/demo.test.ts.snap
- components/Trigger/index.tsx
- components/Trigger/interface.ts
- components/_util/dom.ts
|     Trigger      |   `Trigger` 组件支持通过 `updateAtScroll` 属性，设置在容器滚动时更新弹出框的位置。            |    The `Trigger` component supports the `updateAtScroll` property to update the position of the popover when the container is scrolled.           |     close #652           |
> feat: Trigger supports updateAtScroll property

- components/Typography/utils.tsx
…ions
|  Typography  |  修复 Typography 设置 `white-space` 后无法折叠的bug  |  Fix the bug of folding error after Typography sets `white-space`  |  Closed: #752   |
> fix(Typography): Does not enforce white-space overrides when calculating

- icon/classifyModal.js
- icon/demo.js
- site/src/pages/home/utils/eventMap.ts
> feat: add event tracking to the action that search icon by img

- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/__demo__/control.md
- components/Form/__demo__/nest-form-item.md
- components/Form/__demo__/validate-messages.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/form.test.tsx
- components/Form/__test__/useform.test.tsx
- components/Form/__test__/validate.test.tsx
- components/Form/control.tsx
- components/Form/form-item.tsx
- components/Form/form.tsx
- components/Form/interface.tsx
- components/Form/utils.tsx
- components/Trigger/__test__/__snapshots__/demo.test.ts.snap
- components/locale/interface.tsx
- components/locale/zh-CN.tsx
- package.json
|     Form      |  `Form`  组件支持通过 `validateMessages` 属性设置校验提示信息模板             |     The `Form` component supports setting the validation message template through the `validateMessages` property          |                |
> feat: Form supports validateMessages

- components/Checkbox/interface.ts
- components/Trigger/__test__/__snapshots__/demo.test.ts.snap
- components/Typography/base.tsx
- components/Typography/utils.tsx
- stories/components/Typography.jsx
| Typography |  Typography 组件多行省略支持不同样式的文本。  | Typography component multi-line omit folding supports different styles of text。  |   Close: #775      |
> feat(Typography): ellipsis support code

- components/List/__demo__/virtual-list.md
- components/List/index.tsx
- components/Select/__demo__/custom-trigger.md
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/_class/VirtualList/index.tsx
| List | `List` 组件 `scrollIntoView` 方法允许指定列表滚动的具体行为。 | The `List` component's `scrollIntoView` method allows specifying the specific behavior of list scrolling. |        Close #700      |
| List | `List` 组件 `virtualListProps` 允许指定虚拟列表元素高度以改善滚动效果。 | The `List` component `virtualListProps` allows specifying virtual list item height to improve scrolling. |        Close #755   |
> enhancement: VirtualList scrolling performance when height of list item varies greatly

- components/Select/__test__/index.test.tsx
- components/Select/interface.tsx
- components/Select/option.tsx
- components/Select/select.tsx
| Select |   修复 `Select.Option` 传入 `onMouseEnter` 和 `onMouseLeave` 未生效的 bug。  |  Fixed the bug that `onMouseEnter` and `onMouseLeave` of `Select.Option` not works. |                |
> fix: Select.Option onMouseEnter/onMouseLeave not work

- components/Card/__test__/__snapshots__/demo.test.ts.snap
- components/Tabs/__test__/__snapshots__/demo.test.ts.snap
- components/Tabs/tab-content.tsx
- components/Tabs/tab-header/dropdown-icon.tsx
- components/Tabs/tab-header/index.tsx
- components/Tabs/tab-header/tab-title.tsx
- components/Tabs/tabs.tsx
- yarn.lock
Accessibility:
Tabs supports role & aria
> enhance: Tabs supports role & aria

- components/Form/store.tsx
See https://github.com/arco-design/arco-design/issues/791
Generic optimization
N/A
| Component | Changelog(CN)             | Changelog(EN)                   | Related issues                                        |
| --------- | ------------------------- | ------------------------------- | ----------------------------------------------------- |
| Form      | 优化`DeepPartial`泛型实现 | Optimized `DeepPartial` generic | https://github.com/arco-design/arco-design/issues/791 |
N/A
> fix(Form): optimize DeepPartial generic

- components/InputNumber/__test__/index.test.tsx
- components/InputNumber/index.tsx
- components/InputNumber/utils.ts
|   InputNumber   |   `InputNumber` 使用 `Math.round` 替换 `Number.prototype.toFixed` 计算小数点后保留的数字，避免末尾数字为 5 时可能出现的临界情况。     | `InputNumber` uses `Math.round` instead of `Number.prototype.toFixed` to calculate the number after the decimal point, to avoid the critical situation that may occur when the final number is 5.  |     Close #782           |
> enhancement: InputNumber with precision use Math.round to replace number.toFixed

- components/Pagination/page-item.tsx
- components/Pagination/pagination.tsx
Pagination locale fallback to avoid custom locales error. Close: https://github.com/arco-design/arco-design/issues/790
> enhance: Pagination locale fallback to avoid error

- components/_class/notification.tsx
|   Notification        |   修复 `Notification` 组件在并发弹出多个提醒框时，只渲染出部分通知的 bug。  |   Fixed a bug where the `Notification` component only rendered some notifications when multiple reminder boxes popped up concurrently.            |                Close #789  |
> fix: notification count error

- components/Calendar/README.en-US.md
- components/Calendar/README.zh-CN.md
- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Pagination/README.zh-CN.md
- components/Radio/interface.ts
- components/Slider/README.en-US.md
- components/Slider/README.zh-CN.md
- components/Table/README.en-US.md
- components/Table/README.zh-CN.md
- components/Table/interface.tsx
- components/Timeline/README.en-US.md
- components/Timeline/README.zh-CN.md
- components/Tree/README.zh-CN.md
- components/Typography/README.zh-CN.md
|     Table      |    修改 `Table` 组件 `rowKey` 的 `TS` 定义为 `React.Key \| ((record: T) => React.Key)`。          |      Modify the `TS` of the `Table` component `rowKey` to be `React.Key \| ((record: T) => React.Key)`.       |  close #751               |
> ts: TableProps rowKey

- components/BackTop/__test__/__snapshots__/demo.test.ts.snap
- components/Calendar/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/__test__/__snapshots__/index.test.tsx.snap
- components/Cascader/cascader.tsx
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Input/__test__/__snapshots__/demo.test.ts.snap
- components/Pagination/__test__/__snapshots__/demo.test.ts.snap
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Select/__test__/__snapshots__/index.test.tsx.snap
- components/Select/option.tsx
- components/Select/select.tsx
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/tree-select.tsx
- components/Trigger/__test__/__snapshots__/demo.test.ts.snap
- components/_class/select-view.tsx
Aria improvement.
`Select` add `role` `aria-haspopup` `aria-autocomplete` `aria-expanded` `aria-disabled` `aria-controls`.
`Select.Option` add `role` `aria-selected`.
> enhancement: Aria improvement for Select

- components/Pagination/__test__/__snapshots__/demo.test.ts.snap
> test: update snap

- components/DatePicker/__test__/date.test.tsx
- components/DatePicker/picker.tsx
|      DatePicker     |      修复 `DatePicker` 组件传入不包含 `defaultValue` 的 `showTime` 对象，导致时间面板报错的 bug。          |       Fixed a bug where the `DatePicker` component passed a `showTime` object that did not contain a `defaultValue`, causing the time panel to report an error.        |                |
> fix: timepicker error when showTime is an empty object

- components/_util/getHighlightText.tsx
Select组件，文本搜索功能，当输入小写时，大写的那些选项，有显示出来，但并不高亮
更改了getHighlightText工具函数的执行逻辑，使用带capture group功能的正则，来split字符串。
修复结果
| Select  |  修复 `Select` 组件搜索时匹配到的选项文本未高亮的问题。  |  Fixed an issue where the matched option text was not highlighted when the `Select` component searched.    |                |
> fix(select): highlight matched text by case-insensitive

- components/Form/control.tsx
- components/Form/form-item.tsx
|  Form         |      修复 `Form` 组件在 React 18 严格模式下，表单项受控失效的 bug。        |   Fix the bug that the `Form` component has controlled invalidation of form items in React 18 strict mode.            |   close #788              |
> fix: form not work in react 18 strictmode

- components/Form/store.tsx
- components/locale/ja-JP.tsx
- components/locale/zh-HK.tsx
- components/locale/zh-TW.tsx
> feat: form validateMessage add ja-JP, zh-HK lang

- components/Typography/utils.tsx
| Typography  | 修复 `Typography` 组件单行省略下 `Tooltip` 失效的bug| Fix the bug that the `Tooltip` is invalid when the `Typography` component is omitted from a single line |   Closed: #821   |
> fix(Typography): white-space effect when ellipsis is calculated

- components/Switch/__test__/index.test.tsx
- components/Switch/index.tsx
- components/Switch/interface.ts
|     Switch      |    修复 `Switch` 组件无法触发 `Popconfirm` 弹出层显示的 bug。           |    Fixed a bug where the `Switch` component could not trigger the display of the `Popconfirm` popup layer.           |    Close #828             |
> fix: switch onclick

- components/Tabs/tab-header/index.tsx
…rectly judged
|   Tabs  |  修复 `Tabs` 组件滚动按钮展示/消失临界计算错误的 bug。 | Fixed the bug of critical calculation error in the appear/disappear of the scroll button of the `Tabs` . |  Closed: #812  |
> fix(tabs):Fixed the bug that the timing of the tabs scroll button was incorrectly judged.

- site/src/pages/home/sections/ShowCase/style/index.module.less
> fix(style): the background of showcase in home is not align center

- components/Table/__test__/pagination.test.tsx
- components/Table/table.tsx
| Table | 修复 `Table` 组件的外层 `ConfigProvider` 设置 `pagination` 后无法生效的bug。| Fix the bug that the outer `ConfigProvider` of the `Table` component cannot take effect after setting `pagination`  |                |
> fix(Table): Table Pagination 优先级

- components/Statistic/__test__/__snapshots__/demo.test.ts.snap
- components/Statistic/__test__/index.test.tsx
- components/Statistic/index.tsx
- components/Statistic/style/index.less
- components/Statistic/style/token.less
Add less token:
Statistic prefix and suffix margin.
Close: https://github.com/arco-design/arco-design/issues/838
> style: Statistic add token prefix and suffix margin

- components/ConfigProvider/interface.ts
- components/Timeline/__test__/__snapshots__/index.test.tsx.snap
- components/Timeline/__test__/index.test.tsx
- components/Timeline/item.tsx
| ConfigProvider | `ConfigProvider` 组件的 `componentConfig` 支持配置 `Timeline.Item`。  | The `componentConfig` of the `ConfigProvider` component supports configuring `Timeline.Item`. |  Close: https://github.com/arco-design/arco-design/issues/853  |
> feat: ConfigProvider componentConfig add Timeline.Item

- components/Table/table.tsx
Close: https://github.com/arco-design/arco-design/issues/807
> fix: Table no header set scrollbar error

- components/Form/__demo__/form-context.md
- components/Form/__demo__/useWatch.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/use.test.tsx
- components/Form/hooks/useContext.ts
- components/Form/hooks/useWatch.ts
- components/Form/index.tsx
- components/Form/interface.tsx
- components/Form/store.tsx
- components/Form/useForm.ts
|       Form    |   `Form` 组件支持 `Form.useWatch`。            |      The `Form` component supports `Form.useWatch`.         |close #816                 |
|       Form    |       `Form` 组件支持 `Form.useFormContext`。                       |      The `Form` component supports `Form.useFormContext`.         |     close #816            |
> feat: Form supports Form.useWatch & Form.useFormContext

- components/Upload/request.ts
|       Upload    |     调整 `Upload` 组件上传请求的参数顺序（`file` 字段最后被添加到 `FormData` 中）。         |   Adjust the order of parameters in the upload request of the `Upload` component (the `file` field is added last to `FormData`).            |                close #842 |
> fix(upload): Adjust the sequence of upload request parameters

- components/Anchor/anchor.tsx
- 看了下出现的原因是 `slide` 的回调一直无法触发，因为其实走的是 `resolve(null)` 的逻辑。
- 所以说在动画完成前`isScrolling.current` 就是 `false` 了
- 然后就会触发 `scrollEventListener` 把出现在适口最佳位置的元素作为激活元素。
- 这样导致可能出现 用户点击了最后一个锚点，但实际上定位到适口中间的锚点元素。
| Anchor | 修复 `Anchor` 组件在内容高度不够的情况下，点击锚点元素定位出错的 bug | Fixed the bug that the `Anchor` component clicked on the anchor element when the content height was not enough. | Closed: #846  |
> fix(Anchor): scroll animation complete callback

- components/Typography/README.en-US.md
- components/Typography/README.zh-CN.md
- components/Typography/__test__/__snapshots__/demo.test.ts.snap
- components/Typography/__test__/index.test.tsx
- components/Typography/base.tsx
- components/Typography/interface.tsx
- components/Typography/operations.tsx
- stories/components/Typography.jsx
|  Typography   |   `Typography` 组件省略场景支持展开受控。   |  The `Typography` component omits the scene to support expanding controlled.   |     |
> feat(Typography): ellipsisConfig.expand support controlled scene

- components/Form/store.tsx
- components/Table/README.en-US.md
- components/Table/README.zh-CN.md
- components/Table/__demo__/data-children.md
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Table/__test__/common/data.ts
- components/Table/__test__/expand.test.tsx
- components/Table/__test__/selection.test.tsx
- components/Table/__test__/sorter.test.tsx
- components/Table/hooks/useRowSelection.tsx
- components/Table/interface.tsx
- components/Table/table.tsx
- components/Table/tbody/tr.tsx
- components/Table/utils.tsx
|  Table  | `Table` 组件新增 `rowSelection.checkStrictly` 支持父子选择关联。  |  `Table` Add `rowSelection.checkStrictly` to support parent-child selection associations.   |  Close: https://github.com/arco-design/arco-design/issues/698  |
> feat: Table add checkStrictly

- components/Typography/base.tsx
- components/Typography/utils.tsx
| Typography  |  修复`Typography` 组件使用 `code`等行内元素时，折叠出错的 bug。 |  Fix the bug of folding error when `Typography` component uses inline elements such as `code`.   |       |
> fix(Typography): The effect of `display:inline` such as `<code/>` on ellipsising

- components/Tabs/style/index.less
- components/Tabs/style/token.less
|     Tabs      |     `rounded` 类型的 `Tabs` 组件支持不同尺寸。         |       The `Tabs` component of type `rounded` supports different sizes.        |        close #742         |
> feat: Rounded Tabs supports size

- components/Anchor/link.tsx
- components/_util/is.ts
如果级别发生跳变的话，比如从1级变为3级标题，因为是嵌套结构需要嵌套一层`text`为`""`的节点，则会出现一个空白，且空白能点击，#846 的第二个问题。
当`title`为空的时候，不显示其下的可点击区域`<a/>`。
|    Anchor       |        当`title`为空的时候，不显示其下的可点击区域`<a/>`       |       When `title` is empty, the clickable area `<a/>` under it is not displayed        |        #846        |
与 #847 相同，但是因为分支分问题，重新提交
> Fix anchor

- components/Table/style/index.less
|    Table       |    修复表格分组时，内部的表头单元格也有圆角           |        Fix  inner table header have border radius when table set column group      |      Close [#837](https://github.com/arco-design/arco-design/issues/837)          |
> fix(table): fix group column has wrong border radius

- components/Form/form-item.tsx
- components/Form/interface.tsx
> ts: form ts

- components/ResizeBox/__test__/group.test.tsx
- components/ResizeBox/split-group.tsx
|  ResizeBox  |  修复 `ResizeBox` 的 `Split.Group` 在特定场景无法自适应的 bug |  Fixed a bug that `Split.Group` of `ResizeBox` could not adapt to certain scenes  |    Closed: #871  |
> fix(ResizeBox): Split.Group adaptive bug

- components/Upload/style/index.less
- components/Upload/style/token.less
> style: upload add token

- components/Typography/__test__/__snapshots__/demo.test.ts.snap
- components/Typography/__test__/index.test.tsx
- components/Typography/base.tsx
- components/Typography/operations.tsx
- stories/components/Typography.jsx
|  Typography  |  修复 `Typography` 组件 `展开/折叠` 按钮展示时机错误的bug  |  Fixed the bug that the `Expand/Collapse` button of the `Typography` component was displayed at the wrong time  |   Closed: #876     |
> fix: expanding operation display time

- components/DatePicker/README.en-US.md
- components/DatePicker/README.zh-CN.md
- components/DatePicker/__test__/date.test.tsx
- components/DatePicker/interface.tsx
- components/DatePicker/picker.tsx
- stories/DatePicker.story.tsx
|  DatePicker  | `DatePicker` 组件新增 `panelRender` 参数。  | Added `panelRender` parameter to the `DatePicker` component.   |                |
> Feat datepicker panel render

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Cascader/__demo__/custom_children.md
- components/Cascader/cascader.tsx
- components/Cascader/interface.ts
> feat: 给Cascader增加inputvalue属性

- site/package.json
- site/yarn.lock
|   bump arco-doc-site-components version to support ts demo        |   升级 arco-doc-site-components 版本，支持 ts demo          |               |                |
> chore: bump arco-doc-site-components version to support ts demo

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/__demo__/setFields.md
- components/Form/control.tsx
- components/_util/is.ts
|     Form      |     修复 `Form` 组件通过 `setFields` 设置 `warning` 为 `null` 时，表单控件的 `warning` 状态未被清空的 bug 。        |     Fix the bug that the `warning` state of the form control is not cleared when the `Form` component sets the `warning` to `null` through `setFields`.          |    close #900             |
> fix: form should clear warning status

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Cascader/__demo__/custom_children.md
- components/Cascader/__demo__/search.md
- components/Cascader/cascader.tsx
- components/Cascader/interface.ts
|    Cascader       |    `Cascader` 组件支持通过 `InputValue` 属性控制输入框值 。          |      The `Cascader` component supports controlling the input box value through the `InputValue` property         |   close #815              |
> feat: Cascader supports inputValue and onInputValueChange

- components/Timeline/style/index.less
|     Timeline      |  修复 `Timeline` 组件在 `mode=alternate` 时，时间轴右侧 label 内容渲染样式错误的问题。             |        Fixed an issue where the content of the label on the right side of the timeline was rendered incorrectly when the `Timeline` component was in `mode=alternate`.       |    close #902              |
> fix: timeline label style in alternate mode

- components/Portal/Portal.tsx
> fix: portal Spelling mistakes

- components/Trigger/README.en-US.md
- components/Trigger/README.zh-CN.md
- components/Trigger/index.tsx
- components/Trigger/interface.ts
Trigger组件在多个嵌套滚动容器情况下，会有popup被遮挡，或者popup浮出当前滚动容器等一些edge case，因此，增加一个closeOnScroll属性，用于简化处理。
另外，和UX沟通，一般用户滚动的话，可能这个时候是不需要看菜单的，如有这样的情况，便可以使用该属性。
|      Trigger     |     `Trigger` 组件支持通过 `containerScrollToClose` 属性设置弹出层挂载容器滚动时，关闭弹出层。           |   The `Trigger` component supports the popup layer to be closed when the container is scrolled by setting the `containerScrollToClose` property.            |                |
> feat(trigger): add a new prop "containerScrollToClose" supporting close popup when scrolling

- components/Transfer/__demo__/with-table.md
- components/Transfer/list.tsx
|  Transfer   |   修复 `Transfer` 自定义列表时，`onItemSelectAll` 方法失效的 bug。      |   Fix the bug that the `onItemSelectAll` method does not work when `Transfer` customizes the list.  |                |
> fix: Transfer custom list's select-all not work

- components/Menu/style/index.less
|  Menu  |  调整 `Menu` 的子菜单从左侧弹出时弹出层的位置。 | Adjust the position of the popup layer when the submenu of `Menu` pops up from the left. |      Close #897          |
> style: sub-menu position of menu in pop mode

- components/Radio/interface.ts
- components/Radio/radio.tsx
|     Radio      | 完善 `Radio` 组件对 `children` 的 TS 定义             |      Improve the TS definition of `children` for `Radio` component         |       close #919          |
> fix: radio ts 

- components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap
- components/ResizeBox/split-group.tsx
- stories/Resizebox.story.tsx
|  ResizeBox  | 修复 `ResizeBox.SplitGroup` 响应式出错的bug |  Fix `ResizeBox.SplitGroup` responsive error bug    |             Closed: #871 |
> fix(ResizeBox): Use percentage calculation to cover responsive scenarios

- components/Layout/README.en-US.md
- components/Layout/README.zh-CN.md
- components/Layout/__demo__/resizeProps.md
- components/Layout/__test__/__snapshots__/demo.test.ts.snap
- components/Layout/__test__/index.test.tsx
- components/Layout/interface.ts
- components/Layout/sider.tsx
|  Layout  | Layout 新增 `resizeBoxProps` 属性，接收 `resizeBox` 的所有参数 |Layout adds `resizeBoxProps` property to receive all parameters of `resizeBox` | Closed: #882 |
> feat(Layout): support resizebox props

- components/Typography/base.tsx
| Typography |  减少 `Typography` 首次渲染时的计算次数  |  Reduce the number of computations for `Typography` on first render   |                |
> enhance(Typography): Reduce the number of first fold calculations

- components/Card/__test__/__snapshots__/demo.test.ts.snap
- components/Tabs/__test__/__snapshots__/demo.test.ts.snap
- components/Tabs/style/index.less
- components/Tabs/style/token.less
- components/Tabs/tab-header/index.tsx
- components/Tabs/tab-header/tab-title.tsx
- components/Tabs/utils.tsx
|     Tabs      |  `Tabs` 组件页签头支持通过 Tab 键聚焦样式              |   The `Tabs` component tab header supports focusing styles via the Tab key            |               |
> style: Tabs supports focus-visible style

- components/Button/style/index.less
- components/Button/style/token.less
- components/Upload/__test__/list.test.tsx
- stories/Button.story.tsx
| Button | `Button` 组件添加 Tab 键选中的样式。  | The `Button` component adds the tab selection style. |        https://github.com/arco-design/arco-design/issues/160        |
> style: Button add focus-visible style

- components/Table/__demo__/virtualized.md
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Table/style/index.less
- components/Table/table.tsx
- components/Table/tbody/index.tsx
- components/_class/VirtualList/Filler.tsx
- components/_class/VirtualList/index.tsx
- stories/Table.story.tsx
- yarn.lock
|  Table  | `Table` 组件开启 `virtualized` 后支持固定列。  | The `Table` component supports fixed columns when `virtualized` is enabled.  |   Close: https://github.com/arco-design/arco-design/issues/644  |
> Feat table virtual fixed

- components/Layout/__test__/index.test.tsx
- components/Layout/sider.tsx
- components/ResizeBox/__demo__/split.md
- components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap
- components/ResizeBox/__test__/index.test.tsx
- components/ResizeBox/interface.ts
- components/ResizeBox/split.tsx
|  `ResizeBox`  |   `ResizeBox.Split` 新增 `horizontal-reverse` 和 `vertical-reverse` 两种排列方式。  | `ResizeBox.Split` added `horizontal-reverse` and `vertical-reverse` two arrangements.  | Closed:  #870   |
> feat(Resize): support direction reverse

- components/Collapse/item.tsx
- components/Radio/interface.ts
> fix: collapse error in react 18

- components/style/animation/zoom.less
|   Common        |      调整 `Popconfirm`，`Popover`， `Tooltip` 组件动画弹出效果，避免边界场景下过冲效果导致的页面抖动。     |    Adjust `Popconfirm`, `Popover`, `Tooltip` component animation pop-up effect to avoid page jitter caused by overshoot effect in border scenes.       |        Close #881         |
> style: tooltip animation function

- components/DatePicker/README.en-US.md
- components/DatePicker/README.zh-CN.md
- components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
- components/DatePicker/__test__/date.test.tsx
- components/DatePicker/__test__/format.test.tsx
- components/DatePicker/__test__/panel.test.tsx
- components/DatePicker/__test__/range.hover.test.tsx
- components/DatePicker/__test__/range.test.tsx
- components/DatePicker/__test__/timezone.test.tsx
- components/DatePicker/__test__/week.test.tsx
- components/DatePicker/context.ts
- components/DatePicker/interface.tsx
- components/DatePicker/panels/body.tsx
- components/DatePicker/panels/date/index.tsx
- components/DatePicker/panels/range/index.tsx
- components/DatePicker/panels/week-list.tsx
- components/DatePicker/panels/week/index.tsx
- components/DatePicker/picker-range.tsx
- components/DatePicker/picker.tsx
- components/DatePicker/util.ts
- components/_util/dayjs.ts
| DatePicker |  `DatePicker` 组件的 `dayStartOfWeek` 的默认值由 locale 语言决定，不再统一默认 `0`。   | The default value of the `dayStartOfWeek` of the `DatePicker` component is determined by the locale set, no longer default to `0`.  | Close: https://github.com/arco-design/arco-design/issues/779         |
> enhance: DatePicker dayStartOfWeek default is determined by locale

- components/Select/__test__/index.test.tsx
- components/Select/select.tsx
|  Select |  修复 `Select` 组件设置 `LabelInValue` 时可能出现的回调参数格式错误的 bug。 |  Fixed the bug that the callback parameter was wrong when the `Select` component set `LabelInValue`. |                |
> fix: labelInValue not work in Select with a initial LabeledValue

- components/Menu/context.ts
- components/Menu/hotkey.ts
- components/Menu/index.tsx
- components/Menu/item.tsx
- components/Menu/style/index.less
- components/Tabs/style/index.less
- components/Tabs/style/token.less
| Menu  |  修复 `Menu` 组件子菜单标题栏图标未垂直居中的问题。  |   Fixed `Menu` component submenu title bar icons not vertically centered.  |                |
> style: vertical position of menu-header's suffix icon

- components/Input/__test__/index.test.tsx
- components/Input/input-element.tsx
- components/Input/input.tsx
- components/Input/interface.tsx
- components/Input/textarea.tsx
- components/Input/useComposition.ts
- components/InputTag/input-tag.tsx
- components/Mentions/__test__/index.test.tsx
- components/Typography/__test__/index.test.tsx
- components/_class/select-view.tsx
- stories/Typography.story.tsx
|   Input   |   修复 `Input.TextArea` 组件输入中文时长度有可能超过 `maxLength` 的 bug。  |    Fixed the bug that the length of `Input.TextArea` component may exceed `maxLength` when inputting Chinese.  |     Close #964        |
> fix: textarea maxLength may not work while inputing Chinese

- components/Cascader/__demo__/custom_children.md
Cascader组件自定义选择框示例代码在无初始值的情况下，样式展示有问题，会多出一部分无关空白。
https://codesandbox.io/s/klsvqp?file=/index.js
给外层div设置最大宽度为内容宽度（maxWidth: 'fit-content'）。
> docs:优化Cascader组件自定义选择框demo代码

- components/Cascader/__test__/index.test.tsx
- components/Cascader/panel/list.tsx
- components/Cascader/panel/search-panel.tsx
- site/package.json
- site/yarn.lock
Upgrade arco-markdown-loader and arco-site-components.
> site: upgrade arco-markdown-loader and arco-site-components

- .github/workflows/main.yml
> add react 18 check action

- components/Table/hooks/useRowSelection.tsx
- components/Table/table.tsx
- components/Table/utils.tsx
- stories/Table.story.tsx
|  Table  |  修复 `Table` 组件在树形数据时会改变原始 data 的 bug。  |   Fix the bug that `Table` component will change the original data when tree data.   |  Close: https://github.com/arco-design/arco-design/issues/999  |
> fix: Table should not change origin data

- components/Select/interface.tsx
- components/Select/option.tsx
- components/Select/select.tsx
|  Select  |  `Select` 组件通过 Dom Attribute 标记用户正在创建和已经创建的选项。  | The `Select` component uses the Dom Attribute to mark options that the user is creating and has already created. | Close #998  |
> enhancenment: mark Select options that are created/creating by user self via DOM attribute

- components/DatePicker/__test__/range.hover.test.tsx
- components/DatePicker/hooks/useCellClassName.ts
- components/DatePicker/style/index.less
Enhancement: DatePicker.RangePicker hover style. Close: https://github.com/arco-design/arco-design/issues/1001
> enhance: DatePicker hover style

- .github/workflows/pr_check.yml
1. Update `actions/setup-node` from v2 to v3
2. Update node 14 to node 16
3. Add yarn cache to speed up pr-check
```yaml
uses: actions/setup-node@v3 
with:
node-version: 16
cache: 'yarn'
```
N/A
> Update Github Action and Node Runtime

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Cascader/__demo__/draggable.md
- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/cascader.tsx
- components/Cascader/interface.ts
- components/TreeSelect/__demo__/draggable.md
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/tree-select.tsx
| Cascader | 修复 `dragToSort` 在 `Cascader` 中不生效的问题 | fix `dragToSort` not works  on `Cascader`  |  close #1018  |
| TreeSelect | 修复 `dragToSort` 在 TreeSelect 中不生效的问题 | fix `dragToSort` not works on `TreeSelect` | close #1018  |
> Sfj/fix tree select/cascader dragtosort

- components/DatePicker/picker-range.tsx
| DatePicker | 修复 `DatePicker` 组件少数情况选择范围失效的 bug。  |  Fixed a bug where the selection range of the `DatePicker` component was invalid in rare cases.   | Close: https://github.com/arco-design/arco-design/issues/1036  |
> fix: DatePicker first select range

- components/Pagination/style/index.less
|  Pagination  |  修复 `Pagination` 中的省略号在某些情况下垂直方向未居中的问题。  |  Fixed ellipsis in `Pagination` not vertically centered in some cases.  |     Close #1000        |
> style: make sure vertical-align of Pagination item-jumper's icon is center

- components/Statistic/README.en-US.md
- components/Statistic/README.zh-CN.md
- components/Statistic/__demo__/countdown.md
- components/Statistic/__test__/__snapshots__/demo.test.ts.snap
- components/Statistic/__test__/countdown.test.tsx
- components/Statistic/__test__/index.test.tsx
- components/Statistic/countdown.tsx
- components/Statistic/index.tsx
- components/Statistic/interface.ts
|  Statistic  | `Statistic` 新增 `renderFormat` 参数支持自定义渲染。  | `Statistic` component adds `renderFormat` parameter to support custom rendering. |   Closed: #994    |
> feat(Statistic): support renderFormat

- components/Menu/style/index.less
- components/Select/option.tsx
|    Menu     |  修复 `Menu.SubMenu` 展开时其右侧的箭头方向未改变的问题。 |  Fixed the issue that the arrow direction on the right side of `Menu.SubMenu` did not change when it was expanded.  |                |
> style: Menu.SubMenu's arrow should rotate when the SubMenu is opened

- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/context.ts
- components/Form/form-item.tsx
- components/Form/form-list.tsx
- components/Form/store.tsx
|     Form      |    修复 `Form.List` 组件在移除表单项时，其他表单项校验状态丢失的 bug。          |      Fixed a bug where the validation state of other form items was lost when the `Form.List` component was removed from the form item.         |                close #996 |
|     Form      |    修复 `form.clearFields()` 方法未清空校验状态的 bug。          |      Fixed a bug where the `form.clearFields()` method did not clear the validation state.        |                close #1027 |
> fix: Set field error bug when use dynamic form

- components/Table/hooks/useExpand.tsx
- components/Table/hooks/useRowSelection.tsx
- components/Table/table.tsx
- components/Table/tbody/index.tsx
- components/Table/tbody/td.tsx
- components/Table/tbody/tr.tsx
- components/Table/tfoot/index.tsx
- components/Table/utils.tsx
- stories/Table.story.tsx
|  Table |  修复 `Table` 组件对外输出的 data 和 record 包含内部数据的 bug。  |   Fixed the bug that the data and record outputted by the `Table` component contained internal data.   | Close: https://github.com/arco-design/arco-design/issues/999     |
> fix: Table output data and record should not contains internal data

- components/Statistic/__demo__/countdown.md
> fix: Statistic demo renderFormat 

- components/Drawer/index.tsx
|   Drawer        |   修复 `Drawer` 在隐藏过程中设置 `visible=true` 时，再次点击蒙层抽屉无法被隐藏的 bug。             |  Fixed the bug that when the `Drawer` was set to `visible=true` during the hiding process, clicking again on the masked drawer could not be hidden.             |        close #1058         |
> fix: drawer should be hidden

- components/Typography/style/index.less
Fix the following warning:
```
autoprefixer: end value has mixed support, consider using flex-end instead
````
根据代码上下文 (`display:flex`) 得知此处是 flexbox ，因此 `align-items: end;` 应该写为 `align-items: flex-end;`
|   Typography |    修复 Typography 组件 flex 属性值不规范的问题  |  Fix a css flex property in Typography  |                |
> fix(Typography): fix autoprefixer warning

- components/Table/utils.tsx
- stories/Table.story.tsx
Fix bug when Table record is class, it will be converted to object.
> fix: Error when Table data item is class

- components/Form/README.en-US.md
- components/Form/README.zh-CN.md
- components/Form/control.tsx
- components/Form/form-item.tsx
- components/Form/interface.tsx
|    Form       |       修复 `Form.List` 下调整表单项顺序，校验状态可能出现展示错乱的问题        |       Fix the problem that the order of form items is adjusted under `Form.List`, and the verification status may be displayed in disorder        |      close #1059           |
> fix: clear error status

- components/TimePicker/picker.tsx
- components/TimePicker/util.ts
- stories/DatePicker.story.tsx
> fix: TimePicker with timezone auto sort

- components/Calendar/style/index.less
add one line less code~
|      Calendar     |  使用年日历时，`defaultValue`以及selected date没有被高亮             |        `defaultValue` and selected date not highlighted when in year mode       | #1072                |
> fix: add style for selected date when year mode

- components/Card/__demo__/hoverable.md
- components/Card/__demo__/no-border.md
- components/Card/__demo__/only-content.md
- components/Card/__demo__/with-actions.md
- components/Card/__demo__/with-skeleton.md
- components/Card/__test__/__snapshots__/demo.test.ts.snap
- components/Card/index.tsx
- components/Card/style/index.less
- site/src/index.js
> style: Card add rtl style

- components/Tabs/__test__/index.test.tsx
- components/Typography/__test__/css-ellipsis.test.tsx
- components/Typography/__test__/index.test.tsx
- components/Typography/__test__/js-ellipsis.test.tsx
> Test migration to `esting-library` by yyh

- components/Transfer/style/index.less
|  Transfer   |  修复 `Transfer` 可拖拽时，列表中的第一个条目的拖拽标识可能被容器遮挡的问题。   | Fixed an issue where the drag flag of the first item in the list might be obscured by the container when `Transfer` is draggable. |  Close #1054   |
> style: hint style of draggable Transfer item

- components/Collapse/collapse.tsx
- components/Collapse/style/index.less
- site/src/index.js
> RTL style: Collapse

- components/Carousel/index.tsx
- components/Carousel/style/index.less
- site/src/index.js
> style: Carousel add rtl style

- components/Table/__demo__/attribution.md
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Table/style/index.less
- components/Table/table.tsx
|  Table | 修复 `Table` 组件左边框在无数据时消失的样式问题。 |  Fix the style issue that the left border of `Table` component disappears when there is no data.  | Close: https://github.com/arco-design/arco-design/issues/1088    |
> style: Table no data border

- components/Table/tbody/tr.tsx
Fix Table row props object deconstruct.
> fix: Table row props object deconstruct

- components/Calendar/__demo__/panel.md
- components/Calendar/__test__/__snapshots__/demo.test.ts.snap
- components/Calendar/index.tsx
- components/Calendar/style/index.less
- site/src/index.js
> RTL style: calendar

- components/Table/table.tsx
- components/Table/utils.tsx
|   Table   |  修复 `Table` 组件 data 为 null 时报错的 bug。   |  Fix the bug of error when `Table` component data is null.   | Close: https://github.com/arco-design/arco-design/issues/1090  |
> fix: Error when Table data is null

- components/Upload/uploader.tsx
|      Upload     |        修复 `Upload` 组件在 Windows 系统下可以上传非 `accept` 类型的文件       |        fix `Upload` can upload file type not in accept       |        Close #1093         |
> fix: upload should check file type before upload

- components/InputTag/README.en-US.md
- components/InputTag/README.zh-CN.md
- components/InputTag/__demo__/basic.md
- components/InputTag/__demo__/validate.md
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/__test__/index.test.tsx
- components/InputTag/input-tag.tsx
- components/InputTag/interface.ts
- stories/InputTag.story.tsx
|   InputTag  | `InputTag` 组件允许通过 `validate` 属性格式化用户输入的值。  |  The `InputTag` component allows formatting of values entered by the user via the `validate` property.  |    Close #1066    |
> feat: InputTag validate allow return a non-boolean result

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Cascader/cascader.tsx
- components/Cascader/interface.ts
- components/Cascader/panel/search-panel.tsx
- components/_class/select-view.tsx
| Cascader| `Cascader` 支持通过  `defaultActiveFirstOption` 属性设置搜索后默认高亮第一个选项。  |`Cascader` supports the default highlighting of the first option after searching by setting the `defaultActiveFirstOption` property.|feature #1096 |
> feat: cascader add default highlight option attribute after search

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Cascader/__test__/__snapshots__/index.test.tsx.snap
- components/Cascader/__test__/index.test.tsx
- components/Cascader/__test__/search.test.tsx
- components/Cascader/interface.ts
- components/Checkbox/__test__/group.test.tsx
- components/Checkbox/__test__/index.test.tsx
- components/Form/__template__/index.en-US.md
- components/Form/__template__/index.zh-CN.md
- components/Upload/__template__/index.en-US.md
- components/Upload/__template__/index.zh-CN.md
> test: update cascader & checkbox test cases

- components/Typography/style/index.less
|  Typography   |   `Typography` 默认样式添加 `white-space: 'normal'` 以消除父元素对省略影响。      | The `Typography` default style adds `white-space: 'normal'` to remove the parent element's effect on ellipsis.   |  Closed: #1055    |
> style: add typography default whiteSpace style

- components/Form/__test__/use.test.tsx
- components/Form/hooks/useWatch.ts
|      Form     |   修复 `Form.useWatch` 在监听有初始值但未挂载的表单控件时，返回值存在 `初始值 => undefined` 的变化，导致组件更新。            |    Fixed `Form.useWatch` when monitoring a form control with an initial value but not mounted, the return value has a change of `initial value => undefined`, causing the component to update.      |                |
|      Form     |   `Form.useWatch` 支持监听多个字段值。            |     `Form.useWatch` supports watching multiple field values.          |                |
> feat: Form.useWatch supports multiple fields

- components/Upload/README.en-US.md
- components/Upload/README.zh-CN.md
- components/Upload/__demo__/drag.md
- components/Upload/__test__/__snapshots__/demo.test.ts.snap
- components/Upload/interface.tsx
- components/Upload/trigger-node.tsx
- components/Upload/upload.tsx
- components/Upload/uploader.tsx
|   Upload   |  `Upload` 组件支持监听 `onDrop` 事件          |  The `Upload` component supports listening to the `onDrop` event             |     #991            |
> feat: add ondrop prop for upload

- components/Avatar/__demo__/autoFixFontSize.md
- components/Avatar/__test__/__snapshots__/demo.test.ts.snap
- components/Avatar/avatar.tsx
- components/Avatar/group.tsx
- components/Avatar/style/index.less
> RTL style: Avatar.

- components/Grid/col.tsx
- components/Grid/row.tsx
- components/Grid/style/col.less
- components/Grid/style/row.less
> RTL style: Grid

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/Select/__demo__/multiple.md
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/README.en-US.md
- components/TreeSelect/README.zh-CN.md
- components/_class/select-view.tsx
|   Select        |    `Select` 组件支持通过对象类型的 `maxTagCount` 属性定制 `maxTag` 内容展示          | The `Select` component supports customizing the `maxTag` content display through the `maxTagCount` property of the object type              |    close #1063             |
|   Cascader        |    `Cascader` 组件支持通过对象类型的 `maxTagCount` 属性定制 `maxTag` 内容展示          | The `Cascader` component supports customizing the `maxTag` content display through the `maxTagCount` property of the object type              |    close #1063             |
|   TreeSelect        |      `TreeSelect` 组件支持通过对象类型的 `maxTagCount` 属性定制 `maxTag` 内容展示          | The `TreeSelect` component supports customizing the …
> feat: select supports maxTagCount render

- components/_util/getHighlightText.tsx
Lodash cannot on demand, Using the component with the getHighlightText method, the package size of lodash is too large.
|  |  按需引入 lodash |  Lodash on demand       |                |
> perf(lodash): lodash on demand

- components/Collapse/__test__/index.test.tsx
- components/Comment/__test__/index.test.tsx
- components/ConfigProvider/__test__/locale.test.tsx
- components/ConfigProvider/__test__/theme.test.tsx
- components/DatePicker/__test__/date.test.tsx
- components/DatePicker/__test__/format.test.tsx
- components/DatePicker/__test__/month.test.tsx
- components/DatePicker/__test__/panel.test.tsx
- components/DatePicker/__test__/quarter.test.tsx
- components/DatePicker/__test__/range.hover.test.tsx
- components/DatePicker/__test__/range.panel.test.tsx
- components/DatePicker/__test__/range.test.tsx
- components/DatePicker/__test__/timezone.test.tsx
- components/DatePicker/__test__/utils.ts
- components/DatePicker/__test__/week.test.tsx
- components/DatePicker/__test__/year.test.tsx
- components/Descriptions/__test__/index.test.tsx
- components/Divider/__test__/index.test.tsx
- components/Rate/__test__/index.test.tsx
- components/Result/__test__/index.test.tsx
- components/Skeleton/__test__/index.test.tsx
- tests/util.ts
> test: upgrade tests

- components/Select/style/index.less
- components/Tabs/style/rtl.less
- Fix irregular style writing
- 修复不规范的 style 写法
> style: fix irregular rtl style

- components/Dropdown/__test__/__snapshots__/demo.test.ts.snap
- components/Dropdown/__test__/index.test.tsx
- components/Dropdown/button.tsx
- components/Dropdown/index.tsx
- components/Link/__demo__/dropdown.md
- components/Link/__test__/__snapshots__/demo.test.ts.snap
| Dropdown | 修复 `disabled` 属性未对 `Dropdown.Button` 的第二个按钮生效的 bug。 |   Fixed the bug that `disabled` didn't work for the second button of `Dropdown.Button`. |   Close #1126  |
> fix: disabled not work for the second button of Dropdown.Button

- components/Typography/base.tsx
- components/Typography/useEllipsis.tsx
|  Typography  | 修复 `Typography` 组件 `underline` 等不同文本样式下文字省略问题 | Fix the problem of `Typography` text omission under different text styles such as `underline`  |                |
> fix(Typography): Short text folding problem in special scenes

- components/Table/table.tsx
Close: https://github.com/arco-design/arco-design/issues/1154
> fix: Table hook deps

- components/Table/table.tsx
Table的onChange在pagination触发时无法拿到最新的状态
用组件库中生成的onPaginationChange替换用户传入pagination的onChange，并消除循环引用
|    Table       |  修复 `Table` 组件 `onChange` 回调参数更新不及时的bug  | Fix the bug that the `onChange` callback parameter of the `Table` component is not updated in time |   Closed: #1147    |
> fix(Table): pagination onchange

- site/src/widget/Body/index.jsx
- site/src/widget/Menu/index.jsx
> docs: redirect /react to /react/docs/start

- .config/webpack.config.js
- scripts/init.sh
- site/config/pwa.js
- site/package.json
- site/src/index-en.js
- site/src/index.js
- site/src/serviceWorker.js
- site/src/serviceWorkerRegistration.js
- site/yarn.lock
add add pwa support for react docs
> chore: add add pwa support for react docs

- site/src/index-en.js
- site/src/index.js
> chore: update notification text

- components/Alert/__test__/__snapshots__/demo.test.ts.snap
- components/Alert/index.tsx
|    Alert       |      修复点击 `Alert` 组件的关闭按钮误触外部 `form` 的 `submit` 事件的 bug。  |      Fixed a bug where clicking the close button of an `Alert` component accidentally triggered the `submit` event of an external `form`.   |           Close:  #1189      |
> fix: Alert close button should have type='button'

- components/Table/__test__/columns.test.tsx
- components/Table/__test__/components.test.tsx
- components/Table/__test__/expand.test.tsx
- components/Table/__test__/filter.test.tsx
- components/Table/__test__/fixed-columns.test.tsx
- components/Table/__test__/group-columns.test.tsx
- components/Table/__test__/index.test.tsx
- components/Table/__test__/pagination.test.tsx
- components/Table/__test__/selection.test.tsx
- components/Table/__test__/sorter.test.tsx
- components/Table/__test__/summary.test.tsx
- components/Table/__test__/virtualized.test.tsx
> test: upgrade Table tests

- site/src/App.js
- site/src/index-en.js
- site/src/index.js
- site/src/pages/customer/sections/Banner/style/iconWall.module.less
- site/src/pages/customer/sections/Customers/styles/index.module.less
- site/src/pages/home/components/EditorSkin/style/index.module.less
- site/src/pages/home/components/StartBtn/style/index.module.less
- site/src/pages/home/content/Token/index.module.less
- site/src/pages/home/context.ts
- site/src/pages/home/sections/Banner/style/content.module.less
- site/src/pages/home/sections/Ecosystem/components/block/index.module.less
- site/src/pages/home/sections/Ecosystem/components/blockList/index.module.less
- site/src/pages/home/sections/QuickStart/index.tsx
- site/src/pages/home/sections/QuickStart/style/index.module.less
- site/src/pages/home/sections/Resource/components/Card/index.module.less
- site/src/pages/home/sections/Resource/components/Card/index.tsx
- site/src/pages/home/sections/Resource/components/DesignValues/index.module.less
- site/src/pages/home/sections/ShowCase/components/Card/index.tsx
- site/src/pages/home/sections/Teams/index.tsx
- site/src/pages/home/sections/Teams/style/index.module.less
- site/src/style/index.less
- site/src/style/markdown.less
- site/yarn.lock
> homepage: support rtl

- components/Trigger/index.tsx
- components/Trigger/portal.tsx
|    Trigger       |   修复 `Trigger` 组件在 React 18 严格模式下弹出层无法显示的 bug。            |         Fixed a bug where the `Trigger` component could not display the popup in React 18 strict mode.      |                |
> fix: trigger can not work in react 18 strictmode

- components/TimePicker/README.en-US.md
- components/TimePicker/README.zh-CN.md
- components/TimePicker/interface.tsx
- components/TimePicker/picker.tsx
|     TimePicker      |      添加`triggerElement`属性支持自定义触发器         |         add `triggerElement` prop to support custom trigger element      |           Close: #1195      |
> feat(TimePicker): support custom trigger element

- components/Link/__test__/__snapshots__/demo.test.ts.snap
- components/Link/index.tsx
- components/Link/style/index.less
- components/Menu/style/index.less
- components/Select/style/index.less
- components/Select/style/token.less
- components/TreeSelect/__demo__/onSearch.md
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/__test__/index.test.tsx
- components/TreeSelect/hook/useStateValue.ts
|      TreeSelect     |     修复 `TreeSelect` 组件在受控模式下开启复选框多选且远程搜索时，已选中项存在 label 未正常展示的 bug。           |      Fixed a bug where the label of the selected item was not displayed properly when the `TreeSelect` component enabled multiple checkbox selection and remote search in controlled mode.         |      Close #1196           |
> fix(treeSelect): label displayed error

- components/Select/select.tsx
- components/Table/__demo__/expandprops.md
- components/Table/tbody/tr.tsx
Close: https://github.com/arco-design/arco-design/issues/1200
> enhance: Table expandProps.icon

- components/Table/style/index.less
- components/Table/style/index.ts
- components/Table/summary/row.tsx
- components/Table/table.tsx
- components/Table/tbody/td.tsx
- components/Table/tbody/tr.tsx
- components/Table/thead/column.tsx
- components/Table/thead/index.tsx
- site/public/index.ejs
|   Table  |  `Table` 组件支持 rtl 样式。    | Component `Table` add rtl style.   |                |
> style: Table add rtl style

- components/DatePicker/panels/date/index.tsx
|      RangePicker     |         修复 `RangePicker` 点击头部月份再点击年份无响应的问题。      |        Fix `RangePicker` can't change mode from month to year.       |                |
> fix: rangepicker change mode setpanelmode is undefined

- components/Image/__test__/preview.test.tsx
- components/Image/image-preview-group.tsx
- components/Image/image-preview.tsx
- components/Image/image.tsx
- components/Image/previewGroupContext.ts
|  Image   | 修复 Image.Preview 回调函数在打开预览不触发的问题。`Image.Preview` 受控逻辑优化，通过 `visible` 和 `onVisibleChange` 可以进行受控展示/关闭。**`Image.Preview`组件 内部不再更改 `visible` 的状态**  |  Fix `Image.Preview` callback function not triggering when preview is opened. Image.Preview controlled logic optimization, controlled display/close through `visible` and `onVisibleChange`. **Inside the `Image.Preview` component no longer changes the state of `visible`** | Closed: #1145 |
> fix(Image.Preview): fix the controlled logic for visible

- components/Image/image-preview.tsx
Image.Preview controlled scene in not set props.visible
> fix: image-preview controlled scene in not set props.visible

- components/Mentions/__test__/__snapshots__/demo.test.ts.snap
- components/Mentions/__test__/__snapshots__/index.test.tsx.snap
- components/Mentions/index.tsx
|  Mentions | 修复 `Mentions` 组件下拉弹窗出现时的位置抖动。  |   Fix the position jitter when the `Mentions` dropdown popup appears.   |                |
> fix: Mentions popup jitter

- package.json
- scripts/dependencies.sh
> chore: add dependencies scripts

- components/Image/__test__/index.test.tsx
- components/Image/image.tsx
| Image |  修复 `Image` 组件传入原生属性 `onLoad`, `onError` 不触发的 bug  | Fixed the bug that the `Image` component passed the native property `onLoad`, `onError` was not triggered  |   Closed: #1237   |
> image native attribute onload does not trigger

- components/Upload/util.tsx
|      Upload     |       修复 `Upload` 组件设置`accept=*`时失效的问题        |       fix `accept=*` does not work in `Upload`        |       #1230          |
> fix: fix accept file util

- components/DatePicker/panels/date/index.tsx
- components/DatePicker/picker-range.tsx
- components/DatePicker/picker.tsx
- components/DatePicker/util.ts
|  DatePicker   |  修复 `DatePicker.WeekPicker` 输入框和面板显示的周不一致的 bug。   |   Fix the bug of inconsistent week display between `DatePicker.WeekPicker` input box and panel.    | Close: https://github.com/arco-design/arco-design/issues/1229   |
> fix: DatePicker.WeekPicker locale format error

- components/Transfer/__test__/__snapshots__/demo.test.ts.snap
- components/Tree/__test__/__snapshots__/demo.test.ts.snap
- components/Tree/node.tsx
Tree 在使用treeData参数时，无法标识TreeNode的层级
给TreeNode新增aria-level属性，用来标识层级
> feat: 在Tree中，使用treeData渲染Tree时，为TreeNode添加层级标识

- components/ConfigProvider/__demo__/rtl.md
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/Tabs/style/rtl.less
> docs: ConfigProvider add rtl demo

- components/Form/__test__/setfield.test.tsx
- components/Form/utils.tsx
|      Form     |       修复 `Form` 组件 `setFieldsValue` 传入的值为空数组或空对象时，设置未生效的问题。        |       Fix the bug that form value won't update when the parameter of `setFieldsValue` is empty array or empty object.     |       Close: #1085          |
> fix: iterativelyGetKeys should get all valid key

- components/DatePicker/picker-range.tsx
| DatePicker  | 修复 `DatePicker.RangePicker` 组件在临界情况判断是否超出范围有误的问题。 | Fix the problem that the `DatePicker.RangePicker` component is wrong to judge whether it is out of range in a critical situation.  |  Close: https://github.com/arco-design/arco-design/issues/1255  |
> fix: DatePicker.RangePicker isOutofRange

- components/Table/__test__/case.test.tsx
- components/Table/utils.tsx
|  Table | 修复 `Table` 组件在 data 格式为 `[['1']], ['2']]` 时不能正确渲染的问题。 |  Fixed `Table` component not rendering correctly when data format is `[['1']], ['2']]`. | Close: https://github.com/arco-design/arco-design/issues/1258   |
> fix: Table data item is arrry should render correctly

- components/Tabs/__demo__/position.md
修改文档: Tabs组件position案例中的props为tabPosition
|     Tabs      |       修改position文档的props        |        Modify the props of the position document       |        none        |
> 修改文档: Tabs组件position案例中的props为tabPosition

- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Collapse/item.tsx
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/InputTag/__test__/__snapshots__/demo.test.ts.snap
- components/List/__test__/__snapshots__/demo.test.ts.snap
- components/Pagination/__test__/__snapshots__/demo.test.ts.snap
- components/Pagination/__test__/__snapshots__/index.test.tsx.snap
- components/Pagination/page-item.tsx
- components/Pagination/style/index.less
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Tag/__test__/__snapshots__/demo.test.ts.snap
- components/Tag/index.tsx
- components/Tag/style/index.less
- components/Transfer/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/Trigger/__test__/__snapshots__/demo.test.ts.snap
- components/_util/hooks/useKeyboardEvent.ts
|     Pagination      |     `Pagination` 组件支持通过键盘事件切换页码         |    `Pagination` supports switching page numbers via keyboard events           |                |
|     Collapse      |     `Collapse` 组件支持通过键盘事件切换当前面板选中         |    `Collapse` supports switching the current panel selection via keyboard events      |                |
|     Tag      |     `Tag` 组件支持通过键盘事件关闭标签         |    `The `Tag` component supports closing tags via keyboard events      |                |
> enhancement:  pagination , Collapse, tag  keyboard events

- components/Image/README.en-US.md
- components/Image/README.zh-CN.md
- components/Image/__test__/preview.test.tsx
- components/Image/__test__/previewGroup.test.tsx
- components/Image/image-preview-group.tsx
- components/Image/image-preview.tsx
- components/Image/image.tsx
- components/Image/interface.ts
- components/Image/previewGroupContext.ts
- components/Tag/style/index.less
- stories/Image.story.tsx
| Image  | `Image.Preview` 新增 `imgAttributes` 参数，将属性透传至弹窗中的 `img` 标签上 |  `Image.Preview` adds the `imgAttributes` parameter to transparently transmit the properties to the `img` tag in the preview modal   |   Closed: #1117   |
> feat(Image.Preview): Image.Preview support imageProps

- components/DatePicker/picker-range.tsx
- components/DatePicker/style/index.less
- stories/DatePicker.story.tsx
|  DatePicker   |  修复 `DatePicker.RangePicker` 组件 `panelRender` 不生效的 bug。  | Fixed the bug that the `panelRender` of the `DatePicker.RangePicker` component did not work.  |                |
> fix: DatePicker panelRender not work

- components/Modal/__test__/useModal.test.tsx
- components/Modal/useModal/index.tsx
| Modal | 修复通过 `useModal` 创建弹窗实例时返回的方法 `update`为 `undefined` 的bug  |Fix the bug that the method `update` returned by `useModal` is `undefined` when creating a modal instance. | Closed: #1287  |
> fix(useModal): the bug that the update function is undefined in the ModalInstance

- site/src/pages/icon/md/__demo__/iconfont.md
> docs: update icon demo

- components/index.tsx
- package.json
- scripts/dependencies.sh
- scripts/generate-version.js
| common | 组件库对外暴露 `version` 字段。  |  Export prop `version`.   | Close: https://github.com/arco-design/arco-design/issues/1284  |
> enhance: export version

- components/Popover/README.zh-CN.md
- components/Tooltip/README.zh-CN.md
- components/Tooltip/interface.ts
> docs(trigger): fix comments

- components/Table/__demo__/table-edit.md
> docs: Talble edit demo change to ts

- components/Cascader/__test__/case.test.tsx
- components/Cascader/util.tsx
|       Cascader    |   优化 `Cascader` 组件多选时对传入的非法格式 `value` 的边界处理            |    Optimize cascader edge case handling           |   #1290              |
> enhancement: Optimize cascader edge case handling

- components/Menu/style/index.less
|   Menu   |  修复 `Menu` 组件内置折叠按钮显示位置出错的 bug  | Fix the bug that the display position of the built-in collapse button of the `Menu` component is wrong  |  Closed: #1321  |
> style: The collapsed button layout error in `LTR` scene

- components/Pagination/__test__/index.test.tsx
- components/Pagination/pagination.tsx
|  Pagination   |   修复 `Pagination` 组件的初始 `pageSize` 与选中的 `sizeOptions` 不一致的 bug。   | Fixed a bug where the initial `pageSize` of the `Pagination` component was inconsistent with the selected `sizeOptions`. |    Closed: #1324     |
> fix: pagination sizeOptions effect pageSize

- components/DatePicker/__test__/range.test.tsx
- components/DatePicker/picker-range.tsx
|  DatePicker  |  修复 `DatePicker.RangePicker` 组件动态修改 `disabled`，禁用日期没有及时更新的 bug。 | Fix the bug that the `DatePicker.RangePicker` component dynamically modifies `disabled`, and the disabled date is not updated in time. |  Close: https://github.com/arco-design/arco-design/issues/1317    |
> fix: DatePicker half disabled

- components/Select/select.tsx
|  Select |  确保 `Select` 组件使用 `dropdownRender` 自定义下拉框内容并获取页面焦点时，键盘快捷键仍然可用。 |  Make sure that the keyboard shortcuts are still available when the `Select` component uses `dropdownRender` to customize the dropdown box content and gets the page focus. |                |
> enhancement: Select hotkey with a custom dropdown-menu

- components/BackTop/__test__/__snapshots__/demo.test.ts.snap
- components/Calendar/__test__/__snapshots__/demo.test.ts.snap
- components/Card/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/__test__/__snapshots__/demo.test.ts.snap
- components/Cascader/__test__/__snapshots__/index.test.tsx.snap
- components/Cascader/cascader.tsx
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/DatePicker/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Image/image.tsx
- components/Input/__test__/__snapshots__/demo.test.ts.snap
- components/Layout/__test__/__snapshots__/demo.test.ts.snap
- components/Menu/__test__/__snapshots__/demo.test.ts.snap
- components/Menu/index.tsx
- components/Menu/sub-menu/inline.tsx
- components/Menu/sub-menu/pop.tsx
- components/Pagination/__test__/__snapshots__/demo.test.ts.snap
- components/Progress/__test__/__snapshots__/demo.test.ts.snap
- components/Progress/circle-progress.tsx
- components/Select/__test__/__snapshots__/demo.test.ts.snap
- components/Select/__test__/__snapshots__/index.test.tsx.snap
- components/Select/select.tsx
- components/Table/__test__/__snapshots__/demo.test.ts.snap
- components/Tabs/__test__/__snapshots__/demo.test.ts.snap
- components/Tabs/tabs.tsx
- components/TimePicker/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
- components/TreeSelect/tree-select.tsx
- components/Trigger/__test__/__snapshots__/demo.test.ts.snap
- components/_util/hooks/useId.ts
| Common | 修复由于自动生成的 DOM `id` 导致的服务端渲染报错的问题。 |  Fix server-side rendering error due to auto-generated DOM `id`. |      Close #958    |
> fix: SSR error caused by global component DOM id

- components/InputTag/style/index.less
|  InputTag   |  `InputTag` 组件 `placeholder` 过长时末尾使用 `...` 展示。  |  When the `placeholder` of the `InputTag` component is too long, it will be displayed with `...` at the end.  |   Close #1335   |
> style: text ellipsis of InputTag's placeholder

- components/Table/__test__/case.test.tsx
- components/Table/hooks/useRowSelection.tsx
|  Table  | 修复 `Table` 组件更新 `data` 之后，下次选中 selectedRows 未及时更新的问题。  |  Fix the problem that after the `Table` component updates `data`, the selectedRows is not updated in time when the selectedRows is selected next time.  | Close: https://github.com/arco-design/arco-design/issues/1294 |
> fix: Table selectedRows, close #1294

- components/locale/de-DE.tsx
|DatePicker| 修复 `DatePicker` 组件在 `de-DE` 语言下会报错的问题。  | Fixed `DatePicker` component error in `de-DE` language.  |  Close: https://github.com/arco-design/arco-design/issues/1346  |
> fix: DatePicker locale de-DE error

- site/src/App.js
- site/src/utils/i18n.js
> site: remove site redirect

- components/Cascader/panel/list.tsx
- components/_class/VirtualList/index.tsx
|  Cascader  |  修复 `Cascader` 组件设置 `expandTrigger` 为 `hover` 时下拉列表的抖动问题。 |    Fixed the jitter of the drop-down list when the `Cascader` component set `expandTrigger` to `hover`.  |   Close #1361   |
> fix: Cascader panel list scrolling

- components/Typography/useCssEllipsis.tsx
- components/Typography/useEllipsis.tsx
|  Typography  |   修复 `Typography` 组件在折叠计算中会出现抖动情况的 bug   |  Fixed a bug where the `Typography` component would jitter in the folding calculation   |    Closed: #1349     |
> fix(Typography): shakes obviously during calculation

- components/Cascader/__test__/case.test.tsx
- components/Cascader/base/node.ts
- components/Cascader/util.tsx
…cted when there are disabled children
|  Cascader         |        修复 `Cascader` 组件存在禁用子节点时，选中半选状态的父节点时无法切换选中状态的 bug。       |  Fixed the bug that when the `Cascader` component has disabled child nodes, when the parent node in the half-selected state is selected, the selected state cannot be switched.             |                |
> fix(Cascader): Parent node cannot switch from half-selected to unselected when there are disabled children

- components/Steps/README.en-US.md
- components/Steps/README.zh-CN.md
- components/Steps/index.tsx
- components/Steps/interface.ts
- components/Steps/step.tsx
|  Steps  |  修复 `Steps.Step` 传入 `onClick` 事件后偶现不触发回调的 bug  | Fix the bug that the callback is not triggered occasionally after `Steps.Step` is passed to the `onClick` event  |   Closed: #1305    |
- [] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
> fix(Steps): Step onClick not triggered

- components/Drawer/index.tsx
- components/Modal/modal.tsx
- components/Popconfirm/index.tsx
- package.json
- stories/Drawer.story.tsx
- yarn.lock
|    Drawer       |      修复 `Drawer` 组件在 `iframe` 内强制锁定焦点导致父页面无法获取焦点的 bug。   |        Fixed a bug where the `Drawer` component was forced to lock the focus inside an `iframe`, causing the parent page to fail to get the focus.       |        close #1353  close #1169        |
|    Modal       |          修复 `Modal` 组件在 `iframe` 内强制锁定焦点导致父页面无法获取焦点的 bug。      |      Fixed a bug where the `Modal` component was forced to lock the focus inside an `iframe`, causing the parent page to fail to get the focus.         |     close #1353  close #1169              |
|    Popconfirm       |     修复 `Popconfirm` 组件在 `iframe` 内强制锁定焦点导致父页面无法获取焦点的 bug。           |      Fixed a bug where …
> fix: focuslock default allow cross iframe

- components/Message/index.tsx
- components/Modal/confirm.tsx
- components/Notification/index.tsx
- components/_util/react-dom.ts
|  Common         |    优化 `Modal`, `Notification`, `Message` 组件在 React 18 下通过 `createRoot` 渲染节点。           |      Optimized `Modal`, `Notification`, `Message` components to render nodes via `createRoot` in React 18.         |  close #1130               close #1298 close #|
> enhancement: avoid createRoot warning

- components/Dropdown/style/index.less
- components/Menu/style/index.less
|   Menu    |  优化 `Menu` 组件中内嵌 `<a/>` 的样式。 |  Optimize the style of inline `<a/>` in `Menu` component. |   Close #1318  |
|   Dropdown    |  优化 `Dropdown` 组件下拉菜单中 `Menu` 内嵌 `<a/>` 的样式。 |  Optimize the style of `<a/>` embedded in `Menu` in the dropdown menu of the `Dropdown` component. |   Close #1318  |
> style: enhance style of <a> in Menu.Item

- components/Form/utils.tsx
iterativelyGetKeys example error
no need to test
> fix: iterativelyGetKeys example error

- components/Message/style/index.less
when body set display property to flex
Message component will not visible
set the class '.arco-message-wrapper'  property left to 0
| Message    |  修复 `Message` 在设置了 `body { display: 'flex' }` 的页面中无法正常显示的 bug。  |  Fixed the bug that `Message` could not be displayed properly in pages with `body { display: 'flex' }` set.  |                |
> fix: 修复body设置flex之后message不显示的问题

- components/Drawer/interface.ts
The property `DrawerProps['placement']` should be a union type of supported placement, which provide better DX with Typescript
Change `string` type to `'top' | 'right' | 'bottom' | 'left'` union type
|     Drawer      |      优化 `Drawer` 组件  `placement` 属性的类型。        |     Improve typescript definition of the `placement` property of `Drawer`.         |                |
> refactor: Drawer placement props refactor to union string type

- components/DatePicker/panels/range/index.tsx
- components/DatePicker/picker-range.tsx
Close: https://github.com/arco-design/arco-design/issues/1356
> enhance: DatePicker.RangePicker fix show dates

- components/Breadcrumb/README.en-US.md
- components/Breadcrumb/README.zh-CN.md
- components/Breadcrumb/__test__/index.test.tsx
- components/Breadcrumb/interface.ts
- components/Breadcrumb/item.tsx
- components/Breadcrumb/style/index.less
- stories/Breadcrumb.story.tsx
| Breadcrumb | `Breadcrumb` 新增 `href`, `onClick` 和 `tagName` 属性 | `Breadcrumb` adds `href`, `onClick` and `tagName` properties.  |    Closed: #1347      |
> feat: breadcrumb support link tagName click

- components/Cascader/README.en-US.md
- components/Cascader/README.zh-CN.md
- components/Cascader/__test__/index.test.tsx
- components/Cascader/cascader.tsx
- components/Select/README.en-US.md
- components/Select/README.zh-CN.md
- components/Select/__test__/index.test.tsx
- components/Select/select.tsx
- components/TreeSelect/README.en-US.md
- components/TreeSelect/README.zh-CN.md
- components/TreeSelect/__test__/index.test.tsx
- components/TreeSelect/tree-select.tsx
- components/_class/select-view.tsx
|  Select |  `Select` 组件支持监听 `onKeyDown` 回调。   |  The `Select` component supports listening to the `onKeyDown` callback.  |    Close #1291  |
|  TreeSelect |  `TreeSelect` 组件支持监听 `onKeyDown` 回调。   |  The `TreeSelect` component supports listening to the `onKeyDown` callback.  |                |
| Cascader |  `Cascader` 组件支持监听 `onKeyDown` 回调。   |  The `Cascader` component supports listening to the `onKeyDown` callback.  |                |
> feat: support onKeyDown callback for Select/TreeSelect/Cascader

- components/Dropdown/style/index.less
- components/Menu/style/index.less
> style: enhance the style of <a/> in MenuItem

- components/Form/__demo__/register.md
- components/Form/__test__/__snapshots__/demo.test.ts.snap
- components/Form/__test__/case.test.tsx
- components/Form/__test__/dym.test.tsx
- components/Form/__test__/form.test.tsx
- components/Form/__test__/index.test.tsx
- components/Form/__test__/list.test.tsx
- components/Form/__test__/provider.test.tsx
- components/Form/__test__/shouldUpdate.test.tsx
- components/Form/__test__/use.test.tsx
- components/Form/__test__/validate.test.tsx
- components/Form/control.tsx
- components/Form/interface.tsx
- components/Form/utils.tsx
- components/_util/warning.ts
- components/index.tsx
|     Form      |  `Form.Item` 支持 `dependencies` 属性             |  `Form.Item` supports the `dependencies` property             |   close #1008              |
> feat: Form supports dependencies

- components/Grid/README.en-US.md
- components/Grid/README.zh-CN.md
- components/Grid/col.tsx
- components/Grid/interface.ts
- components/Grid/row.tsx
- components/Grid/style/col.less
- components/Layout/README.en-US.md
- components/Layout/README.zh-CN.md
- components/Layout/interface.ts
- components/List/README.en-US.md
- components/List/README.zh-CN.md
- components/List/interface.ts
- components/_util/responsiveObserve.ts
|  Grid |  `Grid` 响应式断点支持 `xxxl` (页面宽度 > 2000px)。  |   `Grid` responsive breakpoints support `xxxl` (width > 2000px).   |                |
> feat: Grid support responsive size xxxl 

- components/Layout/style/index.less
|  Layout  |  修复 `Layout` 亮色主题下可能导致的页面出现滚动的问题。 |  Fixed the issue that could cause the page to scroll under the `Layout` light theme.  |  Close #1384   |
> style: avoid Layout overflow caused by border

- components/Table/utils.tsx
https://github.com/arco-design/arco-design/issues/1369
Data is dynamically obtained from the server. Generate columns based on data. The properties of the objects in the data are uncertain, so the dataIndex property used by the generated column may be the same as the default value of the `childrenColumnName` property of the Table component. As a result, the `travale` method in the `deepCloneData` method thinks that this is a tree data display. Then recursively call the `travel` method and pass a non-array parameter resulting in an error.
There are two solutions:
The first: use `Symbol.for()` to specify the `childrenColumnName` property of the Table component to ensure uniqueness, which will not be the same as the dataIndex of the dynamically generated columns. But this solution is not …
> fix: solve the error when the Table component clones the data

- components/ConfigProvider/README.en-US.md
- components/ConfigProvider/README.zh-CN.md
- components/ConfigProvider/__demo__/local-setting.md
- components/ConfigProvider/__demo__/rtl.md
- components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap
- components/ConfigProvider/index.tsx
- components/ConfigProvider/interface.ts
- components/Message/__demo__/useMessage.md
- components/Message/__test__/__snapshots__/demo.test.ts.snap
- components/Message/__test__/useMessage.test.tsx
- components/Message/index.tsx
- components/Message/useMessage.tsx
- components/Modal/useModal/index.tsx
- components/Notification/__demo__/useNotification.md
- components/Notification/__test__/__snapshots__/demo.test.ts.snap
- components/Notification/__test__/useNotification.test.tsx
- components/Notification/index.tsx
- components/Notification/useNotification.tsx
- components/_class/notification.tsx
- components/_util/contextHolder.tsx
|  Message  |  `Message` 组件支持 `useMessage` 用法以便读取 `context`  | `Message` component supports `useMessage` usage for reading `context`  | Closed: #1340     |
|  Notification  |  `Notification` 组件支持 `useNotification` 用法以便读取 `context`  | `Notification` component supports `useNotification` usage for reading `context`  |   |
> feat: support useMessage, useNotification

- components/Form/__test__/case.test.tsx
- components/Form/__test__/validate.test.tsx
- components/Form/hooks/useWatch.ts
|    Form       |      修复 `Form.useWatch` 在 `field` 改变时，返回值未及时更新的 bug。      |      Fix the bug that the return value of `Form.useWatch` is not updated in time when `field` changes         |      close #1343           |
> fix: form watch value not work when field change
