site/src/style/index.less, stories/index.stories.js
Update less content when `yarn start`, the site style cannot be updated automatically.
Import the less file of dist files, not the css file.
=> chore: fix style can not auto update in dev mode

components/Avatar/group.tsx
closes #88 
|Avatar|修复 `Avatar` 组件设置 `maxCount = 0` 时头像全部展示的问题。|Fix the bug that the `Avatar` component still show all avatars when set `maxCount = 0`.|close #88|
=> fix: avatar group shows +x when maxCount equals 0

components/Form/__demo__/shouldUpdate.md
The current [example of nested Form.Item](https://arco.design/react/components/form#%E5%B5%8C%E5%A5%97%E6%8E%A7%E4%BB%B6) uses `noStyle={{showErrorTip: true}}` and `Grid.Row` to achieve the effect of two fields in one line, but with `noStyle={{showErrorTip: true}}` when both fields have errors, the errors are elevated to the parent `Form.Item`. It leads to a stacking of error messages that is not user-friendly. `Grid.Row` with a normal `Form.Item` can achieve the same effect, and the error message will appear under the corresponding `Form.
A sample of the modified version can be found at https://codepen.io/ignorancew/pen/vYJdrXw?editors=001.
=> docs: Modify the nested Form.Item example to make the error message more user-friendly.

components/Typography/__demo__/ellipsis-controlled.md, components/Typography/__demo__/ellipsis.md, components/Typography/__test__/__snapshots__/demo.test.ts.snap
Flex will affect the width of the child element, causing the child element to not occupy all the space
Manually add the style `width: 100%`, add a flex scene to the demo on the `Typography` component.
=> feat: add a ellispsis in flex scene demo

components/Tabs/__demo__/drag.md, stories/components/Tab.jsx
Tabs component drag example error `Cannot have two HTML5 backends at the same time`
[react-dnd-issue](https://github.com/react-dnd/react-dnd/issues/186)
=> fix: the tabs darg demo

components/Menu/README.en-US.md, components/Menu/README.zh-CN.md, components/Menu/index.tsx, components/Menu/interface.tsx, components/Menu/overflow-wrap.tsx, components/Menu/style/index.less
Allow user to forbid horizontal Menu auto-wrap when items overflow.
Add  a new property `ellipsis`.
| Menu | `Menu` 新增 `ellipsis` 属性以支持禁用水平菜单的菜单项自动折叠功能  |  `Menu` adds property `ellipsis` to forbid the automatic folding of menu items |  #60   |
| Menu | 修复 `Menu` 因为读取 `null` 的属性导致报错的 bug | Fix the bug that `Menu` caused an error because of reading an property of `null` | #101  |
=> Menu add property ellipsis

site/src/style/page.less
When browsing on mobile device, the heading of docs that has 'ac-nav-intro' class is messy. 
- iPhone 11 iOS15.0.1
- Safari
=> fix: The site page title compatible mobile media

components/Trigger/index.tsx
|      Trigger     |    修复 `Trigger` 组件在弹出层出现动画结束前错误触发弹出层鼠标事件的 bug。           |   Fixed a bug where the 'Trigger' component incorrectly triggered the pop-up mouse event before the animation ended.            |        close #126         |
=> fix: Trigger prevents mouse events before entered

components/Menu/__test__/index.test.tsx, components/Menu/item-group.tsx, components/Menu/item.tsx, components/Menu/sub-menu/inline.tsx, components/Menu/util.ts, components/Progress/interface.ts, components/Progress/line-progess.tsx
`Menu.SubMenu`'s own properties should have the highest priority which should not be inherited from its parent.
Change `{ ...parentProps }` to `{ ...parentProps, ...selfProps }`.
Add a new test case for it.
| Menu |  `Menu.SubMenu` 组件修复嵌套使用时，内层 `SubMenu` 属性被父 `SubMenu` 覆盖的 bug。    |   `Menu.SubMenu` component fixes the bug that the inner `SubMenu` property is overridden by the parent `SubMenu` when used in nesting.     |                |
=> fix: Menu.SubMenu's property priority is wrong

components/Menu/style/index.less
Hide the text after icon when Menu is collapsed.
| Menu | `Menu` 组件折叠时隐藏菜单项图标后的文字，避免出现 `...` 。  |  Hide the text behind the menu item icon when the `Menu` component is collapsed to avoid display `...`. |                |
=> style: MenuItem hide text after icon when Menu is collapsed

components/Select/option.tsx, components/Select/select.tsx
Users can not define Select's popup max height in css files.
Remove the inline style `max-height: 200px` in Select's popup container.
| Select | `Select` 修复用户无法在 CSS 文件中覆盖弹窗高度的问题。     |    `Select` fixes the problem that users cannot cover the height of the pop-up window in the CSS file.    |                |
| Select | `Select` 修复单选时虚拟列表定位异常的 bug。 | `Select` Fix the problem of abnormal positioning of virtual list in single mode. | |
=> enhancement: Select allow user to define popup's max height in css files

components/_util/resizeObserver.tsx
ResizeObserver can not get latest react state value in `onResize` callback.
| ResizeBox | 修复 `ResizeBox.Split` 组件切换 `direction` 时，两侧面板比例发生改变的 bug。|  Fix the bug that the ratio of the panels changes when the `ResizeBox.Split` component switches the `direction`. |                |
=> fix: ResizeObserver can not get latest react state in onResize callback

components/Table/interface.tsx, components/Table/table.tsx, components/Table/tbody/index.tsx
| Table  | 修复 `Table` 组件在开启 `virtualized` 之后，当滚动条始终显示时表头出现错位的样式问题。  | Fix the style problem that the header of the `Table` component is misplaced when the scroll bar is always displayed after the `virtualized` is turned on.  | Close: https://github.com/arco-design/arco-design/issues/34 |
=> style: Table virtualized scroll bar style

components/Slider/index.tsx, components/Slider/input.tsx
CLOSE #198 
- change value on input blur instead of on input change
https://user-images.githubusercontent.com/27187946/142857686-fbd34fc0-3d5d-4e32-8b23-441929027a4e.mp4
- if initial value is `[0, 0]`, there is a bug using input to change slider
add unit test if needed
|      Slider     |     Bug fix          |      Bug fix         |        #198         |
=> fix(slider): slider wrong update value with two input case

components/AutoComplete/index.tsx, components/AutoComplete/interface.ts
Add a new parameter of `onPressEnter` callback.
| AutoComplete |  `AutoComplete` 组件 `onPressEnter` 回调新增 `activeOption` 参数以区分回车键按下时下拉列表是否存在激活的选项。 | `AutoComplete`'s property `onPressEnter` adds the `activeOption` parameter to distinguish whether there is an active option in the drop-down list when the Enter key is pressed. | #197  |
=> enhancement: AutoComplete onPressEnter add a new parameter activeOption

components/Tree/animation.tsx
| Tree | 修复 `Tree` 组件在展开后没有子节点场景下，无法再收起的bug  | Fix the bug that the `Tree` component can no longer be collapsed when there is no child node after expansion |  #222  |
=> fix: the timing of tree onExpandEnd trigger

components/Select/README.en-US.md, components/Select/README.zh-CN.md, components/Select/interface.tsx, components/Select/select.tsx, components/Select/utils.tsx
`renderFormat` callback's parameter `value` should be an object when `labelInValue` is `true`.
| Select | `Select` 组件修复 `renderFormat` 回调在设置 `labelInValue` 时，其参数未返回对象的 bug。 |  `Select` fixes the bug that the parameter of the `renderFormat` callback does not return an object when the `labelInValue` is `true`.   |                |
=> fix: Select callback's parameter enhancement when labelInValue is true

components/Progress/style/index.less, components/Progress/style/token.less, components/Upload/trigger-node.tsx, components/Upload/upload.tsx, components/Upload/uploader.tsx
|   Upload       |        修复 `Upload` 组件上传文件夹时，`beforeUpload` 的第二个参数未获取到本次上传的全部文件的 bug。       | Fix the bug that when the `Upload` component uploads a folder, the second parameter of `beforeUpload` does not get all the files uploaded this time.              |         close #242        |
=> fix: upload directory excute beforeUpload

components/Typography/utils.tsx
| Typography | 修复 `Typography`组件设置`showTooltip`后不生效的bug。  |  Fix the bug that the `Typography` component does not take effect after setting `showTooltip`.  | Close #248  |
=> fix: typography 折叠判断镜像dom的setAttribute style 错误

components/Input/input-element.tsx
Reverts arco-design/arco-design#250
=> Revert "fix: 事件绑定在icon上，hover时候点击边缘位置时，无法清空value。应绑定在icon外层的icon-hover的上"

components/Form/__test__/validate.test.tsx, components/Form/control.tsx, components/Form/form-item.tsx, components/Form/interface.tsx, components/Form/style/status.less
|   Form        |     修复 `Form` 组件教验通过时表现出 `warning` 样式的 bug。          |   Fix the bug that the `warning` style of the `Form` component is shown when the teaching experience is passed.          |  close #279                |
=> fix: Form validate status bug

components/Cascader/panel/list.tsx
|     Casader      |      修复 `Cascader` 在多选且父子节点不关联时，选中父节点触发了 `loadMore` 的 bug。         |         Fix the bug that `loadMore` is triggered by selecting the parent node when `Cascader` is multiple-selected and the `changeOnSelect` is true.      |           close #285      |
=> fix: cascader value repeat  when changeOnSelect is true

components/Typography/base.tsx, components/Typography/edit-content.tsx, components/Typography/interface.tsx, components/Typography/operations.tsx, components/Typography/utils.tsx, stories/components/Typography.jsx
…tiple children while add ,
|  Typography  | 修复 `Typography` 在国际化场景下折叠计算结果出错的 bug。  | Fix the bug that the calculation result of `Typography` is incorrectly when ellipsised in the international scene |   Close  #287   |
|  Typography  | 修复 `Typography` 对包裹多个动态字符串并 `copyable` 时，复制结果出错的 bug。 |Fix the bug that the copy result is wrong when `Typography` wraps multiple dynamic strings and `copyable` |                |
=> fix: Typography locale config effect ellipsis , multiple children

components/Slider/index.tsx, components/Typography/interface.tsx
| Slider  |  修复 `Slider` 组件的 `onAfterChange` 参数没有被更新的 bug。 | Fix the bug that the `onAfterChange` parameter of the `Slider` component is not updated.  |    Close  #291     |
=> fix: slider onAfterChange value not update

components/Form/style/status.less
| Form  |  修复在带有 `validateStatus` 的 `Form.Item` 中，`InputTag` 没有校验样式的问题。 |  Fix the problem that there is no validated style when `InputTag` is used in `Form.Item` with `validateStatus`.  |                |
=> style: fix InputTag style in FormItem with validateStatus

components/Progress/style/index.less
class name was mistakenly changed in commit `74ddf06b51379770b8c70e644c4fc397177efe9e`
leading to `success` status of `<Progress />` not displaying correctly
fixes [https://github.com/arco-design/arco-design/issues/343](url)
restore the original class name
setting `status="success"` displays the right green colour again
=> fix: progress css classname mistakenly renamed

components/Select/__test__/index.test.tsx, components/Select/select.tsx
| Select | `Select` 修复允许创建选项时，被禁用的选项可以被通过用户输入的方式被选中的 bug。  |  `Select` fixes the bug that disabled options can be selected by user input when `allowCreate = true`. |   Close #370    |
=> fix: Select allowCreate may change disabled options by user input

components/Divider/style/index.less, components/Slider/README.en-US.md, components/Slider/README.zh-CN.md, components/Slider/__test__/index.test.tsx, components/Slider/index.tsx, components/Slider/interface.tsx
The DOM rendering order of the Mark node of `Slider` may be inconsistent with the UI cause style like `:first-child` not works as expect.
| Slider | 修复 `Slider` 的 Mark 节点在 DOM 中的渲染顺序可能与 UI 不一致的问题。 | Fix the problem that the DOM rendering order of the Mark node of `Slider` may be inconsistent with the UI. |                |
=> fix: Slider should render the DOM in the same order as UI display

components/Table/__test__/filter.test.tsx, components/Table/table.tsx
| Table | 修复 `Table` 组件筛选在受控模式下，`filteredValue` 设置为 `undefined` 不能重置的 bug。 | Fix the bug that the filter of the `Table` component cannot be reset when the `filteredValue` is set to `undefined` in the controlled mode.  | Close: https://github.com/arco-design/arco-design/issues/369|
=> fix: Table filter control mode set filteredValue to undefined to reset

components/Menu/index.tsx
| Dropdown |  修复 `Dropdown` 中的 `Menu` 无法通过 `style` 设置宽度的问题。 | Fix the bug that the width of `Menu` in `Dropdown` cannot be set by `style`.   | Close #393  |
=> fix: Menu in Dropdown can not set width by style.width

components/Transfer/README.en-US.md, components/Transfer/README.zh-CN.md, components/Transfer/index.tsx, components/Transfer/interface.tsx, components/Transfer/list.tsx
| Transfer | `Transfer` 支持为 `showSearch` 属性传入 `InputProps`，支持将搜索框渲染至标题区域。 | `Transfer` supports passing `InputProps` to `showSearch`. |  Close #383  |
=> feat: Transfer supports passing InputProps to showSearch

components/Input/__test__/index.test.tsx, components/Input/input-element.tsx
|     Input      |     修复 `Input` 组件在输入中文并直接选中自动补全选项时，未触发 `onChange` 的 bug。          |      Fix the bug that the `onChange` is not triggered when the `Input` component enters Chinese and selects the auto-completion option directly.         |      Close #395           |
=> fix: Input composition error

components/Carousel/index.tsx
| Carousel | 修复 `Carousel` 当 `currentIndex` 设置为非 0 时，首次翻页动画异常的问题。 |  Fix the bug that Carousel's first page switch animation is abnormal when `currentIndex` is set to non-zero.  |  Close #404   |
=> fix: Carousel's first page switch animation is abnormal when currentIndex is set to non-zero

components/Select/interface.tsx, components/Select/option.tsx
See #418 
make children optional in Select.Option
|Select.Option| 支持无 Children |  allow no children        |   #418     |
=> make children of Select.Option optional 

components/Form/__test__/form.test.tsx, components/Form/control.tsx, components/Form/form-label.tsx, components/Form/form.tsx, components/Form/utils.tsx
|      Form     |  修复 `Form` 组件的 `scrollToFirstError` 属性在设置了 `noStyle` 的表单项上失效的 bug。            |    Fixed the bug where the `scrollToFirstError` property of the `Form` component did not work on form items with `noStyle` set.           |       close #430         |
=> fix: form scrollToFirst not work

components/Image/image-preview-group.tsx, components/Image/image-preview.tsx, components/Image/image.tsx, components/Image/previewGroupContext.ts, stories/components/Image.jsx
| Image |  修复 `Image.PreviewGroup` 在子节点的 `src` 更新后预览顺序出错的bug。  |  Fix the bug that the preview order of Image.PreviewGroup is wrong after the src of the child node is updated.   |  Close: #375   |
=> fix: image preview index

components/Typography/__test__/index.test.tsx, components/Typography/utils.tsx, stories/components/Typography.jsx
| Typography  | 修复 `Typography` 组件在浏览器缩放场景下折叠出错的bug  |  Fixed the bug that the `Typography` component was folded incorrectly in the browser zoom scene.  |    |
=> fix: The ellipsis calculation of typography in the zoom scene is wrong

components/InputTag/input-tag.tsx
|  InputTag  | `InputTag` 阻止回车时提交表单。 | `InputTag` prevents form submission on `Enter` pressed. |   Close: #469      |
=> fix: InputTag prevent enter key to submit form

components/Timeline/interface.ts
Solves Type Error (Timeline): mode type definition missing "top" and "bottom".
Reproduce: https://codesandbox.io/s/sweet-bhaskara-wezit?file=/src/App.tsx
1. 经过测试，确定 'top' 和 'bottom' 都是mode属性的有效值，因此在mode的类型定义中中增加了这两项：
```typescript
mode?: 'left' | 'right' | 'top' | 'bottom' | 'alternate' ;
```
2. 根据 `components/Timeline/item.tsx` 的[实现](https://github.com/arco-design/arco-design/blob/279aa9abdd4323357562243af6f4a53f4a508db9/components/Timeline/item.tsx#L63)，推断了在 `direction === 'horizontal'`的情况下，mode的默认值是 'top'。因此在jsdoc中补充了这一点：
```typescript
@defaultValue left(vertical) | top(horizontal)
```
Added "top" and "bottom" into type definition of "mode"
| Timeline  |  修复了 …
=> fix(Timeline): add missing values in type definition

components/Image/image-preview.tsx
…rm cache
|     Image      |      修复 `Image.Preview` 组件在从缓存中加载图片的时候 `onload` 没有触发的问题         |      Fixed `Image.Preview` component `onload` not triggering when loading images from cache         |                |
=> fix(image): fix the problem that onload not be triggered when load form cache

components/InputNumber/index.tsx
See #563
Added condition `targetValue === '.'` so that `.` can be handled correctly.
Manual Testing: Tried to reproduce the error mentioned in #563, and it does not happen again. 
Automated testing: `yarn test`
| InputNumber |修复 `InputNumber` 组件小数点特定情况下无法删除的 bug。| Fix the bug in `InputNumber` where decimal point is handled incorrectly |    #563   |
=> fix(InputNumber) '.' not handled correctly #563

components/Input/input-element.tsx
|  Input  | 修复 `Input` 组件粘贴文本并清空之后，无法再次粘贴同样文本的 bug。   |   Fixed a bug where the same text could not be pasted again after the `Input` component pasted text and cleared it.  |     Close: #575     |
=> fix: Input can not paste the same text after clear

components/Cascader/cascader.tsx, components/Cascader/panel/list.tsx, components/Cascader/util.tsx, components/Select/__demo__/render-format.md, components/Tree/style/index.less, components/Tree/style/token.less, site/docs/version_v2.en-US.md, site/docs/version_v2.zh-CN.md
|  Cascader         |    修复 `Cascader` 组件在受控时偶发复选框选中状态和传入 `value` 不一致的bug。           |      Fixed a bug where the checked state of the `Cascader` component was occasionally inconsistent with the incoming `value` when it was controlled.         |        Close #572         |
=> fix: cascader checkbox status is not controled

components/Table/__test__/columns.test.tsx, components/Table/tbody/td.tsx
|    Table       |   `placeholder` 属性在`Table` 数据为空字符或者 null 生效          |    `placeholder`   attributes take effect when `Table` data is an empty string or null         |       Close: [#606](https://github.com/arco-design/arco-design/issues/606)         |
=> fix(table): placeholder can apply if the data is an empty string or null

components/Cascader/__test__/index.test.tsx, components/Cascader/cascader.tsx, components/Cascader/util.tsx
|      Cascader     |      修复 `Cascader` 组件单选时，第一次触发 `onChange` 时的第二个参数未传递当前选中节点信息的 bug。         |    Fixed the bug that the second parameter of `onChange` was not passed the information of the currently selected node when the `Cascader` component was single-selected for the first time.           |                close #596 |
=> fix: cascader parameter error

components/Cascader/cascader.tsx
|     Cascader      |     修复 `Cascader` 组件在直接输入文本远程搜索时，组件默认值对应的 label  文本显示丢失的问题。        |   Fix the problem that the label text corresponding to the default value of the component is lost when the `Cascader` component is directly input text for remote search            |        Close #632         |
=> fix: cascader lost label text when onSearch & defaultValue

components/Input/__test__/index.test.tsx, components/Input/input-element.tsx, components/Input/input.tsx
|    Input       |  修复 `Input ` 同时设置  allowClear 和 readOnly 属性时, 依然展示清除按钮     |    Fixed display of clear button when `Input` allowClear and readOnly at same time     |      Close: [#637](https://github.com/arco-design/arco-design/issues/637)          |
=> fix(input): fix allowClear and readOnly together show the clear button

components/InputTag/__test__/index.test.tsx, components/InputTag/input-tag.tsx
… and readOnly together
|   InpuTag     |  修复 `InputTag`组件同时设置 allowClear 和 readOnly 时, 依然展示清除按钮             |     Fixed InputTag display cleat button when set allowClear and readOnly together          |      Closed: [#649](https://github.com/arco-design/arco-design/issues/649)          |
=> fix(input-tag): fix InputTag display cleat button when set allowClear and readOnly together

.config/docgen.config.js, package.json, yarn.lock
升级 `arco-scripits`，避免 `docgen` 生成文档时提取到 HTML 原生属性。
=> chore: update docgen config to avoid generating property document from HTML element

components/TimePicker/__test__/index.test.tsx, components/TimePicker/time-picker.tsx
修复了即使 `0` 时、`0` 分、`0` 秒被禁用，默认值仍是 `00:00:00` 的问题。
| Before | After |
:-------------------------:|:-------------------------:
| ![Kapture 2022-03-26 at 17 10 38](https://user-images.githubusercontent.com/56376387/160232868-351b729a-6a2d-4b7b-8e67-91975d558f82.gif) | ![Kapture 2022-03-26 at 17 13 50](https://user-images.githubusercontent.com/56376387/160232956-0bc7a47c-3584-418a-845c-27c71b0916b4.gif) |
新增了一个相应的测试用例。
|     Timepicker      |       当 `TimePicker` 组件禁用部分选项时，在点击时自动寻找可用值。        |       When the `TimePicker` component disables some options, it automatically looks for available values on click.        |        close #494       |
=> enhancement(Timepicker): use not disabled value as default

components/Menu/__test__/index.test.tsx, components/Menu/index.tsx, components/Menu/sub-menu/index.tsx, components/Menu/sub-menu/inline.tsx
|  Menu   |  修复 `Menu` 组件 `collapse` 属性变化时，已经展开的子菜单被收起的 bug。   |  Fixed the bug that the expanded SubMenu was collapsed when the `collapse` property of the `Menu` component was changed. |    Close #814        |
=> fix: Menu should keep open keys after collapse/uncollapse

components/Dropdown/index.tsx
|  Dropdown | 修复 `Dropdown` 下拉菜单中的输入框无法被聚焦的 bug。  |  Fixed the bug that input box in the menu of `Dropdown` can not be focused.    |    Close #841     |
=> fix: Dropdown will prevent input element in dropdown menu get focused

components/Dropdown/index.tsx, components/InputNumber/__test__/index.test.tsx, components/InputNumber/index.tsx, components/InputNumber/utils.ts, stories/components/InputNumber.jsx
|   InputNumber      |    `InputNumber` 组件始终使用非科学计数法展示数值。   |  The `InputNumber` component always displays numbers in non-scientific notation.   |     Close #62      |
=> enhancement: InputNumber use non-scientific notation

components/Form/form-item.tsx, components/Form/interface.tsx
When using function as `children` property in `Form.Item` in React 18, there will be a type error:
```
Type '(formData: FormData) => JSX.Element' is not assignable to type 'ReactNode'.ts(2322)
```
Complete `FormItemProps` types
N/A
| Component | Changelog(CN)                                         | Changelog(EN)                                                                  | Related issues |
| --------- | ----------------------------------------------------- | ------------------------------------------------------------------------------ | -------------- |
| Form      | 补全`FormItemProps`中的`children`类型，以兼容React 18 | Complete `children` property type in `FormItemProps`, compatible with React 18 |                |
N/A
=> Optimized function children TS signature in Form.Item component

components/Image/image-preview-group.tsx
多图预览`<Image.PreviewGroup />`使用`current + onChange`受控的情况下不能切换， #877 。
由于是使用`useEffect`依赖于`currentIndex`变化触发的，在`current`受控的情况下使用`setCurrentIndex`，在`re-render`之后由于会被`propCurrentIndex`覆盖掉，所以并不会触发`Effect`，所以解决方案是在`setCurrentIndex`之前即触发`onChange`。
与 https://codesandbox.io/s/ecstatic-tereshkova-s6wlb4?file=/index.js 相同的示例，能够切换图片。
|     Image     |       修复 `<Image.PreviewGroup />`  组件在 `current` 受控时 `onChange` 事件不触发的问题        |      Fixed `<Image.PreviewGroup />` component's `onChange` event not firing when `current` is controlled        |       close #877          |
=> fix: preview switching under current control

components/Form/__test__/useform.test.tsx, components/Form/store.tsx
I noticed that `getFieldValue` and `getFields` behave differently in the `Store` of the `Form` component. The latter performs `cloneDeep` processing on the internal `store` value to ensure that modifications to the return value of the function do not affect the internal `store`, but `getFieldValue` does not.
I thought it was inappropriate for the two methods to behave inconsistently, so fixed it so that `getFieldValue` also did the same as `getFields`, and added a small unit test.
Finally, I fixed the typo in this file a bit and added the missing `React` reference.
I noticed that the `formData` type of `Form` has no reference type, so I added an attribute value on it, and made sure that my modification achieved the expected effect by modifying the value and comparing it.
| Component | …
=> fix(Form/useForm/store): `getFieldValue` should not change the store

.storybook/main.js, components/Menu/indent.tsx, components/Menu/style/index.less
|   Menu  |  修复 `Menu` 组件折叠状态下子菜单标题的图标未展示的 bug。     |  Fixed the bug that the icon of SubMenu title was not displayed when Menu is collapsed.   |                |
=> style: SubMenu icon does not show when Menu is collapsed

components/Dropdown/__test__/index.test.tsx, components/Dropdown/index.tsx
|   Dropdown   |   修复 `Dropdown` 内的 `Menu` 组件 `onMenuItemClick` 的第三个参数 `keyPath` 缺失的 bug。  |   Fixed the bug that the third parameter `keyPath` of `onMenuItemClick` in `Dropdown.Menu` was missing.    |                |
=> fix: Dropdown.Menu's callback onMenuItemClick missing the third argument keyPath

components/Upload/README.en-US.md, components/Upload/README.zh-CN.md, components/Upload/__test__/list.test.tsx, components/Upload/interface.tsx, components/Upload/list/pictureItem.tsx, components/Upload/list/textItem.tsx, components/Upload/list/uploadProgress.tsx, components/Upload/style/index.less, components/Upload/style/token.less, components/Upload/uploader.tsx
|       Upload    |   `Upload` 组件支持通过 `showUploadList.imageRender` 属性渲染图片。          | The `Upload` component supports rendering images via the `showUploadList.imageRender` property.              |      close #884           |
|       Upload    |   `Upload` 组件支持通过 `showUploadList.progressRender` 属性渲染上传进度节点。       |      The `Upload` component supports rendering upload progress nodes via the `showUploadList.progressRender` property.         |      close #884           |
|       Upload    |   `Upload` 组件支持传入函数类型的 `children` 渲染触发上传的节点内容。       |      The `Upload` component supports `children` passed in the function type to render the node content that triggers the …
=> feat: Upload  supports imageRender & progressRender

components/Layout/__test__/index.test.tsx, components/Layout/sider.tsx
#946 中，以及 #937 的评论中，提出了以下问题：
该问题的根本原因是，目前传给 Sider 的 width 属性的值 (`siderWidth`) 的类型是 number，而不是 string。这会导致这个值无法明确指定长度单位，从而只能被浏览器自动 fallback 为 px 。
```javascript
style={{
width: siderWidth, 
}}
```
1. 修改了测试用例，将预期的 width 属性值从 number 改成对应的以 px 为单位的 string。例如，`300`改为`300px`。
2. 对 propsWidth 和 collapsedWidth 都进行类型判定和转换，如果 raw value 是有单位的string，则保持不变，否则加上"px"变成string，使得长度单位更加精确。
通过自动化单元测试，以及手动对组件进行测试，验证了修改后的 `width` 可以支持"rem"等其他单位。
|`Layout.Sider` | 增加 width 属性对 css 单位的支持|  Add CSS units support for width property | #946  |
=> fix(Layout.Sider): Add CSS units support for width property

components/Dropdown/index.tsx
|   Dropdown   |   在 `Dropdown` 的菜单项没有子节点时彻底隐藏弹出菜单。  |   Completely hides the popup menu when the `Dropdown` menu item has no children.    |                |
=> style: Dropdown should hide itself when it's empty

components/Transfer/__test__/__snapshots__/demo.test.ts.snap, components/Transfer/index.tsx, components/Transfer/interface.tsx, components/Transfer/list.tsx, components/Transfer/style/index.less
|   Transfer    |  优化 `Transfer` 组件在 `simple` 模式下对于当前列表选项数目的展示形式。 |  Optimized the display of the `Transfer` component in `simple` mode for the current number of options in the list. |                |
=> enhancement: Transfer header unit-text on simple mode

components/Input/interface.tsx, components/InputNumber/index.tsx, components/Pagination/page-jumper.tsx, components/_util/hooks/useMergeProps.ts
| InputNumber |  修复 `InputNumber` 被 `Input` 的全局配置影响的 bug。 |  Fixed a bug where `InputNumber` was affected by the global configuration of `Input`.  |  Close #1020   |
=> fix: avoid InputNumber being interfered with by Input's global config

components/Input/input.tsx, components/Input/interface.tsx, components/_util/hooks/useMergeProps.ts
|  Input | 修复 `Input` 组件导致的控制台 React Warning(not recognize prop on a DOM element)。 | Fix console React Warning (not recognize prop on a DOM element) caused by `Input` component.  |  Close #1067  |
=> fix: react warning caused by _ignorePropsFromGlobal

components/Modal/modal.tsx
边缘case:
1. 初始化时设置 Modal 的 `visible` 为 true
2. 在 `useEfffect` 时再将 `visible` 设置为 false
3. 由于 `mountOnEnter` 导致动画实际没有触发
4. `wrapperVisible` 由初始化的 `visible` 决定 所以一直为 true
5. 造成页面上有一个 zIndex=1000 的蒙层，下面所有的事件都无法触发
相关issue #1160
=> fix(Modal): bug caused when Modal was hidden immediately after mounting

components/Select/__test__/index.test.tsx, components/Select/select.tsx
| Select | 修复 `Select` 组件 `inputValue` 受控模式下，`onInputValueChange` 回调可能无法触发的问题。 | Fixed an issue where the `onInputValueChange` callback might not be triggered in the `inputValue` controlled mode of the `Select` component. |   Close #1157   |
=> fix: Select onInputValueChange can't be triggered sometimes

components/Select/select.tsx
See  #1156
Note that this problem is only reproducible in NextJS
When `allowCreate === true`, don't display the placeholder
1. Build the changed library with `yarn build`
2. Pack with `yarn pack`
3. Use packed library in a nextjs project created with [arco-next-starter](https://github.com/jiahao-c/arco-next-starter)
4. Manually tested the updated `Select` component. No more flickering "no data" placeholder occurs.
|  Select |   修复 Select 在 `allowCreate` 时下拉框闪烁空状态的问题。  |  Fixed  flickering "no data" placeholder when `allowCreate` in Select. |  Close #1156   |
=> Fix(Select): Fix flickering "no data" placeholder

components/Table/table.tsx
| Table  |  修复在 `Table` 单独传入 `pagination` 后，分页器的 `onChange` 回调不触发的 bug  |Fix the bug that the `onChange` callback of the paginator does not trigger after `Table` is passed to `pagination` alone |      Closed: #1194           |
=> fix(Table): paginationProps onChange callback can't be triggered

components/Carousel/indicator.tsx, components/Carousel/style/index.less, stories/Carousel.story.tsx, stories/tsconfig.json
|  Carousel | 修复 `Carousel` 点击指示器中间的区域时会滑动到第一页的 bug。 |  Fixed the bug that `Carousel` would slide to the first page when clicking in the middle of indicators.  |   Close #1201   |
|  Carousel | 修复 `Carousel` 内的子元素无法撑起组件高度的 bug。 | Fixed the bug that child elements of `Carousel` could not fill up the height of the component.  |    |
=> fix: Carousel shouldn't slide to the first page when click the gap between indicators

components/Cascader/panel/search-panel.tsx
|        Cascader   |      修复 Cascader 组件的搜索面板存在 value 相同的选项时，开启虚拟滚动会出现选项渲染错乱的问题。         |      Fixed the issue that when virtual scrolling is enabled, when options with the same value exist in the search panel of the Cascader component, the options are rendered incorrectly.         |      Close: #1257           |
=> fix(Cascader): options render incorrect when virtualList is enabled  

components/Cascader/__test__/__snapshots__/demo.test.ts.snap, components/Checkbox/__test__/__snapshots__/demo.test.ts.snap, components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap, components/DatePicker/__test__/__snapshots__/demo.test.ts.snap, components/Form/__test__/__snapshots__/demo.test.ts.snap, components/InputTag/__test__/__snapshots__/demo.test.ts.snap, components/InputTag/input-tag.tsx, components/InputTag/style/index.less, components/PageHeader/__test__/__snapshots__/demo.test.ts.snap, components/ResizeBox/__test__/__snapshots__/demo.test.ts.snap, components/Select/__test__/__snapshots__/demo.test.ts.snap, components/Select/__test__/index.test.tsx, components/Space/__test__/__snapshots__/demo.test.ts.snap, components/Tabs/__test__/__snapshots__/demo.test.ts.snap, components/Tag/__test__/__snapshots__/demo.test.ts.snap, components/Tag/__test__/__snapshots__/index.test.tsx.snap, components/Tag/index.tsx, components/Tag/style/index.less, components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap, components/Trigger/__test__/__snapshots__/demo.test.ts.snap
在给 `Tag` 设定了宽度之后，文字省略会失效。
问题原因 [参考](https://css-tricks.com/flexbox-truncated-text/) 。
有两种解决思路：
* 使用 `span` 对用户传入的内容进行包裹，各种情况表现如下：
* 不修改 DOM 结构，使用 `display: inline-block`，但在带有图标的情况下，图标会被挤出可视区域。
综合来看，第一种方案的效果最好，但会增加一层 DOM 结构。
|  Tag  |  修复 `Tag` 组件文本内容超出后未显示省略号的 bug。 |  Fix the bug that the ellipsis is not displayed after the `Tag` component text content exceeds.    |   Close #1262  |
=> fix: text ellipsis of Tag content

components/Cascader/__test__/__snapshots__/demo.test.ts.snap, components/Form/__test__/__snapshots__/demo.test.ts.snap, components/Input/__test__/__snapshots__/demo.test.ts.snap, components/InputTag/input-tag.tsx, components/InputTag/style/index.less, components/Select/__test__/__snapshots__/demo.test.ts.snap, components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap, components/Trigger/__test__/__snapshots__/demo.test.ts.snap, components/_class/select-view.tsx
* 统一 Select 组件单选/多选模式下的右侧箭头样式，避免歧义。
* 在 `style: { width: 'atuo' }` 且为多选模式时 ，避免聚焦后由于 `<input/>` 的 4px 宽度导致的 Select 宽度抖动。仅优化了显式指定 `showSearch = false` 的情况，允许输入的情况下，聚焦之后必须保留输入框的宽度以保证光标可见。
|  Select  |  统一 `Select` 多选和单选模式下的右侧箭头样式。  |  Unify the style of the right arrow in `Select` multi-select and single-select modes.  |   Close #1283  |
=> style: Select use the same ArrowIcon in both single/multiple mode

components/Typography/__demo__/ellipsis-controlled.md, components/Typography/__demo__/ellipsis.md, components/Typography/__test__/__snapshots__/demo.test.ts.snap, components/Typography/base.tsx, components/Typography/interface.tsx, components/Typography/useEllipsis.tsx
- 修复 Typography 省略在特殊场景下（网页自动翻译）时，React 内部报错导致白屏问题。
- 相关 issue: 
- https://github.com/arco-design/arco-design/issues/1185
- https://github.com/facebook/react/issues/17256
- 解决方式:
- 新增 `ellipsis.wrapper` 参数，用户可以传入一个标签，替换 `React.Fragment`。
- 解决方式略牵强，所以 `ellipsis.wrapper` 参数作为内部参数，不在 Api 文档开放。
- 局限：经测验，在 `flex` 布局中，网页翻译仍会报错... 最优解可能还是要等 React 官方修复
=> enhance: typography add ellipsis.wrapper to replace React.Fragment

components/Grid/style/col.less, stories/Grid.story.tsx
|  Grid   |  修复 `Grid.Col` 组件设置 `md = 0` 会导致其在更大的窗口尺寸下也不展示的 bug。  |    Fix the bug that setting `md = 0` in the `Grid.Col` would cause it to not display on larger window sizes.  |   Close #1297      |
=> fix: Grid.Col won't display in larger screen size when it's set md=0

components/Menu/__test__/index.test.tsx, components/Menu/overflow-wrap.tsx
|  Menu  |  优化水平 `Menu` 宽度改变时自动折叠的表现，避免偶发的折行。  | Optimized the behavior of auto-folding when horizontal `Menu` width changes to avoid occasional line breaks.  |  Close #1322 |
=> enhancement: horizontal Menu auto ellipsis might get wrapped in some specific menu-width

components/Input/input-element.tsx, components/InputTag/style/index.less
|  InputTag |  修复 `InputTag` 设置 `disabled` 时 `placeholder` 未按预期展示的 bug。 |  Fixed the bug that `placeholder` was not displayed as expected when `InputTag` was set to `disabled`.  |                |
=> fix: disabled InputTag should also show placeholder

components/Tabs/style/index.less
修复暗黑模式下Tabs组件为type=capsule & disabled时仍有hover效果的问题
修改后的视频：
https://user-images.githubusercontent.com/78004597/188213939-87d3522d-0e67-4f6b-8fd2-03d871040ee9.mp4
|     Tabs      |    修复深色模式下 `capsule` 类型的 `Tabs` 组件中禁用的 `TabPane` 标题区域的 hover 样式。        |   Fix disabled `TabPane` header area hover style in `Tabs` with `capsule` type in dark mode.    |      |
=> update: 修复type=capsule下Tabs disabled option仍有hover效果

components/Statistic/__test__/__snapshots__/demo.test.ts.snap, components/Statistic/index.tsx
| Statistic | 修复 `Statistic` 不传 `prefix` / `suffix` 时，对应 dom 节点仍然渲染的 bug。 |  Fix the bug that the corresponding dom node still renders when `Statistic` does not pass `prefix` / `suffix`|                |
=> enhancement: Statistic skip rendering dom of prefix when suffix is null/undefined

components/Space/index.tsx
| Space |  优化 `Space` 的子元素在被指定的 `key` 值未发生变化时 DOM 节点却重新挂载的问题。  | Optimize the problem that the DOM node of `Space` is remounted when the specified `key` value has not changed.  |  Close #1320   |
=> enhance: avoid Space item mount again caused by react-key overwrite

components/InputTag/input-tag.tsx
似乎是 react-transition-group 存在 bug，具体参考 https://github.com/reactjs/react-transition-group/issues/863。
|   InputTag    |  修复 `InputTag` 组件开启 `dragToSort` 时，切换禁用状态时会将 Tag 重复渲染两遍的 bug。    |   Fixed the bug that when the `InputTag` component has enabled `dragToSort`, the tag will be rendered twice when the disabled state is toggled.  |     Close #1456     |
=> fix: InputTag render children twice due to ReactTransitionGroup

components/Transfer/item.tsx
|  Transfer  |  修复 `Transfer` 开启 `draggable` 时被禁用的选项仍然可以被拖拽的问题。    |  Fix `Transfer` disabled items can still be draggable when `draggable` is enabled.  |   |
=> fix: forbid draging of disabled Transfer items

components/InputNumber/README.en-US.md, components/InputNumber/README.zh-CN.md, components/InputNumber/__test__/index.test.tsx, components/InputNumber/index.tsx, components/InputNumber/interface.ts
#1510
|    InputNumber   |  `InputNumber` 组件 `formatter` 新增参数以标记用户输入状态。     |  The `InputNumber` component `formatter` adds a parameter to mark the user-typing state.  |  Close #1510          |
=> feat: InputNumber formatter add sencond paramter to notify user-typing status

components/TreeSelect/__test__/index.test.tsx, components/TreeSelect/tree-select.tsx
| TreeSelect   |   减少 `TreeSelect` 组件在开启 `retainInputValueWhileSelect` 时重新渲染的次数  |  Reduce the number of times the `TreeSelect` component re-renders when `retainInputValueWhileSelect` is enabled |  Closed:  #1271    |
=> enhance: Remove unnecessary searches in  retainInputValueWhileSelect mode

components/Select/__test__/__snapshots__/demo.test.ts.snap, components/Select/__test__/index.test.tsx, components/_class/select-view.tsx
|  Select  | 修复 `Select` 组件在 `value = ''` 时，错误将 `placeholder` 作为 `value` 展示的 bug。  |   Fixed `Select` component showing `placeholder` as `value` bug when `value = ''`.  |                |
=> fix: Select shows placeholder as value when value is empty string

components/Select/style/mixin.less
缺少 `pointer-events: none` 可能导致绝对定位的 `<input />` 遮挡下边的元素。
=> style: Select's input style when it is invisible

components/Modal/__test__/useModal.test.tsx, components/Modal/useModal/hookModal.tsx, components/Modal/useModal/index.tsx
|  Modal         |   修复 `Modal.useModal` 返回的 `modal.confirm` 在 `useCallback` 中调用时，不显示弹出层的 bug。             |               Fix the bug that the popup layer is not displayed when `modal.confirm` returned by `Modal.useModal` is called in `useCallback`. | close #1621                |
|  Modal         |     修复通过 `Modal.useModal` 创建的弹出层在通过 `update` 方法更新 title 时，icon 丢失的 bug。                       |    Fix the bug that the icon is lost when the title of the popup layer created by `Modal.useModal` is updated by the `update` method            ||
|  Modal         |     修复通过 `Modal.useModal` 创建的弹出层在 onOK 设置为 Promise 时，Promise 中通过 `update` 更新弹出层内容不生效的 bug。          |   Fix …
=> fix: modal hook

components/_util/dayjs.ts
修复 issue: #1630
使用兼容性更好的`day()` api，并使用新的算法计算周开始日期
修复后，使用任意的dayStartOfWeek都正常了。
|  DatePicker  |  修复 `DatePicker` 组件周选择器对 moment.js 的兼容。  | Fix `DatePicker` week selector compatibility with moment.js.  |    Close: #1630   |
=> fix: 修复date-picker周选择器对moment.js的兼容

components/Cascader/panel/search-panel.tsx
|     Cascader      | 修复 `Cascader` 组件远程搜索时，搜索结果面板可能出现空数据的 bug。              |       Fix the bug that empty data may appear in the search result panel when the `Cascader` component searches remotely.        |   close #1634             |
=> fix(cascader): search result empty

components/InputNumber/__test__/index.test.tsx, components/InputNumber/utils.ts
|     InputNumber      |  修复 `InputNumber` 组件传入精度超过 100 (e.g. 1e-200) 的小数时页面崩溃的问题。  |  Fix the page crash issue when the `InputNumber` passes a decimal with a precision greater than 100 (e.g. 1e-200).   |                |
=> fix: avoid Number.toFiexd() error while value's precision is larger than 100

components/Menu/README.en-US.md, components/Menu/README.zh-CN.md, components/Menu/index.tsx, components/Menu/interface.tsx, components/Menu/overflow-wrap.tsx
目前水平菜单(Menu)自动溢出省略状态下写死了 `···` 文本，有很多场景需要自定义这个符号的具体字符，比如使用 `更多` 作为水平溢出省略的自定义文本。这个 PR 就是为了解决这类问题。
Currently the horizontal menu automatic overflow omission state is hard code `···` text, there are many scenarios need to customize the specific characters of this symbol, such as the use of `more` as the horizontal overflow custom text. This PR is designed to solve such problems.
为 Menu 组件增加 `ellipsisText` prop，在 `ellipsis` 开启的时候参考该参数渲溢出的 Submenu，为了避免 break change，该参数的默认值为 `···`。
Add `ellipsisText` prop to the Menu component, and render the overflow Submenu title with this prop when `ellipsis` is turned on. To avoid break change, the default value of this parameter is `···`.
| --------- | ------------- | ------------- | …
=> feat(Menu): allow to customize the text displayed when menu overflows

components/Collapse/__test__/index.test.tsx, components/Collapse/item.tsx
…licked due to bubbling
Collapse onChange is called twice when header icon or title is clicked due to bubbling
Stop click event bubbling
|  Collapse   |    修复 Collapse 点击 header icon 或者 header title 进行展开/折叠时会触发2次 onChange 的 bug。    |     Collapse onChange is called twice when header icon or title is clicked due to bubbling          |     https://github.com/arco-design/arco-design/issues/1722           |
=> fix: collapse onChange is called twice when header icon or title is clicked due to bubbling

components/InputTag/__test__/index.test.tsx, components/InputTag/input-tag.tsx
|  InputTag     |  修复 `InputTag` 组件 `validate` 回调未对 `tokenSeparators` 触发的值更新生效的问题。  |  Fix the issue that `validate` callback of `InputTag` does not take effect for value updates triggered by `tokenSeparators`. |   Close #1758   |
=> fix(InputTag): property validate not work for value updating caused by tokenSeparators

components/InputTag/__test__/index.test.tsx, components/InputTag/input-tag.tsx
|  InputTag   |  修复 `InputTag` 的 `validate` 回调返回非布尔值时，`onChange` 回调中的 `value.label` 值不为用户输入文本的问题。   |   Fix `value.label` value in `onChange` callback is not user input text when `validate` callback of `InputTag` returns non-boolean value.   |                |
=> fix(InputTag): value format of onChange callback when validate result for tokenSeperators is not boolean

components/TimePicker/__test__/index.test.tsx, components/TimePicker/time-picker.tsx
| TimePicker          |   修复 `TimePicker` 组件在传入的 `format` 中存在 `a` 或 `A` 时，`use12Hours` 传 `false` 也会强制开启 12 小时制的 bug。        |   Fix the bug that `use12Hours` passing `false` will also force the 12-hour format to be turned on when `a` or `A` exists in the passed `format` of the `TimePicker` component.  |   Close: https://github.com/arco-design/arco-design/issues/1769  |
=> fix: time-picker use12Hours

components/InputTag/__test__/index.test.tsx, components/InputTag/input-tag.tsx
|  InputTag | 修复 `InputTag` 粘贴文本自动分词的校验结果全部不通过时 `validate` 函数会连续触发两轮的问题。    |     Fix the issue that `validate` function will trigger two consecutive rounds when all the verification results of the automatic word segmentation of the pasted text of `InputTag` fail.          |                |
=> fix(InputTag): validate function will trigger twice while pasting if it validate result not pass

components/Select/option.tsx
|  Select   |  修复 `Select` 选项内容为空字符串时，选项在下拉列表中不展示的问题。  |  Fix the problem that the option is not displayed in the drop-down list when the content of the `Select` option is an empty string.  |   #1802  |
=> fix(Select): make sure Select option has height when its label is empty string

components/Form/__demo__/custom.md, components/Form/__test__/case.test.tsx, components/Form/context.ts, components/Form/control.tsx
|     Form      |  修复 `Form.Item` 组件在 `rerender` 时注入到自定义表单控件的 `value` 引用地址改变的 bug。             |    Fix the bug that the `value` reference address of the `Form.Item` component injected into the custom form control changes when `rerender`.           |       close #1800          |
=> fix: form value should keep equal when rerender

components/InputNumber/Decimal.ts, components/InputNumber/index.tsx, components/InputNumber/utils.ts
|   InputNumber  |  兼容不支持 `BigInt` 的旧时代浏览器。   |   Compatible with older browsers that don't support `BigInt`.   |  Close #1805       |
=> enhance(InputNumber): disable BigInt usage in low-version browsers

components/_class/select-view.tsx
|  Select  |  修复 `Select` 组件 `dragToSort` 和 `maxTagCount` 配合使用时，拖拽排序结果异常的问题。   |   Fix the problem that when the `Select` component `dragToSort` and `maxTagCount` are used together, the drag sorting result is abnormal.  |  Close #1825  |
=> fix(Select): dragToSort get wrong value when used with maxTagCount

components/Input/input-element.tsx, components/Transfer/__demo__/with-table.md
撤销 [此提交](https://github.com/arco-design/arco-design/commit/46ba4945e2fc5b21768de4c86af235f80838a8fa) 的改动，`<input>` 标签的宽度变化导致了 `InputTag` 的换行，引发下拉框抖动。
|   Select    |  修复 `Select` 多选模式下，选择第一个选项时下拉框抖动问题。  |   Fix `Select` multi-selection mode, when the first option is selected, the drop-down box shakes.   |                |
=> fix: InputTag height jittering caused by input element width change

components/InputTag/input-tag.tsx
|  Select   |   修复 `Select` 组件多选模式下点击 `Tag` 的关闭按钮删除选项时，`Select` 会变为 Focus 状态的问题。   |   Fix the problem that `Select` will be focused when clicking the close button of `Tag` to delete the option in the multi-select mode.  |                |
=> fix(Select): Select will be focused after clicking the close icon of value-tag

components/_class/select-view.tsx
|   Select     |  修复 `Select` 组件弹窗触发方式设置为 `focus` 不生效的 bug。  |   Fix the bug that setting the trigger mode of `Select` popup window to `focus` does not take effect.  |  Close #1905     |
=> fix(Select): triggerProps.trigger=focus not works

components/Input/input-element.tsx, components/InputTag/style/index.less
|   Select  |   修复 `Select` 多选模式下值被清空之后，其宽度缓慢恢复的问题。            |   Fix the problem that the width of `Select` is slowly restored after the value is cleared in multi-selection mode.    |                |
=> fix: Select width changes slowly after selected value tags are cleared

components/Image/image.tsx
|  Image  |  修复 `Image.previewProps` 字段更新后组件 UI 实际未更新的 bug。   |  Fix the bug that the component UI is not actually updated after the `Image.previewProps` field is updated.  |   Close #1971  |
=> fix(Image): Image not update after Image.previewProps updated

components/Input/textarea.tsx
|  Input |  修复 `Input.TextArea` 组件 `autoSize` 属性在非英文输入法时可能不生效的问题。   |   Fix the issue that the `autoSize` of the `Input.TextArea` may not take effect while typing non-English texts. |   Close #1084  |
=> fix(Input.TextArea): TextArea autoResize not work while composition updating

components/Statistic/index.tsx
|  Statistics   |   修复 `Statistics` 组件 `value` 不为数字时，传入的 `prefix` 未被渲染的问题。  |  Fix the problem that `prefix` passed in is not rendered when `value` of `Statistics` is not a number.   |      Close #2031          |
=> fix(Statistics): prefix is not rendered if value is not a number

components/Select/select.tsx, stories/Select.story.tsx
|    Select   |  `Select` 在选项 `label` 为富文本但通过 `triggerProps.style` 设置了弹出框宽度时，仍然保持其开启虚拟列表的能力。             |  `Select` still maintains its ability to open a virtual list when the option `label` is rich text but the width of the popup is set by `triggerProps.style`.    |    Close #2085  |
=> enhance(Select): judgement about whether to enable virtual list

components/Modal/__test__/index.test.tsx, components/Modal/modal.tsx
|   Modal        |  修复 `Modal` 组件设置 `unmountOnExit=true` 并关闭弹窗后，弹窗外层节点未被 `unmount` 的 bug。             |     Fix the bug that when the `Modal` component sets `unmountOnExit=true` and closes the pop-up window, the outer node of the pop-up window is not `unmount` bug.          |       close #2055         |
=> fix(modal): clear wrapper dom after close modal(unmountOnExit=true)

components/Collapse/__test__/index.test.tsx, components/Collapse/item.tsx
|   Collapse    |    修复 Collapse 组件父级节点 onClick 不冒泡触发           |     Fix parents of Collapse cant trigger `onClick` due to bubbling issue   |          Close #2099       |
=> fix: fix collapse item not bubbling issue

components/Input/index.tsx
Similar to the following code. When using `useRef` to refer to the `<Input />`, it is not easy to find the type definition.
```js
import {  Input } from '@arco-design/web-react';
import { RefInputType } from '@arco-design/web-react/es/Input/interface';
const input = useRef<RefInputType>(null);
```
Export `RefInputType` and `RefTextAreaType` types.
Of course, even if it is exported in `<Input />`, it needs to be referenced in `@arco-design/web-react/es/Input`. I am not sure whether it can be exported directly in `index.ts`, because I found that the exports in `index.ts` are `props + default component`. Maybe i can do it ?
|     Input      |       导出 `<Input />` 组件的 …
=> chore: export InputRef

components/Checkbox/checkbox.tsx, components/Radio/radio.tsx
radio和checkbox在label传入0时，因为&&短路操作直接显示0，而没有span包裹，使得在暗黑模式下显示为黑色文字
|       Radio   |  修复 `Radio` 组件在 `children` 为 0 时文本色异常的 bug。             |      Fix the bug that the text color of `Radio` component is abnormal when `children` is 0.         |                |
|       Checkbox|   修复 `Checkbox` 组件在 `children` 为 0 时文本色异常的 bug。             |      Fix the bug that the text color of `Checkbox` component is abnormal when `children` is 0.         |                |
- [ x] Test suite passes (`npm run test`)
- [x ] Provide changelog for relevant changes (e.g. bug fixes and new features) if applicable.
- [ x] Changes are submitted to the appropriate branch (e.g. features …
=> fix: radio和checkbox因为&&短路使得label缺少prefix-text包裹，而导致在暗黑模式下显示为黑色

components/TimePicker/time-picker.tsx
| TimePicker   | 修复 `TimePicker` 组件选中默认值没有兼容 `disabledHours` `disabledMinites` `DisabledSeconds` 的 bug。       | Fix the bug that the default value of `TimePicker` component is not compatible with `disabledHours` `disabledMinites` `DisabledSeconds`.   |                |
当我组件是这样，需要禁用某一天的一段时间，且在外部不受控的时候：
此时当我选了8点，他会默认选择0分钟：
但是00其实是被disabled了不应该被选中的
=> fix: time-picker disabled error

components/_class/select-view.tsx
| Select  |  修复 `Select` 组件宽度为 `auto` 且存在选中值时，聚焦后宽度丢失的问题。  | Fix the issue that `Select` lost width after focusing if its width is `auto` and has a selected value.  |                |
=> fix(Select): container lose width after focused if Select has a default value

components/Menu/__test__/index.test.tsx, components/Menu/util.ts
|    Menu   |   修复 `Popover` 作为 `Menu` 直接子节点报错的问题。  |   Fix the problem that `Popover` is reported as a direct child node of `Menu`.   |   Close #2129    |
=> fix(Menu): avoid tranforming single child to array while processing menu children

components/Select/style/mixin.less
|  Select  | 修复多选 `Select` 在 Chrome 116+ 设置 `showSearch=false` 时点击 `<input>` 区域下拉框无法展开的问题。 | Fix the problem that the drop-down box in the `<input>` area cannot be expanded when the multi-selection `Select` is set to `showSearch=false` in Chrome 116+.     |     |
=> fix(Select): dropdown-menu won't show if click the disabled input-element of Select

components/Timeline/__demo__/labelPosition.md, components/Timeline/__demo__/mode.md, components/Timeline/__demo__/pending.md
`TimelineItem` 的 `position` 属性没有 `bottom` 这个值，应该移除。
=> docs(Timeline):  remove useless position prop

components/Transfer/__demo__/with-tree.md
`Tree` 组件上不存在 `defaultExpandAll`，默认就是展开父级节点的，即展开所有。
=> docs(Transfer): remove useless prop defaultExpandAll

components/Typography/__demo__/ellipsis-controlled.md
`Space` 的 `size` 属性没有 `"middle"` 这个值，应该为 `"medium"`
=> docs(typography): update size from middle to medium

components/Tree/__demo__/controled.md
`setSelectedKeys(keys, extra)` 这个函数，第二个参数是没有意义的，`setState` 只接收一个参数
移除多余的参数
=> docs(Tree): setState只接收一个参数

components/TreeSelect/__demo__/fieldnames.md, components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap
文档的参数传输错误，`defaultSelectedKeys` 应该为 `defaultValue`，然后值之前是不在数据里的，修改了一个存在数据中的值。
=> docs(TreeSelect): defaultSelectedKeys should be defaultValue

components/Image/image.tsx
|  image         |   修复 `Image` 组件 `loader = true` 时加载状态未展示的问题。     |   Fix the problem that the loading status of `Image` is not displayed when `loader = true`.   |                |
看了代码，4个月前在支持lazyload的时候把173干掉了，导致loader为true时也无法进去defaultLoader。
=> fix: image defaultLoader

components/Table/__test__/components.test.tsx, components/Table/tbody/td.tsx, components/Table/utils.tsx
https://github.com/arco-design/arco-design/issues/2170
|    Table       |     修复 `Table` 组件的 render 属性第二个参数可能为 `undefined` 的 bug (该问题在 `2.50.2` 引入)          |    Fix the bug that the second parameter of the render attribute of the `Table` component may be `undefined`           |                |
=> fix(Table): the second parameter of the render function is undefined

components/List/style/index.less
| List  |  修复 `List` 组件设置可翻页时，切换 `pageSize` 的下拉框有时无法展开的问题。  |   Fix the issue that the drop-down for switching `pageSize` sometimes cannot be expanded when `List` enables pagination.   |    Close #2175   |
=> fix(List): pagination's dropdown is hidden caused by list wrapper's [overflow: hidden] style

components/Cascader/__test__/__snapshots__/demo.test.ts.snap, components/Cascader/__test__/__snapshots__/index.test.tsx.snap, components/ConfigProvider/__test__/__snapshots__/demo.test.ts.snap, components/Form/__test__/__snapshots__/demo.test.ts.snap, components/Input/__test__/__snapshots__/demo.test.ts.snap, components/Select/__test__/__snapshots__/demo.test.ts.snap, components/Select/__test__/__snapshots__/index.test.tsx.snap, components/Select/style/mixin.less, components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap, components/_class/select-view.tsx
| Select |  修复 `Select` 单选模式配合 `renderFormat` 和 `showSearch` 使用时，下拉框需要点击两次才能弹出的问题。  |   Fix the issue that when the `Select` is used with `renderFormat` and `showSearch`, the drop-down box needs to be clicked twice to pop up.  | |
=> fix(Select): dropdown-down won't show after clicking if use renderFormat with showSearch

components/Select/__test__/index.test.tsx, components/Select/select.tsx
|  Select   |  修复 `Select` 搜索文本改变后，回车会将之前选中的选项取消选中的 bug。  |   Fix the bug that after the `Select` search text is changed, pressing Enter will uncheck the previously selected option.   |    Close   #2209   |
=> fix(Select): active option should change after input value changed

components/Form/README.en-US.md, components/Form/README.zh-CN.md, components/Form/interface.tsx, components/Input/README.en-US.md, components/Input/README.zh-CN.md, components/Upload/README.en-US.md, components/Upload/README.zh-CN.md, components/Upload/__test__/apis.test.tsx, components/Upload/interface.tsx, components/Upload/upload.tsx, components/Upload/uploader.tsx, components/Upload/util.tsx
|    Upload       |      `Upload` 支持通过 `accept.strict` 设置 `accept` 属性遵循浏览器原生表现，不对文件后缀名进行严格匹配过滤         |    `Upload` supports setting the `accept` attribute through `accept.strict` to follow the browser's native behavior and does not strictly match and filter file extensions.           |      close #2196          |
|    Upload       |      `Upload`  组件 `onRemove` 方法支持回调参数传入当前文件列表     |    The `onRemove` method of the `Upload` component supports passing the callback parameter into the current file list     |       |
|    Upload       |      `Upload`  组件 `onRemove` 方法返回值的 TS 类型修正，`void` 调整为 `void \| boolean \| Promise<void \| boolean>`     |    The TS type correction …
=> feat: Upload supports accept.strict

components/TreeSelect/__test__/index.test.tsx, components/TreeSelect/tree-select.tsx
|   TreeSelect        |     修复 `TreeSelect` 组件的 `TreeData` 改变，未触发 `renderFormat` 重渲染的 bug。         |      Fixed the bug that the `renderFormat` re-rendering was not triggered when the `TreeData` of the `TreeSelect` component was changed.         |  #2214               |
=> fix: tree-select should rerender Text when treeData change

components/Image/__test__/__snapshots__/demo.test.ts.snap, components/Image/__test__/__snapshots__/index.test.tsx.snap, components/Image/image-preview.tsx, components/Image/image.tsx, components/Image/style/image.less
|   Image   |   避免鼠标右键按下时错误触发的图片拖拽。    |  Avoid image dragging that is triggered incorrectly when the right mouse button is pressed.   |    Close  #2231     |
| Image | 优化 Image 在 SSR 且开启 `lazyload` 时首次渲染出现裂图的问题。  | Optimize the problem of cracked image in the first rendering of Image in SSR and `lazyload` is enabled. |  Close #2215 |
=> enhance(Image): enter drag-mode only when mouse left button is pressed

components/Select/style/mixin.less
|   Select   |   修复 Firefox 浏览器中 `Select` 需要点击两次才能出现下拉框的问题。   |  Fixed the issue that `Select` needs to be clicked twice to display the drop-down box in Firefox.   |   Close #2127    |
=> fix(Select): dropdown-box need click twice to show in Firefox

components/Input/search.tsx
主要问题：Input.Search组件在受控状态下，并且maxLength设置为对象，onSearch函数不能接收到任何值，也就是搜索触发函数无法正确接收到Input.Search框里的值。
问题复现步骤：
- 1、使用Input.Search组件
- 2、设置props为受控组件，属性如下(主要是maxLength设为对象，value保证为受控状态，onSearch监测异常搜索)
```
<Input.Search
maxLength={{ errorOnly: true }}
value="受控状态OnSearch没有值"
onSearch={(v) => console.log(v)}
placeholder="Enter keyword to search"
style={{ width: 350 }}
/>
```
然后点击 放大镜图标，触发onSearch函数，此时控制台打印空字符串。
demo地址：https://codesandbox.io/s/friendly-satoshi-fkkg2m?file=/demo.js:0-450
代码没有正确处理 maxLength 参数为对象的情况，我主要加入了判断如果maxLength是对象的话，如何正确处理maxLength的逻辑。这个逻辑本身在Input组件上就使用了，我只是copy了这两行代码。
|    Input       | 修复 `Input.Search` 组件在 `value` 受控且传入了对象类型的 `maxLength`并直接触发 …
=> fix(Input): 修复Search组件受控状态异常问题

components/Cascader/interface.ts, components/Select/README.en-US.md, components/Select/README.zh-CN.md, components/Select/__demo__/allow-create.md, components/Select/__test__/index.test.tsx, components/Select/interface.tsx, components/Select/select.tsx, components/Select/utils.tsx, components/TreeSelect/interface.ts, components/_class/select-view.tsx
|   Select   |   `Select` 组件 `allowCreate` 属性允许传入 `formatter` 以格式化用户创建的选项。   |   The `allowCreate` property of `Select` allows passing in a `formatter` to format user-created options.   |     Close #2238    |
=> feat(Select): allowCreate support formatter fn to customize user-created option label

components/Cascader/README.en-US.md, components/Cascader/README.zh-CN.md, components/Cascader/__test__/__snapshots__/demo.test.ts.snap, components/DatePicker/__test__/__snapshots__/demo.test.ts.snap, components/Form/__test__/__snapshots__/demo.test.ts.snap, components/Input/README.en-US.md, components/Input/README.zh-CN.md, components/Input/__demo__/autoWidth.md, components/Input/__test__/__snapshots__/demo.test.ts.snap, components/Input/input-element.tsx, components/Input/input.tsx, components/Input/interface.tsx, components/Input/style/index.less, components/InputTag/__test__/__snapshots__/demo.test.ts.snap, components/InputTag/__test__/__snapshots__/index.test.tsx.snap, components/InputTag/input-tag.tsx, components/InputTag/style/index.less, components/Select/README.en-US.md, components/Select/README.zh-CN.md, components/Select/__demo__/autoWidth.md, components/Select/__test__/__snapshots__/demo.test.ts.snap, components/TimePicker/__test__/__snapshots__/demo.test.ts.snap, components/Tree/__test__/__snapshots__/demo.test.ts.snap, components/TreeSelect/README.en-US.md, components/TreeSelect/README.zh-CN.md, components/TreeSelect/__test__/__snapshots__/demo.test.ts.snap, components/Trigger/__test__/__snapshots__/demo.test.ts.snap, components/_class/select-view.tsx, components/_util/fillNBSP.ts
|   Select        |     `Select` 组件支持通过 `autoWidth` 属性设置宽度自适应。          |     The `Select` component supports setting width adaptation through the `autoWidth` property.          |     close #2249            |
|   Cascader        |     `Cascader` 组件支持通过 `autoWidth` 属性设置宽度自适应。          |     The `Cascader` component supports setting width adaptation through the `autoWidth` property.          |     close #2249            |
|   TreeSelect        |     `TreeSelect` 组件支持通过 `autoWidth` 属性设置宽度自适应。          |     The `TreeSelect` component supports setting width adaptation through the `autoWidth` property.          |     close #2249            |
|   Input        | …
=> feat: input and select all support autoWidth

components/Spin/__test__/index.test.tsx, components/Spin/index.tsx, components/_util/is.ts
|  Spin   |   修复 `Spin` 组件传入 Children 为 `0` 时，其子节点未渲染的问题。  |  Fixed the issue that the child node of `Spin` is not rendered when the child passed in was `0`.  |                |
=> fix(Spin): render child when it is 0/NaN

components/Input/style/index.less
| Input   |  修复 `Input` 组件具有前后缀时在 Safari 中清空文本导致垂直方向高度抖动的问题。  |   Fixed the issue that clear text of `Input` with prefix/suffix in Safari caused vertical jitter.  |     Close #2310    |
=> style(Input): vertical jitter in Safari when clear text content of input-box

components/List/index.tsx
|  List  |  修复 `List` 组件滚动时偶现的 `cannot read properties of null (reading 'scrollTop')` 错误。  |   Fix the `cannot read properties of null (reading 'scrollTop')` error that occasionally occurs when the `List` component is scrolling.   |  Close #2313   |
=> fix(List): error caused by getting scrollTop from [null]

components/InputTag/input-tag.tsx, components/Select/select.tsx
|  InputTag  |  修复 `InputTag` 组件 `onChange` 回调用时较长时自动分词将会连续触发两次的问题。 |    Fixed the bug that automatic word segmentation would be triggered twice in a row when the `onChange` callback of the `InputTag` took a long time.   |     Close #2376    |
=> fix(InputTag): word separate will be triggered twice if onChange takes a long time

components/Menu/README.en-US.md, components/Menu/README.zh-CN.md, components/Menu/index.tsx, components/Menu/interface.tsx, components/Menu/overflow-wrap.tsx
|  Menu  |  `Menu` 组件新增 `onEllipsisChange` 回调以通知水平菜单内容自动省略状态发生改变。   |  `Menu` component adds a `onEllipsisChange` callback to notify the horizontal menu ellipsis status changed. |   Close #2411      |
=> feat(Menu): new property onEllipsisChange for horizontal-menu ellipsis status change

components/InputTag/input-tag.tsx
[#2451](https://github.com/arco-design/arco-design/issues/2451)
删除 `minWidth: "100%"` 的设置
|  InputTag   |   优化 `InputTag` 清除所有标签时高度抖动的问题。   |    Optimize the issue of vertical jitter when clearing all tags in `InputTag`.     |   Close #2451  |
=> fix(select): 最后一个选项被清除时,高度会闪现2行的高度直到标签完全消失 (#2451)

components/DatePicker/picker-range.tsx, components/_class/picker/input-range.tsx
优化RangePicker input 框重置值的逻辑。
之前：
焦点切换才会重置输入的值。但是有些场景，用户自定义面板后，可能有点击面板的场景，这时候也需要对值进行清空。
之后：
输入框blur之后，就会进行值的清空。
=> Enhance inputvalue

components/ColorPicker/hooks/useColorPicker.ts
The onChange event of the ColorPicker component fires even when initializing.
Determine whether it is the first render.
Just add onChange={console.log} in `components/ColorPicker/__demo__/basic.md` and observe it
|    ColorPicker      |     修复 `ColorPicker` 初始化时触发`onChange` 的 bug         |       Fix the bug that triggers `onChange` when `ColorPicker` is initialized    |                |
=> fix: initializing ColorPicker trigger onChange

CONTRIBUTING.zh-CN.md, components/ColorPicker/__demo__/disabled.md, components/ColorPicker/__demo__/disabledAlpha.md, components/ColorPicker/__test__/__snapshots__/demo.test.ts.snap, components/ColorPicker/control-bar.tsx, components/ColorPicker/hooks/useColorPicker.ts, components/ColorPicker/index.tsx, components/ColorPicker/input-alpha.tsx, components/ColorPicker/input-hex.tsx, components/ColorPicker/input-rgb.tsx, components/ColorPicker/panel.tsx, components/ColorPicker/style/index.less, stories/ColorPicker.story.tsx
As reported in #2528,  disabledAlpha is in the API doc but not implemented
Implement disabledAlpha
看了下这个组件本身没单元测试，所以就只是更新了快照。
|ColorPicker| 支持 disabledAlpha | Add support for disabledAlpha  |  #2528  |
=> Fix(ColorPicker): Implement disabledAlpha (reported missing in #2528)

components/_class/VirtualList/index.tsx
|  Common  |  `VirtualListProps.onScroll` 回调新增第二个参数以通知当前视图区域内首个元素的索引。  |  The `VirtualListProps.onScroll` callback adds a second parameter to inform the index of the first element in the current view area.
|                |
=> feat(VirtualList): add parameter for onScroll to notify current list-item index

components/Image/image.tsx
|  Image  |   修复 `Image` 组件 `loading` 状态展示的问题   |    Fix the problem of `loading` status display of `Image` component  |   Close #2541    |
=> fix(image): when src change，set loading

components/Table/__demo__/virtualized.md, components/Table/style/index.less, components/Table/tbody/index.tsx, components/Table/tbody/tr.tsx
|  Table  |  `Table` 组件虚拟滚动开启时支持展开行和树形数据。  |   `Table` component supports expanding rows and tree data when virtual scrolling is turned on.   |   Close #2543  |
=> enhance(Table): support expanedRows and treeData while Table is virtualized

components/Form/README.en-US.md, components/Form/README.zh-CN.md, components/Form/interface.tsx, components/Modal/README.en-US.md, components/Modal/interface.ts
Some of the `Form.Item` API docs are missing
Add children description for Form.Item API
Add isFormList description for Form.Item API
Add layout description for Form.Item API
|Property|Description|Type|DefaultValue|Version|
|---|---|---|---|---|
|children|`React.ReactNode` type and Fuction type children| React.ReactNode \| (formData: any, form: FormInstance<FormData, FieldValue, FieldKey>) => React.ReactNode |`-`|-|
|layout|布局|'horizontal' \| 'vertical' \| 'inline' |`-`|-|
=> docs: add some descriptions for Form.Item API

components/Typography/__demo__/ellipsis-basic.md, components/Typography/__test__/__snapshots__/demo.test.ts.snap, components/Typography/ellipsis.tsx, components/Typography/interface.tsx
|   Typography   |   `Ellipsis` 支持单行展开按钮的展示   |    `Ellipsis` to support the display of single-line expand buttons    |                |
=> feat: update expandable

components/Radio/radio.tsx
在分析 issues [#2649](https://github.com/arco-design/arco-design/issues/2649) 中的问题时，发现主要问题是 Radio 与 Checkbox 组设置 `disabled` 属性后表现不一致。
- 在 Radio.Group 中设置 `disabled` 属性，Radio.Group 中的所有 Radio 都会被禁用, 在 Radio 中单独设置 `disabled={false}` **无效**。
- 在 Checkbox.Group 中设置 `disabled` 属性，Checkbox.Group 中的所有 Checkbox 都会被禁用, 在 Checkbox 中单独设置 `disabled={false}` **有效**。
代码示例：
```jsx
<div>
<p>Radio:</p>
<Radio.Group disabled>
<Radio value="Option1">Option 1</Radio>
<Radio disabled={false} value="Option2">
Option 2
</Radio>
</Radio.Group>
<p>CheckBox:</p>
<Checkbox.Group disabled>
<Checkbox value="Option1">Option 1</Checkbox>
<Checkbox disabled={false} value="Option2">
Option 2
</Checkbox>
</Checkbox.Group>
</div>
```
考虑到更好的配置性，Checkbox 的表现效果更符合要求，就是 Group 设置禁用态后，改为子项也可以独立配置，这样可以满足更多的使用场景
优先获取 Radio 的 disabled …
=> fix: adjustment of merging priority for radio disabled state

components/InputTag/input-tag.tsx, components/_class/select-view.tsx, components/_util/hooks/usePersistCallback.ts
This PR mainly enhance the SelectView performance. Related issue: https://github.com/arco-design/arco-design/issues/2689
1. memo tagsToShow
2. break the for loop in tagsToShow memo callback (former in renderMultiple) as soon as possible.
3. lastCloseableTagIndex calculation moved to onRemove callback
|      Select     |         优化 SelectView 渲染逻辑，避免选中多个结点时渲染卡顿      |     Enhance the rendering performance of SelectView          |           fix https://github.com/arco-design/arco-design/issues/2689     | 
| InputTag|优化 InputTag 渲染逻辑，降低时间复杂度| reduce time complexity of InputTag |
=> perf: enhance rendering performance of SelectView

components/Tree/node.tsx
在tree onDragStart 事件 dataTransfer.setData('text/plain')设置不上
emit之前去设置node的dataTransfer.setData
|  Tree         |      修复 `Tree` 组件在 `onDragStart` 设置 `dataTransfer.setData` 不生效的 bug。      |       Fixed the bug where `dataTransfer.setData` does not take effect when setting `dataTransfer.setData` in `onDragStart` of `Tree` component.        |                |
=> fix: 导致用户自己设置的dataTransfer.setData('text/plain')失效

components/_class/picker/input-range.tsx, components/_class/picker/input.tsx
当前组件存在两个问题：
1. DatePicker 和 RangePicker 缺少 `onFocus` 事件的样式，导致在使用 Tab 键和 `ref.current.focus()` 方法的时候没有正确显示聚焦样式
2.  RangePicker 组件使用 Tab 键切换焦点的时候，无法在组件的两个 `<input />` 之间切换，也无法通过Tab将焦点切换到其他组件上
Two issues of current components:
1. DatePicker and RangePicker lack the style of `onFocus` event, causing the focused style to not be displayed correctly when using Tab and `ref.current.focus()` method.
2. When using Tab to move the focus point inside RangePicker, the focusing point cannot be moved from one `<input />` components to the other, and the focus point cannot be moved away from RangePicker by using Tab.
| 现有效果 Current Behavior with Tab | 期待效果 Expected Behavior with Tab | 
| --------- | ------------- |
| 一旦进入RangePicker，则焦点不能切走 Once focused on RangePicker, the focus point cannot be moved …
=> fix: change tab behavior for RangePicker and reuse focused style while focused

components/Cascader/hook/useRefCurrent.ts
Fixed a small typo in text `forceUdpate`, it should be `forceUpdate`.
|              |               |               |                |
=> chore: fix typo in text forceUpdate

components/ColorPicker/index.tsx, stories/ColorPicker.story.tsx
fix #2821 
仿照Button组件方式，使用 ConfigContext 的 size
|      ColorPicker     |      修复 `ConfigProvider` 对 `ColorPicker` 提供的 size 属性不生效 bug。         |   Fixed the bug that the size attribute provided by `ConfigProvider` for `ColorPicker` does not take effect.       |   close    #2821          |
=> fix(ColorPicker): use the size form ConfigProvider when there is no size property

components/DatePicker/panels/header.tsx, components/DatePicker/picker.tsx
- [] Enhancement
|     DatePicker      |    修复 `DatePicker` 组件          |         Fixed the bug that some nodes of the `DatePicker` component lacked `key`, causing the console `warning`      |    #2854   close #2856          |
=> fix: datepicker warning key

components/InputTag/__changelog__/index.en-US.md, components/InputTag/__changelog__/index.zh-CN.md, components/InputTag/input-tag.tsx, components/Select/__demo__/maxTag.md, components/Select/__test__/__snapshots__/demo.test.ts.snap, components/_class/select-view.tsx, site/docs/version_v2.en-US.md, site/docs/version_v2.zh-CN.md
|   InputTag        |     修复 `InputTag` 组件 `renderTag` 会针对 `+x...` 标签执行的 bug。（`2.62.0` 引入）          |Fixed the bug that `renderTag` of `InputTag` component will execute for `+x...` tag. (Introduced in `2.62.0`)|                |
|   Select        |     修复 `Select` / `Cascader` / `TreeSelect` 组件设置 `maxTagCount` 后，拖拽排序导致部分已选中值取消选中的 bug。（2.62.0 引入）          |       Fixed the bug that after `maxTagCount` is set for `Select` / `Cascader` / `TreeSelect` components, drag and sort will cause some selected values ​​to be unselected. (Introduced in` 2.62.0`)        |                |
|   Select        |    `Select` / `Cascader` / `TreeSelect` 组件支持通过 `maxTagCount.showPopover` …
=> feat: max tag bugfix & feature

components/ColorPicker/README.en-US.md, components/ColorPicker/README.zh-CN.md, components/ColorPicker/__demo__/colors.md, components/ColorPicker/__demo__/mode.md, components/ColorPicker/__demo__/trigger.md, components/ColorPicker/__test__/__snapshots__/demo.test.ts.snap, components/ColorPicker/control-bar.tsx, components/ColorPicker/hooks/useColorPicker.ts, components/ColorPicker/hooks/useControlBlock.ts, components/ColorPicker/index.tsx, components/ColorPicker/interface.ts, components/ColorPicker/mode.ts, components/ColorPicker/panel.tsx, components/ColorPicker/style/index.less, components/ColorPicker/style/token.less, components/ColorPicker/utils.ts, components/_util/color.ts, components/locale/en-US.tsx, components/locale/ja-JP.tsx, components/locale/zh-CN.tsx, components/locale/zh-HK.tsx, components/locale/zh-TW.tsx
Add gradient mode to `ColorPicker` component. // 为 ColorPicker 组件添加渐变模式
`ColorPicker` will support `mode` property. 
`mode` could be `single`(by default), `gradient` or both `['single', 'gradient']`.
A `Radio` will appear on the color panel for the user to select a single color or gradient colors for when `mode`is`['single', 'gradient']`.
// `ColorPicker` 颜色选择器将支持`mode`字段
// `mode`字段可设置为 `single`（默认值）、`gradient`或 `['single', 'gradient']`
// 当`mode`值为`['single', 'gradient']`时，颜色面板上将出现一个`Radio`单选框以便用户选择单个颜色或渐变色
|ColorPicker|支持`mode`来选择单个颜色或渐变色。|support `mode` to select a single color or gradient colors.|-|
由于此前的内部实现无法直接支持渐变模式的多值 value，因此 ColorPicker 中部分 hooks 与 …
=> Feat: support gradient mode for ColorPicker

components/Form/hooks/useWatch.ts, stories/Form.story.tsx
Types definition of `Form.useWatch` does not accept generic types as `Form.useForm`, which causes when passing a typed FormInstance (such as `FormInstance<T>`) to `Form.useWatch` as a second parameter will cause unexpected types error.
Related Posts:
- https://github.com/arco-design/arco-design/pull/2779 This PR is not accepted because it introduced a breaking change - a generic type parameter without default value.
- https://github.com/arco-design/arco-design/issues/1895
1. Strong types support for `useWatch` using type inference and generic.
2. Provide a fallback type `any` for not making break changes.
Since I didn't change any runtime behavior, I simply edit the `form.story.tsx` to test the added types of `Form.useWatch`.
| Component | Changelog(CN) …
=> fix(form/use-watch): strong typing for Form.useWatch without breaking changes
